/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Algebra.Order.BigOperators.Group.Finset
import Mathlib.Data.Nat.Factorial.Basic

/-!
# CXI01: the positive-moment cone has a fully-disjoint recession ray

The G123--G127 matching-moment LP has depth-column weights

```text
  w_m(s) = (r - s).descFactorial m.
```

Every genuinely descending row has `m > 0`, hence `w_m(r) = (0)_m = 0` at the
fully-disjoint depth `s = r`.  This file turns the observation into an exact convex no-go:

* adding arbitrary mass on the full-depth coordinate leaves every blind nonnegative linear
  constraint unchanged;
* in particular, all positive matching-moment constraints admit an unbounded full-depth ray;
* no conic combination of the positive descent rows can dominate a cost with positive
  full-depth coefficient;
* if the zeroth row is admitted, the full-depth dual column is exactly `lam 0`, so every such
  domination certificate must pay a positive multiple of row zero.  In the census LP row zero is
  the total open-rung energy itself, making that move circular rather than a descent estimate.

This fences not just one chosen LP multiplier but the entire cone generated by positive matching
moments.  Moment-SOS, flag-SDP, maximum-entropy, and rational-dual proposals that only consume those
rows need a genuinely new arithmetic statistic nonzero on the zero-match/full-depth atom.

**Honest scope.**  This proves a method-class obstruction, not a census bound.  Arithmetic-labeled
constraints that see fully-disjoint relations remain admissible, and the Paley/proximity CORE
remains open.  Issues #466/#505.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession

open Finset
open scoped BigOperators

/-- The depth-column coefficient in the matching-moment descent LP. -/
def descentWeight (r m s : ℕ) : ℕ :=
  (r - s).descFactorial m

/-- Every positive matching-moment row vanishes on the fully-disjoint depth. -/
theorem descentWeight_fullDepth_eq_zero (r m : ℕ) (hm : 0 < m) :
    descentWeight r m r = 0 := by
  rw [descentWeight, Nat.sub_self]
  exact Nat.descFactorial_eq_zero_iff_lt.mpr hm

/-- A census supported only at the fully-disjoint depth. -/
def fullDepthSpike (r t : ℕ) : ℕ → ℕ :=
  fun s => if s = r then t else 0

/-- Any nonnegative linear statistic whose full-depth coefficient is zero evaluates to zero on
the full-depth spike. -/
theorem weightedSum_fullDepthSpike_eq_zero (r t : ℕ) (w : ℕ → ℕ)
    (hw : w r = 0) :
    ∑ s ∈ Finset.range (r + 1), w s * fullDepthSpike r t s = 0 := by
  apply Finset.sum_eq_zero
  intro s hs
  by_cases hsr : s = r
  · subst s
    simp [fullDepthSpike, hw]
  · simp [fullDepthSpike, hsr]

/-- **General recession theorem.**  Any family of nonnegative linear constraints blind at depth
`r` has feasible censuses with arbitrarily large depth-`r` coordinate. -/
theorem blindConstraints_have_unbounded_fullDepth_ray {I : Type*}
    (weights : I → ℕ → ℕ) (bounds : I → ℕ) (r B : ℕ)
    (hblind : ∀ i, weights i r = 0) :
    ∃ x : ℕ → ℕ,
      (∀ i, ∑ s ∈ Finset.range (r + 1), weights i s * x s ≤ bounds i) ∧
        B < x r := by
  refine ⟨fullDepthSpike r (B + 1), ?_, ?_⟩
  · intro i
    rw [weightedSum_fullDepthSpike_eq_zero r (B + 1) (weights i) (hblind i)]
    exact Nat.zero_le _
  · simp [fullDepthSpike]

/-- The entire family of positive matching-moment rows admits the full-depth recession ray. -/
theorem positiveDescentConstraints_have_unbounded_fullDepth_ray
    (budgets : ℕ → ℕ) (r B : ℕ) :
    ∃ x : ℕ → ℕ,
      (∀ m, 0 < m → m ≤ r →
        ∑ s ∈ Finset.range (r + 1), descentWeight r m s * x s ≤ budgets m) ∧
        B < x r := by
  refine ⟨fullDepthSpike r (B + 1), ?_, ?_⟩
  · intro m hm _
    rw [weightedSum_fullDepthSpike_eq_zero r (B + 1)
      (descentWeight r m) (descentWeight_fullDepth_eq_zero r m hm)]
    exact Nat.zero_le _
  · simp [fullDepthSpike]

/-- Conversely, the first positive-moment row detects every shallow nonnegative direction: if its
value is zero, every coordinate strictly below full depth is zero.  Together with the spike theorem,
this identifies the common nonnegative recession cone exactly as the full-depth ray. -/
theorem zero_firstDescentMoment_forces_shallow_zero (x : ℕ → ℕ) (r : ℕ)
    (hzero : ∑ s ∈ Finset.range (r + 1), descentWeight r 1 s * x s = 0) :
    ∀ s, s < r → x s = 0 := by
  intro s hsr
  have hmem : s ∈ Finset.range (r + 1) :=
    Finset.mem_range.mpr (hsr.trans (Nat.lt_succ_self r))
  have hterm : descentWeight r 1 s * x s = 0 :=
    (Finset.sum_eq_zero_iff_of_nonneg (fun i hi ↦ Nat.zero_le _)).mp hzero s hmem
  have hcoeffPos : 0 < descentWeight r 1 s := by
    rw [descentWeight, Nat.descFactorial_pos]
    exact Nat.sub_pos_of_lt hsr
  exact (Nat.mul_eq_zero.mp hterm).resolve_left (Nat.ne_of_gt hcoeffPos)

/-- Every conic combination of the positive descent rows still has zero full-depth coefficient. -/
theorem positiveDescentDual_fullDepth_eq_zero (r : ℕ) (lam : ℕ → ℕ) :
    ∑ m ∈ Finset.range r, lam (m + 1) * descentWeight r (m + 1) r = 0 := by
  apply Finset.sum_eq_zero
  intro m hm
  rw [descentWeight_fullDepth_eq_zero r (m + 1) (Nat.succ_pos m), Nat.mul_zero]

/-- No conic combination of positive descent rows can dominate a target that assigns positive
cost to the fully-disjoint coordinate. -/
theorem no_positiveDescentDual_dominates_fullDepth (r : ℕ) (lam c : ℕ → ℕ)
    (hc : 0 < c r) :
    ¬ c r ≤ ∑ m ∈ Finset.range r,
      lam (m + 1) * descentWeight r (m + 1) r := by
  rw [positiveDescentDual_fullDepth_eq_zero r lam]
  exact Nat.not_le_of_lt hc

/-- Once row zero is included, the full-depth dual column is exactly its multiplier. -/
theorem descentDual_fullDepth_eq_rowZero (r : ℕ) (lam : ℕ → ℕ) :
    ∑ m ∈ Finset.range (r + 1), lam m * descentWeight r m r = lam 0 := by
  have hzero : ∀ m ∈ Finset.range (r + 1), m ≠ 0 →
      lam m * descentWeight r m r = 0 := by
    intro m hm hne
    have hmpos : 0 < m := Nat.pos_of_ne_zero hne
    rw [descentWeight_fullDepth_eq_zero r m hmpos, Nat.mul_zero]
  rw [Finset.sum_eq_single_of_mem 0
    (Finset.mem_range.mpr (Nat.succ_pos r)) hzero]
  simp [descentWeight]

/-- Therefore every dual domination of a positive full-depth target must use row zero with a
positive multiplier. -/
theorem fullDepth_domination_requires_rowZero (r : ℕ) (lam c : ℕ → ℕ)
    (hc : 0 < c r)
    (hdom : c r ≤ ∑ m ∈ Finset.range (r + 1),
      lam m * descentWeight r m r) :
    0 < lam 0 := by
  rw [descentDual_fullDepth_eq_rowZero r lam] at hdom
  exact hc.trans_le hdom

end ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession

/-! ## Axiom audit -/
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.descentWeight_fullDepth_eq_zero
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.blindConstraints_have_unbounded_fullDepth_ray
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.positiveDescentConstraints_have_unbounded_fullDepth_ray
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.zero_firstDescentMoment_forces_shallow_zero
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.no_positiveDescentDual_dominates_fullDepth
#print axioms
  ArkLib.ProximityGap.Frontier.CXI01PositiveMomentConeRecession.fullDepth_domination_requires_rowZero
