/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors (#466, lane W4)
-/
import Mathlib.GroupTheory.FiniteAbelian.Duality
import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
import Mathlib.NumberTheory.LegendreSymbol.AddCharacter
import Mathlib.Analysis.Complex.Polynomial.Basic
import Mathlib.Algebra.CharP.Lemmas

set_option autoImplicit false
set_option linter.style.longLine false

/-!
# The function-field model of the prize law is DEGENERATE (#466, lane W4)

**Question (dossier v3 §6, Tier-3 "function-field model theorem").** Is there a provable
function-field analogue of the prize-shaped law
`M(μ_n) = max_{ψ ≠ 1} |Σ_{x∈μ_n} ψ(x)| ≲ √(n log m)` for a thin 2-power multiplicative
structure in `F_q[t]/(f)` — exploiting that Weil/RH is a theorem for function fields?

**Answer: NO — the kill-risk fires, and this file machine-checks the two degeneracy
mechanisms** (probe: `scripts/probes/probe_466_function_field.py` /
`_out_466_function_field.txt`; kb note: `docs/kb/deltastar-466-w4-function-field-model-*.md`).

* **Mechanism 1 (thin residue-ring regime = subfield countermodel).** `F_q[t]/(f)` with `f`
  irreducible of degree `d` IS the finite field `F_{q^d}`, and `μ_n` generates only the
  subfield `F_{q^e}`, `e = ord_n(q)`. Whenever the thinness is manufactured by growing
  `deg f` past `e` (the ONLY route at fixed `q`), `μ_n` lies in a **proper** additive
  subgroup that is the kernel of `x ↦ x^{q^e} − x`, and duality for finite abelian groups
  produces a **nontrivial** additive character that is `1` on all of `μ_n`:
  `Σ_{x∈μ_n} ψ(x) = n` **exactly** — zero cancellation, the law `M = o(n)` is FALSE.
  Formalized here as:
  - `exists_addChar_annihilator_of_notMem` — duality witness (character trivial on a
    subgroup, nontrivial at a chosen `x ∉ K`); input: Mathlib's
    `CommGroup.forall_monoidHom_apply_eq_one_iff`.
  - `thin_regime_zero_cancellation` — abstract zero-cancellation countermodel.
  - `frobPow_fixed_ne_top` — the fixed set of `x ↦ x^{p^s}` is proper when `p^s < |F|`
    (root counting, no Weil input).
  - `ffThin_prizeLaw_countermodel` — **the assembled kill**: in any finite field `F` with
    `n ∣ p^s − 1 < |F|` there is `ψ ≠ 1` with `Σ_{x^n = 1} ψ(x) = #{x : x^n = 1}`.
* **Mechanism 2 (Carlitz-module transliteration is degenerate).** The Carlitz analogue of
  `μ_n` (torsion `C[t^μ]`) is an `F_q`-LINEAR SUBSPACE of the residue field — the Carlitz
  module deforms the ADDITIVE group. Additive-character sums over any additive subgroup
  take only the two values `{|V|, 0}`:
  - `carlitz_additive_dichotomy` — the sum over an additive subgroup is `card` or `0`.
  The non-degenerate pairing (Carlitz torsion × multiplicative character) is the Thakur
  Gauss sum, whose size is v-adically pinned (Gross–Koblitz/Thakur) — not an archimedean
  sup; prior art `docs/kb/bourgain-p5-creative-farreaches-2026-06-15.md` §4.

## Honest scope

* These are elementary (non-Weil) statements; their value is that they machine-check WHY
  no function-field model theorem exists: every FF instantiation of the prize shape is
  either **false** (Mechanism 1), **degenerate** (Mechanism 2), or **verbatim the open
  prime-field problem** (the generating case `d = e`, where the probe shows the same
  empirical √2-law and Weil/RH-for-curves — a theorem over `F_p` too — is identically
  vacuous: `√Q > n` whenever the index exceeds `n`).
* Nothing here touches the open core; `isPrizeClosure := false`. This is a REFUTATION
  artifact (countermodel = WIN per the honesty contract).
-/

namespace FFModelW4

open Finset

/-! ### Mechanism 1: the subfield countermodel -/

section Duality

variable {L : Type*} [AddCommGroup L] [Finite L]

/-- **Duality witness.** For a proper additive subgroup `K` of a finite abelian group `L`
and `x ∉ K`, there is a complex additive character that is `1` on `K` but not at `x`.
(The function-field instantiation: `L` = residue field `F_{q^d}`, `K` = the subfield
`F_{q^e}` generated by `μ_n`, available as an additive subgroup.) -/
theorem exists_addChar_annihilator_of_notMem (K : AddSubgroup L) {x : L} (hx : x ∉ K) :
    ∃ ψ : AddChar L ℂ, (∀ y ∈ K, ψ y = 1) ∧ ψ x ≠ 1 := by
  classical
  -- move to the multiplicative avatar and use finite-abelian duality
  have hexp : NeZero ((Monoid.exponent (Multiplicative L) : ℕ) : ℂ) :=
    ⟨Nat.cast_ne_zero.mpr Monoid.exponent_ne_zero_of_finite⟩
  have hsep : ¬ (∀ φ : Multiplicative L →* ℂˣ,
      (∀ y ∈ AddSubgroup.toSubgroup K, φ y = 1) → φ (Multiplicative.ofAdd x) = 1) := by
    rw [CommGroup.forall_monoidHom_apply_eq_one_iff (M := ℂ)]
    simpa using hx
  push_neg at hsep
  obtain ⟨φ, hφK, hφx⟩ := hsep
  refine ⟨AddChar.toMonoidHomEquiv.symm ((Units.coeHom ℂ).comp φ), fun y hy => ?_, fun h => ?_⟩
  · have hy1 : φ (Multiplicative.ofAdd y) = 1 := hφK (Multiplicative.ofAdd y) (by simpa using hy)
    simp [AddChar.toMonoidHomEquiv_symm_apply, hy1]
  · rw [AddChar.toMonoidHomEquiv_symm_apply] at h
    exact hφx (Units.ext (by simpa using h))

/-- **Thin-regime zero cancellation (abstract form).** If a finite subset `H` (e.g. `μ_n`)
of a finite abelian group `L` is contained in a PROPER subgroup `K`, then some NONTRIVIAL
additive character has `Σ_{x∈H} ψ(x) = |H|` — no cancellation whatsoever. This falsifies
any `o(|H|)` sup-norm law over the ambient group. -/
theorem thin_regime_zero_cancellation (K : AddSubgroup L) (hK : K ≠ ⊤)
    (H : Finset L) (hHK : ∀ x ∈ H, x ∈ K) :
    ∃ ψ : AddChar L ℂ, ψ ≠ 1 ∧ ∑ x ∈ H, ψ x = (H.card : ℂ) := by
  obtain ⟨x, hx⟩ : ∃ x, x ∉ K := by
    by_contra h
    push_neg at h
    exact hK (AddSubgroup.eq_top_iff' K |>.mpr h)
  obtain ⟨ψ, hψK, hψx⟩ := exists_addChar_annihilator_of_notMem K hx
  refine ⟨ψ, fun h => hψx (by simp [h]), ?_⟩
  calc ∑ x ∈ H, ψ x = ∑ _x ∈ H, (1 : ℂ) :=
        Finset.sum_congr rfl fun y hy => hψK y (hHK y hy)
    _ = (H.card : ℂ) := by simp

end Duality

section FiniteField

variable {F : Type*} [Field F] [Fintype F] {p : ℕ} [Fact p.Prime] [CharP F p]

/-- `x ↦ x^{p^s} − x` is additive in characteristic `p` (Frobenius-power difference). -/
def frobPowDiff (F : Type*) [Field F] (p : ℕ) [Fact p.Prime] [CharP F p] (s : ℕ) :
    F →+ F where
  toFun x := x ^ p ^ s - x
  map_zero' := by
    rw [zero_pow (pow_ne_zero s (Fact.out : p.Prime).pos.ne'), sub_zero]
  map_add' a b := by
    rw [add_pow_char_pow]
    ring

@[simp] lemma frobPowDiff_apply (s : ℕ) (x : F) :
    frobPowDiff F p s x = x ^ p ^ s - x := rfl

/-- Membership in the Frobenius-power fixed subgroup. -/
lemma mem_ker_frobPowDiff {s : ℕ} {x : F} :
    x ∈ (frobPowDiff F p s).ker ↔ x ^ p ^ s = x := by
  rw [AddMonoidHom.mem_ker, frobPowDiff_apply, sub_eq_zero]

/-- `μ_n` lands in the Frobenius-power fixed subgroup as soon as `n ∣ p^s − 1`
(this is `μ_n ⊆ F_{p^s}`, the subfield-containment that drives the countermodel). -/
lemma pow_frobPow_eq_self_of_root_of_unity {n s : ℕ} (hn : n ∣ p ^ s - 1) {x : F}
    (hx : x ^ n = 1) : x ^ p ^ s = x := by
  have hps : 1 ≤ p ^ s := Nat.one_le_pow _ _ (Fact.out : p.Prime).pos
  obtain ⟨c, hc⟩ := hn
  have h1 : x ^ (p ^ s - 1) = 1 := by rw [hc, pow_mul, hx, one_pow]
  calc x ^ p ^ s = x ^ (p ^ s - 1 + 1) := by rw [Nat.sub_add_cancel hps]
    _ = x := by rw [pow_succ, h1, one_mul]

/-- **Properness (no Weil needed):** when `p^s < |F|`, the Frobenius-power fixed subgroup
is proper — the polynomial `X^{p^s} − X` has at most `p^s` roots. -/
lemma frobPow_fixed_ne_top {s : ℕ} (hs : 1 ≤ s) (hcard : p ^ s < Fintype.card F) :
    (frobPowDiff F p s).ker ≠ ⊤ := by
  classical
  intro htop
  have hall : ∀ y : F, y ^ p ^ s = y := fun y =>
    mem_ker_frobPowDiff.mp (htop ▸ AddSubgroup.mem_top y)
  -- the polynomial X^{p^s} − X then has every element of F as a root
  set P : Polynomial F := Polynomial.X ^ p ^ s - Polynomial.X with hP
  have hm : 1 < p ^ s := by
    calc 1 < p := (Fact.out : p.Prime).one_lt
      _ = p ^ 1 := (pow_one p).symm
      _ ≤ p ^ s := Nat.pow_le_pow_right (Fact.out : p.Prime).pos hs
  have hdeg : P.natDegree = p ^ s := by
    rw [hP, Polynomial.natDegree_sub_eq_left_of_natDegree_lt] <;>
      simp [Polynomial.natDegree_X_pow, Polynomial.natDegree_X, hm]
  have hP0 : P ≠ 0 := Polynomial.ne_zero_of_natDegree_gt (n := 0) (by omega)
  have hroots : ∀ y : F, y ∈ P.roots := fun y => by
    rw [Polynomial.mem_roots hP0]
    simp [hP, Polynomial.IsRoot, sub_eq_zero, hall y]
  have hsub : Finset.univ ⊆ P.roots.toFinset := fun y _ => by
    simpa using hroots y
  have : Fintype.card F ≤ p ^ s :=
    calc Fintype.card F = Finset.univ.card (α := F) := rfl
      _ ≤ P.roots.toFinset.card := Finset.card_le_card hsub
      _ ≤ Multiset.card P.roots := P.roots.toFinset_card_le
      _ ≤ P.natDegree := P.card_roots'
      _ = p ^ s := hdeg
  omega

/-- **THE FUNCTION-FIELD THIN-REGIME COUNTERMODEL (assembled).**

In any finite field `F` (= `F_q[t]/(f)`, `q = p^r`, `f` irreducible) whose cardinality
strictly exceeds `p^s`, and any `n ∣ p^s − 1` (so that `μ_n` lies in the copy of `F_{p^s}`
inside `F`), there is a **nontrivial** additive character with
`Σ_{x^n=1} ψ(x) = #μ_n` exactly.

Consequence: manufacturing a large index `m = (|F|−1)/n` by growing `deg f` at fixed
constant field — the ONLY thinness dial the function-field model has — makes the
prize-shaped law `M(μ_n) = o(n)` (a fortiori `M ≲ √(n log m)`) **FALSE**. The
function-field transplant of the prize law has NO model theorem; the sole non-degenerate
instantiation is `F = F_p(μ_n)` itself, i.e. the verbatim open problem. -/
theorem ffThin_prizeLaw_countermodel [DecidableEq F] {n s : ℕ}
    (hs : 1 ≤ s) (hn : n ∣ p ^ s - 1) (hcard : p ^ s < Fintype.card F) :
    ∃ ψ : AddChar F ℂ, ψ ≠ 1 ∧
      ∑ x ∈ Finset.univ.filter (fun x : F => x ^ n = 1), ψ x
        = ((Finset.univ.filter (fun x : F => x ^ n = 1)).card : ℂ) := by
  refine thin_regime_zero_cancellation (frobPowDiff F p s).ker
    (frobPow_fixed_ne_top hs hcard) _ (fun x hx => ?_)
  rw [Finset.mem_filter] at hx
  exact mem_ker_frobPowDiff.mpr (pow_frobPow_eq_self_of_root_of_unity hn hx.2)

end FiniteField

/-! ### Mechanism 2: Carlitz-module transliteration is degenerate -/

section Carlitz

variable {L : Type*} [AddCommGroup L]

/-- **Carlitz additive degeneracy.** Any Carlitz-module analogue of `μ_n` (torsion of the
Carlitz module, or of any Drinfeld module) is an `F_q`-linear subspace — in particular an
additive subgroup `V` — of the residue field. Additive-character sums over an additive
subgroup take only the two values `{|V|, 0}`: the naive transliteration of the prize sup
is identically degenerate (`max = |V|`, attained by the `|L|/|V| − 1 ≥ q − 1 > 0`
nontrivial characters annihilating `V`, cf. `thin_regime_zero_cancellation`). -/
theorem carlitz_additive_dichotomy (V : AddSubgroup L) [Fintype V] (ψ : AddChar L ℂ) :
    (∑ v : V, ψ (v : L)) = (Fintype.card V : ℂ) ∨ (∑ v : V, ψ (v : L)) = 0 := by
  classical
  by_cases h1 : ψ.compAddMonoidHom V.subtype = (1 : AddChar V ℂ)
  · left
    have hone : ∀ v : V, ψ (v : L) = 1 := fun v => by
      have := DFunLike.congr_fun h1 v
      simpa using this
    simp [hone]
  · right
    have := AddChar.sum_eq_zero_of_ne_one (R := V) (R' := ℂ) h1
    simpa using this

end Carlitz

end FFModelW4

-- Axiom audit (honesty contract: axiom-clean = [propext, Classical.choice, Quot.sound])
#print axioms FFModelW4.exists_addChar_annihilator_of_notMem
#print axioms FFModelW4.thin_regime_zero_cancellation
#print axioms FFModelW4.frobPow_fixed_ne_top
#print axioms FFModelW4.ffThin_prizeLaw_countermodel
#print axioms FFModelW4.carlitz_additive_dichotomy
