/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib.Tactic

/-!
# G246: a degree-two Krylov recurrence countermodel for the quotient-incidence route (#466)

G245 found the exact self-adjoint physical normal form of the current signed target.  For
`Q = F_p^* / G`, `|G| = n`, and

```text
N[A,B] = #{x in A : 2 - x in B},
```

one has `N = Nᵀ`, the weighted kernel row is `W_G(t) = N[G,tG]` in the sponsor regime
`2 ∉ G`, and the rank-`r` covariance is the mixed quotient matrix coefficient
`p*n*⟨N e_G, R_r^Q⟩ - n²*binom(n,r)`.  That identity is a real structural normal form, but the
only way it could beat the BGK/Jacobi wall would be if the adjacent-rank profile `R_r^Q` were
generated by a bounded-degree polynomial in `N` from the distinguished row/point.  G245's exact
probe showed the bounded Krylov residuals remain large through degree 12.

This file records the smallest exact, kernel-checked obstruction from that probe: in the sponsor
cell `(n,p,m) = (8,1009,126)`, the centered rank-6 quotient profile is not even in the degree-two
Krylov span of the centered base class.  The four displayed rows of the augmented matrix

```text
[e₀ᶜ, N e₀ᶜ, N² e₀ᶜ, R₆ᶜ]
```

have determinant `-285768 ≠ 0`.  Hence the target column is linearly independent from the
three degree-`≤ 2` incidence columns.  This is not a proof against every fixed degree, but it is an
exact countermodel to the first nontrivial recurrence shape and a Lean-auditable certificate for the
G245 no-go: self-adjointness plus the first few incidence moments do not determine the signed
rank profile.

## Scope

The computation of record is `scripts/probes/g246_krylov_degree_two_countermodel.py`, which builds
`G`, `N`, and the rank profiles over `𝔽_1009` exactly.  Lean certifies the recorded integer minor;
it does not reconstruct the finite-field enumeration internally.  The result is a structural no-go,
not a new estimate.  It does not consume the prize target and does not weaken the surviving
full-character signed covariance at ranks `5` and `6`; it only closes the degree-two incidence
recurrence shortcut.  CORE remains OPEN / ON-BGK.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.G246

open Matrix

/-- Exact four-row minor of the augmented Krylov matrix
`[e₀ᶜ, N e₀ᶜ, N² e₀ᶜ, R₆ᶜ]` for the sponsor cell `(n,p,m)=(8,1009,126)`.
Rows are quotient classes `(0,1,2,4)`.  The first three columns are the degree-`≤2` Krylov orbit of
`e₀ᶜ = m e₀ - 1`; the last column is the centered rank-6 profile `R₆ᶜ = m R₆ - (∑ R₆)1`. -/
def degreeTwoMinor : Matrix (Fin 4) (Fin 4) ℤ :=
  ![![125, 118, 944, -3],
    ![-1, -8, -64, -3],
    ![-1, 118, 188, -3],
    ![-1, -7, -56, -3]]

/-- The recorded augmented Krylov minor has nonzero determinant. -/
theorem degreeTwoMinor_det : degreeTwoMinor.det = -285768 := by
  decide

/-- **Degree-two Krylov countermodel.**  The centered rank-6 quotient profile column is not in the
span of `e₀ᶜ`, `N e₀ᶜ`, and `N² e₀ᶜ` for the recorded sponsor cell.  In linear-algebra terms, the
augmented four-column matrix has a nonzero four-row minor. -/
theorem degree_two_krylov_augmented_minor_nonzero : degreeTwoMinor.det ≠ 0 := by
  rw [degreeTwoMinor_det]
  decide

/-- Exact signed covariances for the same cell, recorded to show this is a genuine sponsor-type
BGK datum rather than a degenerate zero case: the two adjacent ranks already have opposite signs. -/
def A5 : ℤ := 20632

def A6 : ℤ := -1792

/-- In the same exact cell the rank-5 covariance is positive. -/
theorem A5_pos : 0 < A5 := by
  decide

/-- In the same exact cell the rank-6 covariance is negative. -/
theorem A6_neg : A6 < 0 := by
  decide

/-- The cell simultaneously witnesses degree-two Krylov failure and a nonzero signed rank-6 gate;
there is no hidden zero-target degeneracy behind the minor. -/
theorem degree_two_failure_with_nonzero_rank6 :
    degreeTwoMinor.det ≠ 0 ∧ A6 < 0 :=
  ⟨degree_two_krylov_augmented_minor_nonzero, A6_neg⟩

end ArkLib.ProximityGap.Frontier.G246
