/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._FS4Depth3PatternDecomposition
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._CharZeroWickEnergy
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._E3StrataCount

/-!
# LANE G56: all-depth folded-pattern decomposition

This file generalizes the FS4 depth-3 folded-polynomial split from sextuples to every even
depth `2*r`.  For `G = {ζ^a : a < 2m}` with `ζ` primitive of order `2m`, every zero-sum
`2*r`-tuple of `G` is represented uniquely by an exponent tuple.  Folding exponents across
`m` turns the zero-sum condition into `aeval ζ P = 0`; the identically-zero folded patterns
are exactly the antipodally balanced tuples counted by `negSymCount`, and the remaining
vanishing patterns are the wraparound excess.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.style.openClassical false

open Finset Polynomial

namespace ArkLib.ProximityGap.Frontier.G56AllDepthPatternDecomposition

open ArkLib.ProximityGap.Frontier.FS4Depth3PatternDecomposition (monomF aeval_monomF)
open ArkLib.ProximityGap.Frontier.E3StrataCount (negSymCount)
open ArkLib.ProximityGap.NegationClosedWalk (zeroSumCount)
open ArkLib.ProximityGap.SubgroupGaussSumMoment (rEnergy)
open ProximityGap.Frontier.CharZeroWickEnergy (rEnergy_eq_zeroSumCount)

open scoped Classical

variable {F : Type*} [Field F]

/-- The exponent domain `[0,2m)^{ell}`. -/
noncomputable def expTupleSet (m ell : ℕ) : Finset (Fin ell → Fin (2 * m)) :=
  Fintype.piFinset (fun _ : Fin ell => (univ : Finset (Fin (2 * m))))

/-- The all-plus folded pattern attached to an exponent tuple. -/
noncomputable def foldedPattern (m ell : ℕ) (t : Fin ell → Fin (2 * m)) : ℤ[X] :=
  ∑ i : Fin ell, monomF m (t i).val

/-- The subgroup generated by a primitive `2m`-th root, represented by exponents. -/
noncomputable abbrev Gset (ζ : F) (m : ℕ) : Finset F := (range (2 * m)).image (ζ ^ ·)

/-- The char-`p` wraparound excess at depth `r`: nonzero folded patterns that vanish at `ζ`. -/
noncomputable def wraparoundExcessR (ζ : F) (m r : ℕ) : ℕ :=
  ((expTupleSet m (2 * r)).filter
    (fun t => foldedPattern m (2 * r) t ≠ 0 ∧
      aeval ζ (foldedPattern m (2 * r) t) = 0)).card

section Setup

variable {ζ : F} {m : ℕ}

theorem zeta_ne_zero (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m)) : ζ ≠ 0 := by
  intro h
  have := hprim.pow_eq_one
  rw [h, zero_pow (by omega : 2 * m ≠ 0)] at this
  exact zero_ne_one this

/-- `ζ^m = -1` for a primitive `2m`-th root. -/
theorem zeta_pow_m (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m)) : ζ ^ m = -1 := by
  have hsq : ζ ^ m * ζ ^ m = 1 := by
    rw [← pow_add, show m + m = 2 * m by ring]
    exact hprim.pow_eq_one
  rcases mul_self_eq_one_iff.mp hsq with h | h
  · exact absurd h (hprim.pow_ne_one_of_pos_of_lt hm.ne' (by omega))
  · exact h

theorem pow_eq_pow_iff (hprim : IsPrimitiveRoot ζ (2 * m)) {a b : ℕ}
    (ha : a < 2 * m) (hb : b < 2 * m) : ζ ^ a = ζ ^ b ↔ a = b :=
  ⟨fun h => hprim.pow_inj ha hb h, fun h => by rw [h]⟩

theorem neg_pow_eq (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m)) {a : ℕ} :
    -ζ ^ a = ζ ^ (a + m) := by
  rw [pow_add, zeta_pow_m hm hprim]
  ring

theorem Gset_neg_closed (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m)) :
    ∀ z ∈ Gset ζ m, -z ∈ Gset ζ m := by
  intro z hz
  obtain ⟨a, ha, rfl⟩ := mem_image.mp hz
  rw [mem_range] at ha
  by_cases h : a < m
  · refine mem_image.mpr ⟨a + m, ?_, ?_⟩
    · rw [mem_range]; omega
    · rw [← neg_pow_eq hm hprim]
  · refine mem_image.mpr ⟨a - m, ?_, ?_⟩
    · rw [mem_range]; omega
    · have : -ζ ^ (a - m) = ζ ^ (a - m + m) := neg_pow_eq hm hprim
      have hh : a - m + m = a := by omega
      rw [hh] at this
      rw [← this, neg_neg]

theorem Gset_card (_hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m)) :
    (Gset ζ m).card = 2 * m := by
  rw [card_image_of_injOn, card_range]
  intro x hx y hy hxy
  exact hprim.pow_inj (mem_range.mp hx) (mem_range.mp hy) hxy

end Setup

section FoldedPatterns

variable {ζ : F} {m ell : ℕ}

/-- Folded-pattern evaluation is the corresponding power sum. -/
theorem aeval_foldedPattern (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m))
    (t : Fin ell → Fin (2 * m)) :
    aeval ζ (foldedPattern m ell t) = ∑ i : Fin ell, ζ ^ (t i).val := by
  rw [foldedPattern, map_sum]
  refine sum_congr rfl (fun i _ => ?_)
  exact aeval_monomF (F := F) (ζ := ζ) (m := m) (zeta_pow_m hm hprim) (by
    exact (t i).isLt)

/-- The coefficient of a folded pattern is the lower-half count minus the upper-half count. -/
theorem coeff_foldedPattern_eq_count (hm : 0 < m) (t : Fin ell → Fin (2 * m)) {a : ℕ}
    (ha : a < m) :
    (foldedPattern m ell t).coeff a
      = ((univ.filter (fun i : Fin ell => (t i).val = a)).card : ℤ)
        - ((univ.filter (fun i : Fin ell => (t i).val = a + m)).card : ℤ) := by
  have hsum :
      (foldedPattern m ell t).coeff a = ∑ x : Fin ell, (monomF m (t x).val).coeff a := by
    simp [foldedPattern]
  rw [hsum]
  calc ∑ x, (monomF m (t x).val).coeff a
      = ∑ i : Fin ell,
          (((if (t i).val = a then 1 else 0) : ℤ)
            - ((if (t i).val = a + m then 1 else 0) : ℤ)) := by
        refine sum_congr rfl (fun i _ => ?_)
        unfold monomF
        by_cases h : (t i).val < m
        · rw [if_pos h, coeff_X_pow]
          by_cases hi : (t i).val = a
          · rw [if_pos hi, if_pos hi.symm, if_neg (by omega : ¬ (t i).val = a + m)]
            ring
          · rw [if_neg hi, if_neg (fun hia => hi hia.symm), if_neg (by omega)]
            ring
        · rw [if_neg h, coeff_neg, coeff_X_pow]
          by_cases hi : (t i).val = a + m
          · rw [if_pos (by omega : a = (t i).val - m), if_neg (by omega), if_pos hi]
            ring
          · rw [if_neg (by omega : ¬ a = (t i).val - m), if_neg (by omega), if_neg hi]
            ring
    _ = (∑ i : Fin ell, ((if (t i).val = a then 1 else 0) : ℤ))
        - (∑ i : Fin ell, ((if (t i).val = a + m then 1 else 0) : ℤ)) := by
        rw [sum_sub_distrib]
    _ = ((univ.filter (fun i : Fin ell => (t i).val = a)).card : ℤ)
        - ((univ.filter (fun i : Fin ell => (t i).val = a + m)).card : ℤ) := by
        rw [card_filter, card_filter]
        push_cast
        rfl

theorem coeff_foldedPattern_eq_balance (hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m))
    (t : Fin ell → Fin (2 * m)) {a : ℕ} (ha : a < m) :
    (foldedPattern m ell t).coeff a
      = ((univ.filter (fun i : Fin ell => ζ ^ (t i).val = ζ ^ a)).card : ℤ)
        - ((univ.filter (fun i : Fin ell => ζ ^ (t i).val = -ζ ^ a)).card : ℤ) := by
  rw [coeff_foldedPattern_eq_count hm t ha]
  have hpos : a + m < 2 * m := by omega
  have h₁ : ∀ i : Fin ell, (ζ ^ (t i).val = ζ ^ a) ↔ (t i).val = a := by
    intro i
    exact pow_eq_pow_iff hprim (t i).isLt (by omega)
  have h₂ : ∀ i : Fin ell, (ζ ^ (t i).val = -ζ ^ a) ↔ (t i).val = a + m := by
    intro i
    rw [neg_pow_eq hm hprim]
    exact pow_eq_pow_iff hprim (t i).isLt hpos
  simp only [h₁, h₂]

/-- A folded pattern is zero exactly when the represented power tuple is antipodally balanced. -/
theorem foldedPattern_eq_zero_iff_balanced (hm : 0 < m)
    (hprim : IsPrimitiveRoot ζ (2 * m)) (t : Fin ell → Fin (2 * m)) :
    foldedPattern m ell t = 0
      ↔ ∀ z : F, (univ.filter (fun i : Fin ell => ζ ^ (t i).val = z)).card
          = (univ.filter (fun i : Fin ell => ζ ^ (t i).val = -z)).card := by
  constructor
  · intro hzero z
    by_cases hz : ∃ a < m, z = ζ ^ a ∨ z = -ζ ^ a
    · obtain ⟨a, ha, hcase⟩ := hz
      have hcoeff := coeff_foldedPattern_eq_balance (ζ := ζ) hm hprim t ha
      rw [hzero, coeff_zero] at hcoeff
      rcases hcase with rfl | rfl
      · omega
      · rw [neg_neg]
        omega
    · push Not at hz
      have hleft : (univ.filter (fun i : Fin ell => ζ ^ (t i).val = z)).card = 0 := by
        rw [card_eq_zero, filter_eq_empty_iff]
        intro i _ hi
        by_cases hlt : (t i).val < m
        · exact (hz (t i).val hlt).1 hi.symm
        · have hrepr : z = -ζ ^ ((t i).val - m) := by
            have hk : ζ ^ (t i).val = -ζ ^ ((t i).val - m) := by
              symm
              rw [neg_pow_eq hm hprim, show (t i).val - m + m = (t i).val by omega]
            exact hi.symm.trans hk
          exact (hz ((t i).val - m) (by omega)).2 hrepr
      have hright : (univ.filter (fun i : Fin ell => ζ ^ (t i).val = -z)).card = 0 := by
        rw [card_eq_zero, filter_eq_empty_iff]
        intro i _ hi
        have hzval : z = -ζ ^ (t i).val := by linear_combination hi
        by_cases hlt : (t i).val < m
        · exact (hz (t i).val hlt).2 hzval
        · have hrepr : z = ζ ^ ((t i).val - m) := by
            have hk : ζ ^ (t i).val = -ζ ^ ((t i).val - m) := by
              symm
              rw [neg_pow_eq hm hprim, show (t i).val - m + m = (t i).val by omega]
            rw [hk, neg_neg] at hzval
            exact hzval
          exact (hz ((t i).val - m) (by omega)).1 hrepr
      rw [hleft, hright]
  · intro hbal
    ext a
    rw [coeff_zero]
    by_cases ha : a < m
    · have hcoeff := coeff_foldedPattern_eq_balance (ζ := ζ) hm hprim t ha
      rw [hbal (ζ ^ a)] at hcoeff
      omega
    · have hcoeff : (foldedPattern m ell t).coeff a = 0 := by
        have hsum :
            (foldedPattern m ell t).coeff a =
              ∑ i : Fin ell, (monomF m (t i).val).coeff a := by
          simp [foldedPattern]
        rw [hsum]
        refine sum_eq_zero (fun i _ => ?_)
        unfold monomF
        by_cases h : (t i).val < m
        · rw [if_pos h, coeff_X_pow]
          exact if_neg (by omega : ¬ a = (t i).val)
        · rw [if_neg h, coeff_neg, coeff_X_pow]
          exact neg_eq_zero.mpr (if_neg (by omega : ¬ a = (t i).val - m))
      exact hcoeff

end FoldedPatterns

section Bijections

variable {ζ : F} {m r : ℕ}

/-- Exponent tuples are the same data as tuples in `Gset ζ m`. -/
theorem expTupleSet_card_bij_piGset (_hm : 0 < m) (hprim : IsPrimitiveRoot ζ (2 * m))
    (P : (Fin (2 * r) → F) → Prop) [DecidablePred P] :
    ((expTupleSet m (2 * r)).filter (fun t => P (fun i => ζ ^ (t i).val))).card
      = ((Fintype.piFinset (fun _ : Fin (2 * r) => Gset ζ m)).filter P).card := by
  refine card_bij (fun t _ i => ζ ^ (t i).val) ?_ ?_ ?_
  · intro t ht
    rw [mem_filter] at ht
    rw [mem_filter]
    constructor
    · rw [Fintype.mem_piFinset]
      intro i
      exact mem_image.mpr ⟨(t i).val, mem_range.mpr (t i).isLt, rfl⟩
    · exact ht.2
  · intro t ht u hu heq
    funext i
    apply Fin.ext
    exact hprim.pow_inj (t i).isLt (u i).isLt (congrFun heq i)
  · intro c hc
    rw [mem_filter] at hc
    have hmem := hc.1
    rw [Fintype.mem_piFinset] at hmem
    choose a ha hpow using fun i => mem_image.mp (hmem i)
    let t : Fin (2 * r) → Fin (2 * m) := fun i => ⟨a i, mem_range.mp (ha i)⟩
    refine ⟨t, ?_, ?_⟩
    · rw [mem_filter]
      constructor
      · unfold expTupleSet
        rw [Fintype.mem_piFinset]
        intro i
        simp
      · simpa [t, hpow] using hc.2
    · funext i
      simp [t, hpow i]

variable [Fintype F]

theorem foldedPattern_zero_count_eq_negSymCount (hm : 0 < m)
    (hprim : IsPrimitiveRoot ζ (2 * m)) :
    ((expTupleSet m (2 * r)).filter (fun t => foldedPattern m (2 * r) t = 0)).card
      = negSymCount (Gset ζ m) (2 * r) := by
  unfold negSymCount
  rw [← expTupleSet_card_bij_piGset (ζ := ζ) hm hprim
      (fun c : Fin (2 * r) → F =>
        ∀ z : F, (univ.filter (fun i => c i = z)).card
          = (univ.filter (fun i => c i = -z)).card)]
  congr 1
  ext t
  simp only [mem_filter]
  constructor
  · intro ht
    exact ⟨ht.1, (foldedPattern_eq_zero_iff_balanced (ζ := ζ) hm hprim t).mp ht.2⟩
  · intro ht
    exact ⟨ht.1, (foldedPattern_eq_zero_iff_balanced (ζ := ζ) hm hprim t).mpr ht.2⟩

theorem zeroSumCount_Gset_eq_negSymCount_add_wraparound (hm : 0 < m)
    (hprim : IsPrimitiveRoot ζ (2 * m)) :
    zeroSumCount (Gset ζ m) (2 * r)
      = negSymCount (Gset ζ m) (2 * r) + wraparoundExcessR ζ m r := by
  rw [zeroSumCount]
  rw [← expTupleSet_card_bij_piGset (ζ := ζ) hm hprim
      (fun c : Fin (2 * r) → F => ∑ i, c i = 0)]
  have hsplit :
      ((expTupleSet m (2 * r)).filter (fun t => ∑ i, ζ ^ (t i).val = 0)).card
        =
      ((expTupleSet m (2 * r)).filter (fun t => foldedPattern m (2 * r) t = 0)).card
        + wraparoundExcessR ζ m r := by
    rw [wraparoundExcessR]
    have hpoint : ∀ t : Fin (2 * r) → Fin (2 * m),
        (∑ i, ζ ^ (t i).val = 0)
          ↔ foldedPattern m (2 * r) t = 0
            ∨ foldedPattern m (2 * r) t ≠ 0 ∧ aeval ζ (foldedPattern m (2 * r) t) = 0 := by
      intro t
      rw [← aeval_foldedPattern (ζ := ζ) hm hprim t]
      constructor
      · intro h
        by_cases hP : foldedPattern m (2 * r) t = 0
        · exact Or.inl hP
        · exact Or.inr ⟨hP, h⟩
      · intro h
        rcases h with hP | hP
        · rw [hP]; simp
        · exact hP.2
    rw [← card_union_of_disjoint]
    · congr 1
      ext t
      by_cases ht : t ∈ expTupleSet m (2 * r)
      · simp [ht, hpoint t]
      · simp [ht]
    · rw [disjoint_left]
      intro t ht0 htw
      rw [mem_filter] at ht0 htw
      exact htw.2.1 ht0.2
  rw [hsplit, foldedPattern_zero_count_eq_negSymCount (ζ := ζ) hm hprim]

/-- **All-depth exact decomposition.**  The `r`-fold additive energy of `Gset ζ m` is the
antipodally balanced count at arity `2*r`, plus the nonzero folded-pattern wraparound excess. -/
theorem rEnergy_Gset_eq_negSymCount_add_wraparoundExcessR (hm : 0 < m)
    (hprim : IsPrimitiveRoot ζ (2 * m)) :
    rEnergy (Gset ζ m) r
      = negSymCount (Gset ζ m) (2 * r) + wraparoundExcessR ζ m r := by
  rw [rEnergy_eq_zeroSumCount (Gset ζ m) r (Gset_neg_closed (ζ := ζ) hm hprim)]
  exact zeroSumCount_Gset_eq_negSymCount_add_wraparound (ζ := ζ) hm hprim

end Bijections

#print axioms coeff_foldedPattern_eq_count
#print axioms foldedPattern_eq_zero_iff_balanced
#print axioms foldedPattern_zero_count_eq_negSymCount
#print axioms zeroSumCount_Gset_eq_negSymCount_add_wraparound
#print axioms rEnergy_Gset_eq_negSymCount_add_wraparoundExcessR

end ArkLib.ProximityGap.Frontier.G56AllDepthPatternDecomposition
