/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib.RingTheory.Ideal.Quotient.Operations
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Tactic.Positivity
import Mathlib.Tactic.Ring

/-!
# G82: the transversality seam quantified — CRT amplification fires at HALF the height
allowance (the sole surviving CORE seam is coverage-blocked, NOT height-blocked)

After G68–G73/G77 the sole surviving CORE surface is the r369 piece-(b) transversality seam:
force a census of wraparound relations to vanish at MANY DISTINCT prime-ideal embeddings and
amplify through a determinant.  OC-PIECEB capped the naive same-ideal stacking; this file
supplies the missing QUANTITATIVE law for the multi-embedding side, in three axiom-clean
layers, and computes the exact threshold at the prize cell.

**The amplification engine (proven here, any commutative ring).**
* `natCard_quotient_iInf_eq_prod` — CRT cardinality: for pairwise-distinct maximal ideals
  `𝔭_1, …, 𝔭_s`, `#(R ⧸ ⋂ 𝔭_i) = Π #(R ⧸ 𝔭_i)`.
* `crt_amplification` (HEADLINE) — if an ideal `L` lies in the COMMON intersection of `s`
  distinct maximal ideals of index `p`, then any bound `#(R ⧸ L) ≤ H` forces `p^s ≤ H`.
* `coverage_log_bound` — hence `s·log p ≤ log H`: common coverage above
  `s* = log H / log p` is CONTRADICTORY — no such census exists.

**Instantiation at the prize cell (documented; heights from OC-PIECEB).**  Take
`R = ℤ[ζ_n]` (`φ = n/2`), `𝔭_a` the degree-1 primes above `p` covered in common by the
depth-3 (`s6h1`) census, and `L` the ideal generated by a full-rank census family.  The
lattice index of the ±1/support-6 row span obeys Hadamard `[O : span] ≤ (√6)^{n/2} = 6^{n/4}`,
and `L ⊇ span ⟹ #(R ⧸ L) ≤ 6^{n/4}`.  So the census CANNOT share
`s > (n/4)·log 6 / log p ≈ 0.112·n/ln n` (at `p = n⁴`) common embeddings — while the
OC-PIECEB height ceiling allows a SINGLE relation to cover up to
`(n/2)·log 6 / log p ≈ 0.224·n/ln n` embeddings:

* `crtThreshold_eq_half_heightCap` — **the contradiction threshold is exactly HALF the
  per-relation height allowance.**  The seam is therefore NOT height-blocked: relations rich
  enough to trigger the contradiction are height-legal.  What is missing is only a FORCING
  mechanism for common coverage (the census concentrates at one embedding, coverage ≈ 1 —
  factor `n/log n` below threshold).  Piece (b) reduces to: force
  `Ω(n/log n)` COMMON vanishing embeddings for a full-rank height-1 family, or prove no
  census can have them (the anti-coincidence direction) — the first NUMERICALLY CLOSE
  boundary the campaign has found on the surviving seam.

HONEST SCOPE.  The engine and threshold arithmetic are proven; the prize-cell instantiation
(Hadamard for the census span, degree-1 splitting of `p` in `ℤ[ζ_n]`) is documented, not
formalized.  No bound on `M`, no closure.  CORE remains OPEN / ON-BGK.

Issue #466.  Target axiom set: `[propext, Classical.choice, Quot.sound]`.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

namespace ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold

open Finset Function

variable {R : Type*} [CommRing R]

/-- **CRT cardinality.**  Pairwise-distinct maximal ideals have jointly-CRT quotients:
`#(R ⧸ ⋂ᵢ 𝔭ᵢ) = Πᵢ #(R ⧸ 𝔭ᵢ)`. -/
theorem natCard_quotient_iInf_eq_prod
    {ι : Type*} [Fintype ι] (f : ι → Ideal R)
    (hmax : ∀ i, (f i).IsMaximal) (hne : Pairwise fun i j => f i ≠ f j) :
    Nat.card (R ⧸ ⨅ i, f i) = ∏ i, Nat.card (R ⧸ f i) := by
  classical
  have hco : Pairwise (IsCoprime on f) := by
    intro i j hij
    haveI := hmax i
    haveI := hmax j
    exact Ideal.isCoprime_of_isMaximal (hne hij)
  have e := Ideal.quotientInfRingEquivPiQuotient f hco
  rw [Nat.card_congr e.toEquiv, Nat.card_pi]

/-- The quotient-factor surjection: `L ≤ J` makes `R ⧸ J` a quotient of `R ⧸ L`, so its
cardinality can only drop. -/
theorem natCard_quotient_le_of_le {L J : Ideal R} (h : L ≤ J) [Finite (R ⧸ L)] :
    Nat.card (R ⧸ J) ≤ Nat.card (R ⧸ L) := by
  classical
  have hsurj : Function.Surjective (Ideal.Quotient.factor h) := by
    intro y
    obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective y
    exact ⟨Ideal.Quotient.mk L x, rfl⟩
  exact Nat.card_le_card_of_surjective _ hsurj

/-- **HEADLINE: CRT amplification.**  An ideal contained in the common intersection of `s`
distinct maximal ideals, each of index `p`, has quotient cardinality at least `p^s`; any
height certificate `#(R ⧸ L) ≤ H` therefore forces `p^s ≤ H`. -/
theorem crt_amplification
    {s : ℕ} (f : Fin s → Ideal R) (p H : ℕ)
    (hmax : ∀ i, (f i).IsMaximal) (hne : Pairwise fun i j => f i ≠ f j)
    (hcard : ∀ i, Nat.card (R ⧸ f i) = p)
    (L : Ideal R) (hL : L ≤ ⨅ i, f i) [Finite (R ⧸ L)]
    (hH : Nat.card (R ⧸ L) ≤ H) :
    p ^ s ≤ H := by
  classical
  have hinf : Nat.card (R ⧸ ⨅ i, f i) = p ^ s := by
    rw [natCard_quotient_iInf_eq_prod f hmax hne]
    simp [hcard]
  calc p ^ s = Nat.card (R ⧸ ⨅ i, f i) := hinf.symm
    _ ≤ Nat.card (R ⧸ L) := natCard_quotient_le_of_le hL
    _ ≤ H := hH

/-- **Mixed-index / CROSS-PRIME amplification.**  Distinct maximal ideals of possibly
DIFFERENT indices `P i` (e.g. degree-1 primes above different rational primes): a common
relation web forces `Π P i ≤ H`.  This is the ideal-theoretic general form of OC-TAIL's
cross-prime finiteness: one bounded-height relation family cannot be simultaneously
exceptional at rational primes whose product exceeds its height certificate — the
stacked-violator prime set is finite in the whole tail, with the exact budget `Π p_i ≤ H`. -/
theorem crt_amplification_mixed
    {ι : Type*} [Fintype ι] (f : ι → Ideal R) (P : ι → ℕ) (H : ℕ)
    (hmax : ∀ i, (f i).IsMaximal) (hne : Pairwise fun i j => f i ≠ f j)
    (hcard : ∀ i, Nat.card (R ⧸ f i) = P i)
    (L : Ideal R) (hL : L ≤ ⨅ i, f i) [Finite (R ⧸ L)]
    (hH : Nat.card (R ⧸ L) ≤ H) :
    ∏ i, P i ≤ H := by
  classical
  have hinf : Nat.card (R ⧸ ⨅ i, f i) = ∏ i, P i := by
    rw [natCard_quotient_iInf_eq_prod f hmax hne]
    exact Finset.prod_congr rfl fun i _ => hcard i
  calc ∏ i, P i = Nat.card (R ⧸ ⨅ i, f i) := hinf.symm
    _ ≤ Nat.card (R ⧸ L) := natCard_quotient_le_of_le hL
    _ ≤ H := hH

/-- **The logarithmic coverage bound**: `p^s ≤ H` pins common coverage at
`s ≤ log H / log p`; coverage above the threshold is contradictory. -/
theorem coverage_log_bound (p H s : ℕ) (hp : 2 ≤ p) (hH : 1 ≤ H)
    (hpow : p ^ s ≤ H) :
    (s : ℝ) * Real.log p ≤ Real.log H := by
  have hplog : (0 : ℝ) < Real.log p := by
    apply Real.log_pos
    exact_mod_cast hp
  have hcast : ((p : ℝ)) ^ s ≤ (H : ℝ) := by exact_mod_cast hpow
  have hppos : (0 : ℝ) < (p : ℝ) ^ s := by positivity
  have := Real.log_le_log hppos hcast
  rwa [Real.log_pow] at this

/-- The prize-cell contradiction threshold: common coverage forcing `p^s > 6^{n/4}`. -/
noncomputable def crtThreshold (n p : ℝ) : ℝ := (n / 4) * Real.log 6 / Real.log p

/-- The OC-PIECEB per-relation height allowance: one support-6 height-1 relation may cover
up to `(n/2)·log 6 / log p` embeddings (`v_p(Norm) ≤ φ·log 6/log p`, `φ = n/2`). -/
noncomputable def heightCoverageCap (n p : ℝ) : ℝ := (n / 2) * Real.log 6 / Real.log p

/-- **The seam is coverage-blocked, not height-blocked**: the CRT contradiction threshold
sits at exactly HALF the single-relation height allowance. -/
theorem crtThreshold_eq_half_heightCap (n p : ℝ) :
    crtThreshold n p = heightCoverageCap n p / 2 := by
  unfold crtThreshold heightCoverageCap
  ring

end ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold

/-! ## Axiom audit -/
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.natCard_quotient_iInf_eq_prod
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.natCard_quotient_le_of_le
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.crt_amplification
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.crt_amplification_mixed
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.coverage_log_bound
#print axioms
  ArkLib.ProximityGap.Frontier.G82TransversalityCRTThreshold.crtThreshold_eq_half_heightCap
