/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._HalfRadiusEvenThirdBlockObstruction
import Mathlib.Combinatorics.SimpleGraph.DegreeSum
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas

/-!
# Rate-quarter `k = 4`: the syndrome-chord graph has at most seven edges

After puncturing an eight-coordinate source core, every regular outsider has
an error supported on two of the eight remaining coordinates.  In the
four-dimensional quotient by the punctured `[8,4]` Reed--Solomon code, its
syndrome lies on the chord spanned by the corresponding two parity columns.
All outsider syndromes also lie in the projective line generated by the two
received rows.

This file isolates the linear-algebraic counting mechanism behind that
picture.  Let `P` be a subspace of dimension at most two in a four-wise
independent column frame.  If `P` contains no column, then at most two chords
through any fixed column can meet `P`: three such chords would put four
independent columns in `P + span(column)`, a space of dimension at most three.
The handshaking lemma first bounds the total number of incident chords by the
number of columns.  Equality would make every column have degree two.  Chord
incidence is transitive up to equality, so every closed neighborhood would
then be a disjoint triangle.  Eight columns cannot be partitioned into such
three-element blocks, improving the concrete ceiling from eight to seven.

For the eight-coordinate complement this gives the sharp ceiling of seven
regular weight-two syndrome supports.  The excluded case where `P` contains
a column is a genuine sparse-direction/long-outsider branch and must be
handled separately.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false

open Finset Module Submodule
open ArkLib.ProximityGap.Frontier.HalfRadiusEvenThirdBlockObstruction

namespace ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterKFourSyndromeChordBound

attribute [local instance] Classical.propDecidable

variable {F V I : Type*} [Field F] [AddCommGroup V] [Module F V]
variable [FiniteDimensional F V] [Fintype I] [DecidableEq I]

/-- A genuine projective chord of the indexed column frame meets `P`.
The displayed nonzero linear combination is an affine representative of the
intersection point. -/
def ChordMeets
    (P : Submodule F V) (v : I -> V) (i j : I) : Prop :=
  i ≠ j ∧
    ∃ a b : F,
      a • v i + b • v j ≠ 0 ∧
      a • v i + b • v j ∈ P

theorem chordMeets_symm
    (P : Submodule F V) (v : I -> V) {i j : I}
    (h : ChordMeets P v i j) : ChordMeets P v j i := by
  obtain ⟨hij, a, b, hne, hmem⟩ := h
  refine ⟨hij.symm, b, a, ?_, ?_⟩
  · simpa only [add_comm] using hne
  · simpa only [add_comm] using hmem

/-- The simple graph whose edges are the column chords meeting `P`. -/
def chordGraph (P : Submodule F V) (v : I -> V) : SimpleGraph I where
  Adj i j := ChordMeets P v i j
  symm _ _ := chordMeets_symm P v
  loopless := ⟨fun _i h => h.1 rfl⟩

/-- If the first endpoint is not in `P`, incidence of the chord `(i,j)`
forces the second endpoint into `P + span(v_i)`. -/
theorem right_mem_sup_span_of_chordMeets
    (P : Submodule F V) (v : I -> V) {i j : I}
    (hi : v i ∉ P) (hij : ChordMeets P v i j) :
    v j ∈ P ⊔ span F ({v i} : Set V) := by
  obtain ⟨_hneij, a, b, hcombNe, hcombMem⟩ := hij
  have hb : b ≠ 0 := by
    intro hb0
    subst b
    simp only [zero_smul, add_zero] at hcombNe hcombMem
    have ha : a ≠ 0 := by
      intro ha0
      subst a
      exact hcombNe (zero_smul F (v i))
    apply hi
    have hinv : a⁻¹ • (a • v i) ∈ P := P.smul_mem a⁻¹ hcombMem
    simpa only [inv_smul_smul₀ ha] using hinv
  let W : Submodule F V := P ⊔ span F ({v i} : Set V)
  have hcombW : a • v i + b • v j ∈ W :=
    (show P ≤ W from le_sup_left) hcombMem
  have hviW : v i ∈ W :=
    (show span F ({v i} : Set V) ≤ W from le_sup_right)
      (subset_span (Set.mem_singleton (v i)))
  have hdiffW : (a • v i + b • v j) - a • v i ∈ W :=
    W.sub_mem hcombW (W.smul_mem a hviW)
  have hbvjW : b • v j ∈ W := by
    simpa only [add_sub_cancel_left] using hdiffW
  have hinvW : b⁻¹ • (b • v j) ∈ W := W.smul_mem b⁻¹ hbvjW
  simpa only [inv_smul_smul₀ hb] using hinvW

/-- If `P` avoids one endpoint, its intersection with the corresponding
two-column chord span has dimension at most one. -/
theorem finrank_inf_pairSpan_le_one
    (P : Submodule F V) (v : I -> V) (i j : I)
    (hi : v i ∉ P) :
    finrank F ↥(P ⊓ span F ({v i, v j} : Set V)) ≤ 1 := by
  classical
  let S : Submodule F V := span F ({v i, v j} : Set V)
  let Q : Submodule F V := P ⊓ S
  change finrank F Q ≤ 1
  by_contra hdim
  have hQtwo : 2 ≤ finrank F Q := by omega
  have hSdim : finrank F S ≤ 2 := by
    dsimp only [S]
    have hspan :
        finrank F (span F ({v i, v j} : Set V)) ≤
          ({v i, v j} : Finset V).card := by
      simpa using finrank_span_finset_le_card (R := F)
        ({v i, v j} : Finset V)
    rcases Finset.card_pair_eq_one_or_two (a := v i) (b := v j) with hcard | hcard
    · omega
    · omega
  have hQleS : Q ≤ S := inf_le_right
  have hQdimLe : finrank F Q ≤ finrank F S :=
    Submodule.finrank_mono hQleS
  have hdimEq : finrank F Q = finrank F S := by omega
  have hQS : Q = S :=
    Submodule.eq_of_le_of_finrank_eq hQleS hdimEq
  apply hi
  have hviS : v i ∈ S := by
    exact subset_span (by simp)
  have hviQ : v i ∈ Q := by
    rw [hQS]
    exact hviS
  exact hviQ.1

/-- The projective intersection point of a chord with a column-avoiding
syndrome plane is unique. -/
theorem proportional_of_mem_plane_mem_pairSpan
    (P : Submodule F V) (v : I -> V) (i j : I)
    (hi : v i ∉ P) {x y : V}
    (hxNe : x ≠ 0) (hxP : x ∈ P)
    (hxSpan : x ∈ span F ({v i, v j} : Set V))
    (hyP : y ∈ P)
    (hySpan : y ∈ span F ({v i, v j} : Set V)) :
    ∃ c : F, c • x = y := by
  let Q : Submodule F V :=
    P ⊓ span F ({v i, v j} : Set V)
  let xQ : Q := ⟨x, hxP, hxSpan⟩
  let yQ : Q := ⟨y, hyP, hySpan⟩
  have hxQNe : xQ ≠ 0 := by
    intro hzero
    apply hxNe
    have hcoe := congrArg Subtype.val hzero
    simpa only [xQ, Submodule.coe_zero] using hcoe
  have hQpos : 0 < finrank F Q :=
    Module.finrank_pos_iff_exists_ne_zero.mpr ⟨xQ, hxQNe⟩
  have hQle : finrank F Q ≤ 1 := by
    simpa only [Q] using finrank_inf_pairSpan_le_one P v i j hi
  have hQone : finrank F Q = 1 := by omega
  obtain ⟨c, hc⟩ := exists_smul_eq_of_finrank_eq_one hQone hxQNe yQ
  refine ⟨c, ?_⟩
  exact congrArg Subtype.val hc

/-- Distinct columns in a four-wise independent frame are not scalar
multiples. -/
theorem column_ne_smul_of_independentUpTo_four
    (v : I -> V) (hMDS4 : IndependentUpTo (F := F) v 4)
    {i j : I} (hij : i ≠ j) (a : F) :
    a • v i ≠ v j := by
  have hcard : ({i, j} : Finset I).card ≤ 4 := by
    rcases Finset.card_pair_eq_one_or_two (a := i) (b := j) with h | h <;> omega
  have hLI' := hMDS4 ({i, j} : Finset I) hcard
  let ii : ({i, j} : Finset I) := ⟨i, by simp⟩
  let jj : ({i, j} : Finset I) := ⟨j, by simp⟩
  let e : Fin 2 -> ({i, j} : Finset I) := ![ii, jj]
  have he : Function.Injective e := by
    intro x y
    fin_cases x <;> fin_cases y <;> simp [e, ii, jj, hij, hij.symm]
  have hpair := hLI'.comp e he
  have heq :
      ((fun x : ({i, j} : Finset I) => v x.1) ∘ e) = ![v i, v j] := by
    funext x
    fin_cases x <;> rfl
  have hpair' : LinearIndependent F ![v i, v j] := by
    rw [← heq]
    exact hpair
  have hiNe : v i ≠ 0 := hpair'.ne_zero 0
  exact (LinearIndependent.pair_iff' hiNe).mp hpair' a

/-- Conversely, if the second endpoint lies in `P + span(v_i)`, then the
chord meets `P`, provided the two columns are independent and neither endpoint
lies in `P`. -/
theorem chordMeets_of_right_mem_sup_span
    (P : Submodule F V) (v : I -> V)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    {i j : I} (hij : i ≠ j)
    (hmem : v j ∈ P ⊔ span F ({v i} : Set V)) :
    ChordMeets P v i j := by
  obtain ⟨p, hp, s, hs, hps⟩ := (Submodule.mem_sup).mp hmem
  obtain ⟨a, ha⟩ := (Submodule.mem_span_singleton).mp hs
  subst s
  have hpNe : p ≠ 0 := by
    intro hp0
    have hjEq : v j = a • v i := by
      rw [← hps, hp0, zero_add]
    exact column_ne_smul_of_independentUpTo_four v hMDS4 hij a hjEq.symm
  have hcombo : (-a) • v i + (1 : F) • v j = p := by
    rw [one_smul, neg_smul]
    rw [← hps]
    abel
  refine ⟨hij, -a, (1 : F), ?_, ?_⟩
  · intro hzero
    apply hpNe
    calc
      p = (-a) • v i + (1 : F) • v j := hcombo.symm
      _ = 0 := hzero
  · rw [← hcombo] at hp
    exact hp

/-- Chord incidence is transitive up to the forbidden diagonal.  Geometrically,
two columns are adjacent exactly when their nonzero images in `V/P` have the
same projective direction. -/
theorem chordGraph_adj_trans_or_eq
    (P : Submodule F V) (v : I -> V)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P)
    {i j k : I}
    (hij : (chordGraph P v).Adj i j)
    (hjk : (chordGraph P v).Adj j k) :
    i = k ∨ (chordGraph P v).Adj i k := by
  by_cases hik : i = k
  · exact Or.inl hik
  · right
    change ChordMeets P v i j at hij
    change ChordMeets P v j k at hjk
    change ChordMeets P v i k
    let W : Submodule F V := P ⊔ span F ({v i} : Set V)
    have hjW : v j ∈ W :=
      right_mem_sup_span_of_chordMeets P v (hnoColumn i) hij
    have hspanJ : span F ({v j} : Set V) ≤ W := by
      rw [Submodule.span_le]
      intro x hx
      simp only [Set.mem_singleton_iff] at hx
      subst x
      exact hjW
    have hsupLe : P ⊔ span F ({v j} : Set V) ≤ W :=
      sup_le le_sup_left hspanJ
    have hkW : v k ∈ W := hsupLe
      (right_mem_sup_span_of_chordMeets P v (hnoColumn j) hjk)
    exact chordMeets_of_right_mem_sup_span P v hMDS4 hik hkW

/-- A nonzero chord intersection spans any syndrome subspace of dimension at
most one. -/
theorem le_pairSpan_of_finrank_le_one_of_chordMeets
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P <= 1)
    {i j : I} (hij : ChordMeets P v i j) :
    P <= span F ({v i, v j} : Set V) := by
  obtain ⟨_hij, a, b, hxNe, hxP⟩ := hij
  let x : V := a • v i + b • v j
  have hxSpan : x ∈ span F ({v i, v j} : Set V) := by
    rw [Submodule.mem_span_pair]
    exact ⟨a, b, rfl⟩
  let xP : P := ⟨x, hxP⟩
  have hxPNe : xP ≠ 0 := by
    intro hzero
    apply hxNe
    have hcoe := congrArg Subtype.val hzero
    simpa only [xP, x, Submodule.coe_zero] using hcoe
  have hPpos : 0 < finrank F P :=
    Module.finrank_pos_iff_exists_ne_zero.mpr ⟨xP, hxPNe⟩
  have hPone : finrank F P = 1 := by omega
  intro y hy
  let yP : P := ⟨y, hy⟩
  obtain ⟨c, hc⟩ := exists_smul_eq_of_finrank_eq_one hPone hxPNe yP
  have hcVal : c • x = y := congrArg Subtype.val hc
  rw [← hcVal]
  exact smul_mem _ c hxSpan

/-- In a four-wise independent, column-avoiding frame, a one-dimensional
syndrome subspace meets at most one indexed chord support. -/
theorem pair_eq_of_chordMeets_of_finrank_le_one
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P <= 1)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : forall i, v i ∉ P)
    {i j k l : I}
    (hij : ChordMeets P v i j)
    (hkl : ChordMeets P v k l) :
    ({i, j} : Finset I) = {k, l} := by
  classical
  let S : Finset I := {i, j}
  let C : Finset I := {k, l}
  have hScard : S.card = 2 := by
    simpa only [S] using Finset.card_pair hij.1
  have hCcard : C.card = 2 := by
    simpa only [C] using Finset.card_pair hkl.1
  by_contra hSC
  have hinterLe : (S ∩ C).card <= 1 := by
    by_contra hnot
    have hinterLower : 2 <= (S ∩ C).card := by omega
    have hinterEqS : S ∩ C = S := by
      apply Finset.eq_of_subset_of_card_le Finset.inter_subset_left
      rw [hScard]
      exact hinterLower
    have hSsubC : S ⊆ C := by
      rw [← hinterEqS]
      exact Finset.inter_subset_right
    have hEq : S = C := by
      apply Finset.eq_of_subset_of_card_le hSsubC
      rw [hScard, hCcard]
    exact hSC hEq
  have hunionCard : (S ∪ C).card <= 4 := by
    exact (Finset.card_union_le S C).trans (by omega)
  have hLI' := hMDS4 (S ∪ C) hunionCard
  have hLI : LinearIndepOn F v (((S ∪ C : Finset I) : Set I)) := by
    simpa only [LinearIndepOn] using hLI'
  have hPS : P <= columnSpan (F := F) v S := by
    intro z hz
    have hz' := le_pairSpan_of_finrank_le_one_of_chordMeets
      P v hP hij hz
    simpa only [S, columnSpan, Finset.coe_insert, Finset.coe_singleton,
      Set.image_pair] using hz'
  have hPC : P <= columnSpan (F := F) v C := by
    intro z hz
    have hz' := le_pairSpan_of_finrank_le_one_of_chordMeets
      P v hP hkl hz
    simpa only [C, columnSpan, Finset.coe_insert, Finset.coe_singleton,
      Set.image_pair] using hz'
  have hcommon : P <= columnSpan (F := F) v (S ∩ C) :=
    sharedSubmodule_le_commonSpan v S C P hLI hPS hPC
  obtain ⟨_hijNe, a, b, hxNe, hxP⟩ := hij
  let x : V := a • v i + b • v j
  have hxCommon : x ∈ columnSpan (F := F) v (S ∩ C) := hcommon hxP
  by_cases hinterEmpty : S ∩ C = ∅
  · apply hxNe
    have hxZero : x = 0 := by
      simpa only [hinterEmpty, columnSpan, Finset.coe_empty, Set.image_empty,
        Submodule.span_empty, Submodule.mem_bot] using hxCommon
    exact hxZero
  · obtain ⟨t, ht⟩ := Finset.nonempty_iff_ne_empty.mpr hinterEmpty
    have hinterEq : S ∩ C = {t} := by
      apply Finset.eq_singleton_iff_unique_mem.mpr
      refine ⟨ht, ?_⟩
      intro y hy
      exact (Finset.card_le_one.mp hinterLe) y hy t ht
    have hxSpanT : x ∈ span F ({v t} : Set V) := by
      simpa only [hinterEq, columnSpan, Finset.coe_singleton,
        Set.image_singleton] using hxCommon
    obtain ⟨c, hc⟩ := (Submodule.mem_span_singleton.mp hxSpanT)
    have hcNe : c ≠ 0 := by
      intro hcZero
      apply hxNe
      change x = 0
      rw [← hc, hcZero, zero_smul]
    apply hnoColumn t
    have hscaled : c⁻¹ • x ∈ P := P.smul_mem c⁻¹ hxP
    rw [← hc, inv_smul_smul₀ hcNe] at hscaled
    exact hscaled

/-- At a column outside `P`, the chord-incidence degree is at most two.

Three neighbors would place the fixed column and three neighboring columns
inside `P + span(v_i)`, whose dimension is at most `2+1=3`, contradicting
four-wise independence. -/
theorem chordGraph_degree_le_two
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P) (i : I) :
    (chordGraph P v).degree i ≤ 2 := by
  classical
  let G := chordGraph P v
  change G.degree i ≤ 2
  by_contra hdegree
  have hthree : 3 ≤ (G.neighborFinset i).card := by
    rw [SimpleGraph.card_neighborFinset_eq_degree]
    omega
  obtain ⟨T, hTsub, hTcard⟩ := Finset.exists_subset_card_eq hthree
  have hiT : i ∉ T := by
    intro hi
    have hiNeighbor : i ∈ G.neighborFinset i := hTsub hi
    have hii : G.Adj i i := by
      simpa only [SimpleGraph.mem_neighborFinset] using hiNeighbor
    exact G.loopless.irrefl i hii
  let J : Finset I := insert i T
  have hJcard : J.card = 4 := by
    dsimp only [J]
    rw [Finset.card_insert_of_notMem hiT, hTcard]
  have hJLI : LinearIndependent F (fun j : J => v j) :=
    hMDS4 J (by omega)
  let W : Submodule F V := P ⊔ span F ({v i} : Set V)
  have hvaluesW : ∀ j : J, v j ∈ W := by
    intro j
    have hjCases : j.1 = i ∨ j.1 ∈ T := by
      simpa only [J, Finset.mem_insert] using j.2
    rcases hjCases with hji | hjT
    · rw [hji]
      exact (show span F ({v i} : Set V) ≤ W from le_sup_right)
        (subset_span (Set.mem_singleton (v i)))
    · have hjNeighbor : j.1 ∈ G.neighborFinset i := hTsub hjT
      have hAdj : G.Adj i j.1 := by
        simpa only [SimpleGraph.mem_neighborFinset] using hjNeighbor
      exact right_mem_sup_span_of_chordMeets P v (hnoColumn i) hAdj
  have hspanLe : span F (Set.range (fun j : J => v j)) ≤ W := by
    rw [Submodule.span_le]
    rintro x ⟨j, rfl⟩
    exact hvaluesW j
  have hLower : 4 ≤ finrank F W := by
    have hmono := Submodule.finrank_mono hspanLe
    rw [finrank_span_eq_card hJLI] at hmono
    simpa only [Fintype.card_coe, hJcard] using hmono
  have hviNe : v i ≠ 0 := by
    intro hzero
    apply hnoColumn i
    rw [hzero]
    exact P.zero_mem
  have hUpper : finrank F W ≤ 3 := by
    calc
      finrank F W ≤ finrank F P + finrank F (span F ({v i} : Set V)) :=
        Submodule.finrank_add_le_finrank_add_finrank P
          (span F ({v i} : Set V))
      _ = finrank F P + 1 := by rw [finrank_span_singleton hviNe]
      _ ≤ 3 := by omega
  omega

/-- **Syndrome-chord edge bound.**  A two-dimensional projective syndrome
line avoiding all columns meets at most one chord per column on average. -/
theorem chordGraph_edgeFinset_card_le
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P) :
    (chordGraph P v).edgeFinset.card ≤ Fintype.card I := by
  classical
  let G := chordGraph P v
  change G.edgeFinset.card ≤ Fintype.card I
  have hdegree : ∀ i, G.degree i ≤ 2 :=
    chordGraph_degree_le_two P v hP hMDS4 hnoColumn
  have hsum : (∑ i : I, G.degree i) ≤ ∑ _i : I, 2 :=
    Finset.sum_le_sum fun i _ => hdegree i
  rw [G.sum_degrees_eq_twice_card_edges] at hsum
  simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul] at hsum
  omega

/-- A transitive-up-to-diagonal graph on eight vertices with maximum degree
two has at most seven edges.  Equality in the handshake bound would force
degree two everywhere, while transitivity makes every closed neighborhood a
three-vertex block; two such blocks leave only two vertices. -/
theorem edgeFinset_card_le_seven_of_card_eq_eight
    {alpha : Type*} [Fintype alpha]
    (G : SimpleGraph alpha)
    (hcard : Fintype.card alpha = 8)
    (hdegree : forall i, G.degree i <= 2)
    (htrans : forall {i j k : alpha}, G.Adj i j -> G.Adj j k ->
      i = k \/ G.Adj i k) :
    G.edgeFinset.card <= 7 := by
  classical
  have hsumLe : (∑ i : alpha, G.degree i) <= ∑ _i : alpha, 2 :=
    Finset.sum_le_sum fun i _ => hdegree i
  rw [G.sum_degrees_eq_twice_card_edges] at hsumLe
  simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul, hcard] at hsumLe
  have hedgeLe : G.edgeFinset.card <= 8 := by omega
  by_contra hedgeNot
  have hedgeEq : G.edgeFinset.card = 8 := by omega
  have hsumEq : (∑ i : alpha, G.degree i) = ∑ _i : alpha, 2 := by
    rw [G.sum_degrees_eq_twice_card_edges]
    simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul, hedgeEq, hcard]
  have hdegreeEq : forall i, G.degree i = 2 := by
    exact fun i =>
      (Finset.sum_eq_sum_iff_of_le fun j _ => hdegree j).mp hsumEq
        i (Finset.mem_univ i)
  let C : alpha -> Finset alpha := fun i => insert i (G.neighborFinset i)
  have hCcard (i : alpha) : (C i).card = 3 := by
    dsimp only [C]
    rw [Finset.card_insert_of_notMem]
    · rw [SimpleGraph.card_neighborFinset_eq_degree, hdegreeEq i]
    · simpa only [SimpleGraph.mem_neighborFinset] using G.loopless.irrefl i
  have hclosed {i x y : alpha} (hx : x ∈ C i) (hxy : G.Adj x y) :
      y ∈ C i := by
    simp only [C, Finset.mem_insert, SimpleGraph.mem_neighborFinset] at hx ⊢
    rcases hx with hxi | hix
    · subst x
      exact Or.inr hxy
    · rcases htrans hix hxy with hiy | hiy
      · exact Or.inl hiy.symm
      · exact Or.inr hiy
  have hCsubset_compl {i j : alpha} (hj : j ∉ C i) :
      C j ⊆ (Finset.univ : Finset alpha) \ C i := by
    intro y hy
    rw [Finset.mem_sdiff]
    refine ⟨Finset.mem_univ y, ?_⟩
    intro hyCi
    simp only [C, Finset.mem_insert, SimpleGraph.mem_neighborFinset] at hy
    rcases hy with hyj | hjy
    · exact hj (hyj ▸ hyCi)
    · exact hj (hclosed hyCi (G.symm hjy))
  have halphaPos : 0 < Fintype.card alpha := by omega
  obtain ⟨i⟩ := Fintype.card_pos_iff.mp halphaPos
  let R1 : Finset alpha := Finset.univ \ C i
  have hR1card : R1.card = 5 := by
    dsimp only [R1]
    rw [Finset.card_sdiff_of_subset (Finset.subset_univ _),
      Finset.card_univ, hcard, hCcard]
  obtain ⟨j, hjR1⟩ := Finset.card_pos.mp (show 0 < R1.card by omega)
  have hjNotCi : j ∉ C i := (Finset.mem_sdiff.mp hjR1).2
  have hCjR1 : C j ⊆ R1 := by
    simpa only [R1] using hCsubset_compl hjNotCi
  let R2 : Finset alpha := R1 \ C j
  have hR2card : R2.card = 2 := by
    dsimp only [R2]
    rw [Finset.card_sdiff_of_subset hCjR1, hR1card, hCcard]
  obtain ⟨k, hkR2⟩ := Finset.card_pos.mp (show 0 < R2.card by omega)
  have hkR1 : k ∈ R1 := (Finset.mem_sdiff.mp hkR2).1
  have hkNotCj : k ∉ C j := (Finset.mem_sdiff.mp hkR2).2
  have hkNotCi : k ∉ C i := (Finset.mem_sdiff.mp hkR1).2
  have hCkR1 : C k ⊆ R1 := by
    simpa only [R1] using hCsubset_compl hkNotCi
  have hCkR2 : C k ⊆ R2 := by
    intro y hyCk
    change y ∈ R1 \ C j
    rw [Finset.mem_sdiff]
    refine ⟨hCkR1 hyCk, ?_⟩
    exact (Finset.mem_sdiff.mp (hCsubset_compl hkNotCj hyCk)).2
  have hcardMono := Finset.card_le_card hCkR2
  rw [hCcard, hR2card] at hcardMono
  omega

/-- The seven-vertex companion to
`edgeFinset_card_le_seven_of_card_eq_eight`.  Closed three-vertex blocks can
cover at most six of seven vertices, so the handshake ceiling is again
strict. -/
theorem edgeFinset_card_le_six_of_card_eq_seven
    {alpha : Type*} [Fintype alpha]
    (G : SimpleGraph alpha)
    (hcard : Fintype.card alpha = 7)
    (hdegree : forall i, G.degree i <= 2)
    (htrans : forall {i j k : alpha}, G.Adj i j -> G.Adj j k ->
      i = k \/ G.Adj i k) :
    G.edgeFinset.card <= 6 := by
  classical
  have hsumLe : (∑ i : alpha, G.degree i) <= ∑ _i : alpha, 2 :=
    Finset.sum_le_sum fun i _ => hdegree i
  rw [G.sum_degrees_eq_twice_card_edges] at hsumLe
  simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul, hcard] at hsumLe
  have hedgeLe : G.edgeFinset.card <= 7 := by omega
  by_contra hedgeNot
  have hedgeEq : G.edgeFinset.card = 7 := by omega
  have hsumEq : (∑ i : alpha, G.degree i) = ∑ _i : alpha, 2 := by
    rw [G.sum_degrees_eq_twice_card_edges]
    simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul, hedgeEq, hcard]
  have hdegreeEq : forall i, G.degree i = 2 := by
    exact fun i =>
      (Finset.sum_eq_sum_iff_of_le fun j _ => hdegree j).mp hsumEq
        i (Finset.mem_univ i)
  let C : alpha -> Finset alpha := fun i => insert i (G.neighborFinset i)
  have hCcard (i : alpha) : (C i).card = 3 := by
    dsimp only [C]
    rw [Finset.card_insert_of_notMem]
    · rw [SimpleGraph.card_neighborFinset_eq_degree, hdegreeEq i]
    · simpa only [SimpleGraph.mem_neighborFinset] using G.loopless.irrefl i
  have hclosed {i x y : alpha} (hx : x ∈ C i) (hxy : G.Adj x y) :
      y ∈ C i := by
    simp only [C, Finset.mem_insert, SimpleGraph.mem_neighborFinset] at hx ⊢
    rcases hx with hxi | hix
    · subst x
      exact Or.inr hxy
    · rcases htrans hix hxy with hiy | hiy
      · exact Or.inl hiy.symm
      · exact Or.inr hiy
  have hCsubset_compl {i j : alpha} (hj : j ∉ C i) :
      C j ⊆ (Finset.univ : Finset alpha) \ C i := by
    intro y hy
    rw [Finset.mem_sdiff]
    refine ⟨Finset.mem_univ y, ?_⟩
    intro hyCi
    simp only [C, Finset.mem_insert, SimpleGraph.mem_neighborFinset] at hy
    rcases hy with hyj | hjy
    · exact hj (hyj ▸ hyCi)
    · exact hj (hclosed hyCi (G.symm hjy))
  have halphaPos : 0 < Fintype.card alpha := by omega
  obtain ⟨i⟩ := Fintype.card_pos_iff.mp halphaPos
  let R1 : Finset alpha := Finset.univ \ C i
  have hR1card : R1.card = 4 := by
    dsimp only [R1]
    rw [Finset.card_sdiff_of_subset (Finset.subset_univ _),
      Finset.card_univ, hcard, hCcard]
  obtain ⟨j, hjR1⟩ := Finset.card_pos.mp (show 0 < R1.card by omega)
  have hjNotCi : j ∉ C i := (Finset.mem_sdiff.mp hjR1).2
  have hCjR1 : C j ⊆ R1 := by
    simpa only [R1] using hCsubset_compl hjNotCi
  let R2 : Finset alpha := R1 \ C j
  have hR2card : R2.card = 1 := by
    dsimp only [R2]
    rw [Finset.card_sdiff_of_subset hCjR1, hR1card, hCcard]
  obtain ⟨k, hkR2⟩ := Finset.card_pos.mp (show 0 < R2.card by omega)
  have hkR1 : k ∈ R1 := (Finset.mem_sdiff.mp hkR2).1
  have hkNotCj : k ∉ C j := (Finset.mem_sdiff.mp hkR2).2
  have hkNotCi : k ∉ C i := (Finset.mem_sdiff.mp hkR1).2
  have hCkR1 : C k ⊆ R1 := by
    simpa only [R1] using hCsubset_compl hkNotCi
  have hCkR2 : C k ⊆ R2 := by
    intro y hyCk
    change y ∈ R1 \ C j
    rw [Finset.mem_sdiff]
    refine ⟨hCkR1 hyCk, ?_⟩
    exact (Finset.mem_sdiff.mp (hCsubset_compl hkNotCj hyCk)).2
  have hcardMono := Finset.card_le_card hCkR2
  rw [hCcard, hR2card] at hcardMono
  omega

/-- The concrete eight-column specialization used by the remaining
`n=16,k=4` regular-outsider branch. -/
theorem chordGraph_edgeFinset_card_le_eight
    (P : Submodule F V) (v : I -> V)
    (hI : Fintype.card I = 8)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P) :
    (chordGraph P v).edgeFinset.card ≤ 8 := by
  simpa only [hI] using
    chordGraph_edgeFinset_card_le P v hP hMDS4 hnoColumn

/-- The strengthened eight-column chord bound. -/
theorem chordGraph_edgeFinset_card_le_seven
    (P : Submodule F V) (v : I -> V)
    (hI : Fintype.card I = 8)
    (hP : finrank F P <= 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : forall i, v i ∉ P) :
    (chordGraph P v).edgeFinset.card <= 7 := by
  apply edgeFinset_card_le_seven_of_card_eq_eight
    (chordGraph P v) hI
  · exact chordGraph_degree_le_two P v hP hMDS4 hnoColumn
  · intro i j k hij hjk
    exact chordGraph_adj_trans_or_eq P v hMDS4 hnoColumn hij hjk

/-- The strengthened seven-column chord bound used after deleting one
coordinate-column degeneracy. -/
theorem chordGraph_edgeFinset_card_le_six
    (P : Submodule F V) (v : I -> V)
    (hI : Fintype.card I = 7)
    (hP : finrank F P <= 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : forall i, v i ∉ P) :
    (chordGraph P v).edgeFinset.card <= 6 := by
  apply edgeFinset_card_le_six_of_card_eq_seven
    (chordGraph P v) hI
  · exact chordGraph_degree_le_two P v hP hMDS4 hnoColumn
  · intro i j k hij hjk
    exact chordGraph_adj_trans_or_eq P v hMDS4 hnoColumn hij hjk

/-- Equality in the chord bound is rigid: every column has chord degree
exactly two. -/
theorem chordGraph_degree_eq_two_of_edge_card_eq_vertex_card
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P)
    (hedges : (chordGraph P v).edgeFinset.card = Fintype.card I)
    (i : I) :
    (chordGraph P v).degree i = 2 := by
  classical
  let G := chordGraph P v
  change G.degree i = 2
  have hdegree : ∀ j, G.degree j ≤ 2 :=
    chordGraph_degree_le_two P v hP hMDS4 hnoColumn
  have hIpos : 1 ≤ Fintype.card I :=
    Fintype.card_pos_iff.mpr ⟨i⟩
  apply Nat.le_antisymm (hdegree i)
  by_contra hnot
  have hi : G.degree i ≤ 1 := by omega
  have hrest :
      (∑ j ∈ (Finset.univ : Finset I).erase i, G.degree j) ≤
        2 * (Fintype.card I - 1) := by
    calc
      (∑ j ∈ (Finset.univ : Finset I).erase i, G.degree j) ≤
          ∑ _j ∈ (Finset.univ : Finset I).erase i, 2 :=
        Finset.sum_le_sum fun j _ => hdegree j
      _ = 2 * (Fintype.card I - 1) := by
        simp [Finset.card_erase_of_mem, Nat.mul_comm]
  have hsplit := Finset.sum_erase_add (Finset.univ : Finset I)
    (fun j => G.degree j) (Finset.mem_univ i)
  have hsum := G.sum_degrees_eq_twice_card_edges
  have hedges' : G.edgeFinset.card = Fintype.card I := by
    simpa only [G] using hedges
  have htotal :
      (∑ j ∈ (Finset.univ : Finset I).erase i, G.degree j) +
          G.degree i = 2 * Fintype.card I := by
    calc
      (∑ j ∈ (Finset.univ : Finset I).erase i, G.degree j) +
          G.degree i = ∑ j : I, G.degree j := hsplit
      _ = 2 * G.edgeFinset.card := hsum
      _ = 2 * Fintype.card I := by rw [hedges']
  omega

/-- A projectively honest finite family of nonzero points in `P`, each
carried by an indexed column chord, injects into the chord graph. -/
theorem card_le_chords_of_projectively_injective_chord_assignment
    {Gamma : Type*} [DecidableEq Gamma]
    (P : Submodule F V) (v : I -> V)
    (hnoColumn : ∀ i, v i ∉ P)
    (G : Finset Gamma) (left right : Gamma -> I) (point : Gamma -> V)
    (hendpoints : ∀ gamma ∈ G, left gamma ≠ right gamma)
    (hpointNe : ∀ gamma ∈ G, point gamma ≠ 0)
    (hpointP : ∀ gamma ∈ G, point gamma ∈ P)
    (hpointSpan : ∀ gamma ∈ G,
      point gamma ∈ span F ({v (left gamma), v (right gamma)} : Set V))
    (hprojective : ∀ gamma ∈ G, ∀ beta ∈ G,
      (∃ c : F, c • point gamma = point beta) -> gamma = beta) :
    G.card ≤ (chordGraph P v).edgeFinset.card := by
  classical
  let H := chordGraph P v
  have hchord : ∀ gamma ∈ G,
      H.Adj (left gamma) (right gamma) := by
    intro gamma hgamma
    change ChordMeets P v (left gamma) (right gamma)
    have hspan := hpointSpan gamma hgamma
    rw [Submodule.mem_span_pair] at hspan
    obtain ⟨a, b, hab⟩ := hspan
    refine ⟨hendpoints gamma hgamma, a, b, ?_, ?_⟩
    · rw [hab]
      exact hpointNe gamma hgamma
    · rw [hab]
      exact hpointP gamma hgamma
  let edgeOf : {gamma // gamma ∈ G} -> H.edgeFinset := fun gamma =>
    ⟨s(left gamma.1, right gamma.1), by
      rw [SimpleGraph.mem_edgeFinset, SimpleGraph.mem_edgeSet]
      exact hchord gamma.1 gamma.2⟩
  have hedgeInjective : Function.Injective edgeOf := by
    intro gamma beta hedge
    have hedgeValue :
        s(left gamma.1, right gamma.1) =
          s(left beta.1, right beta.1) :=
      congrArg Subtype.val hedge
    have hbetaSpan :
        point beta.1 ∈
          span F ({v (left gamma.1), v (right gamma.1)} : Set V) := by
      rcases Sym2.eq_iff.mp hedgeValue with hsame | hswap
      · simpa only [hsame.1, hsame.2] using
          hpointSpan beta.1 beta.2
      · simpa only [hswap.1, hswap.2, Set.pair_comm] using
          hpointSpan beta.1 beta.2
    obtain ⟨c, hc⟩ := proportional_of_mem_plane_mem_pairSpan
      P v (left gamma.1) (right gamma.1)
        (hnoColumn (left gamma.1))
        (hpointNe gamma.1 gamma.2)
        (hpointP gamma.1 gamma.2)
        (hpointSpan gamma.1 gamma.2)
        (hpointP beta.1 beta.2) hbetaSpan
    apply Subtype.ext
    exact hprojective gamma.1 gamma.2 beta.1 beta.2 ⟨c, hc⟩
  have hcardMap := Fintype.card_le_of_injective edgeOf hedgeInjective
  have hcardMap' : G.card ≤ H.edgeFinset.card := by
    simpa only [Fintype.card_coe] using hcardMap
  simpa only [H] using hcardMap'

/-- The generic projective assignment bound, obtained by combining the chord
injection with the maximum-degree estimate. -/
theorem card_le_columns_of_projectively_injective_chord_assignment
    {Gamma : Type*} [DecidableEq Gamma]
    (P : Submodule F V) (v : I -> V)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P)
    (G : Finset Gamma) (left right : Gamma -> I) (point : Gamma -> V)
    (hendpoints : ∀ gamma ∈ G, left gamma ≠ right gamma)
    (hpointNe : ∀ gamma ∈ G, point gamma ≠ 0)
    (hpointP : ∀ gamma ∈ G, point gamma ∈ P)
    (hpointSpan : ∀ gamma ∈ G,
      point gamma ∈ span F ({v (left gamma), v (right gamma)} : Set V))
    (hprojective : ∀ gamma ∈ G, ∀ beta ∈ G,
      (∃ c : F, c • point gamma = point beta) -> gamma = beta) :
    G.card ≤ Fintype.card I := by
  exact (card_le_chords_of_projectively_injective_chord_assignment
    P v hnoColumn G left right point hendpoints hpointNe hpointP
      hpointSpan hprojective).trans
    (chordGraph_edgeFinset_card_le P v hP hMDS4 hnoColumn)

/-- The strengthened projective-assignment bound for eight columns. -/
theorem card_le_seven_of_projectively_injective_chord_assignment
    {Gamma : Type*} [DecidableEq Gamma]
    (P : Submodule F V) (v : I -> V)
    (hI : Fintype.card I = 8)
    (hP : finrank F P ≤ 2)
    (hMDS4 : IndependentUpTo (F := F) v 4)
    (hnoColumn : ∀ i, v i ∉ P)
    (G : Finset Gamma) (left right : Gamma -> I) (point : Gamma -> V)
    (hendpoints : ∀ gamma ∈ G, left gamma ≠ right gamma)
    (hpointNe : ∀ gamma ∈ G, point gamma ≠ 0)
    (hpointP : ∀ gamma ∈ G, point gamma ∈ P)
    (hpointSpan : ∀ gamma ∈ G,
      point gamma ∈ span F ({v (left gamma), v (right gamma)} : Set V))
    (hprojective : ∀ gamma ∈ G, ∀ beta ∈ G,
      (∃ c : F, c • point gamma = point beta) -> gamma = beta) :
    G.card ≤ 7 := by
  exact (card_le_chords_of_projectively_injective_chord_assignment
    P v hnoColumn G left right point hendpoints hpointNe hpointP
      hpointSpan hprojective).trans
    (chordGraph_edgeFinset_card_le_seven P v hI hP hMDS4 hnoColumn)

end ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterKFourSyndromeChordBound

/-! ## Axiom audit -/

open ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterKFourSyndromeChordBound
#print axioms right_mem_sup_span_of_chordMeets
#print axioms finrank_inf_pairSpan_le_one
#print axioms proportional_of_mem_plane_mem_pairSpan
#print axioms le_pairSpan_of_finrank_le_one_of_chordMeets
#print axioms pair_eq_of_chordMeets_of_finrank_le_one
#print axioms chordGraph_degree_le_two
#print axioms chordGraph_edgeFinset_card_le
#print axioms chordGraph_edgeFinset_card_le_eight
#print axioms edgeFinset_card_le_seven_of_card_eq_eight
#print axioms chordGraph_edgeFinset_card_le_seven
#print axioms edgeFinset_card_le_six_of_card_eq_seven
#print axioms chordGraph_edgeFinset_card_le_six
#print axioms chordGraph_degree_eq_two_of_edge_card_eq_vertex_card
#print axioms card_le_columns_of_projectively_injective_chord_assignment
#print axioms card_le_seven_of_projectively_injective_chord_assignment
