/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Hab25CaptureKernelUD

/-!
# A smooth-domain rate-quarter half-predecessor counterexample over `F_97`

This file transcribes and independently checks the exact certificate generated
by `scripts/probes/probe_rate_quarter_smooth_isolated_counterexample.py`.
The evaluation domain is the order-`32` subgroup generated by `28` in `F_97`.
For the rate-quarter Reed--Solomon code of dimension `8`, the displayed stack
has at least `36` MCA-bad scalars at radius `15/32`, whose agreement threshold
is `17`.

The proof does not enumerate the Reed--Solomon code.  Each scalar is supplied
with:

* one of three degree-`<8` polynomial pairs `(a_l,r_l)`;
* a sixteen-coordinate core on which `(a_l,r_l)=(u_0,u_1)`;
* one fresh coordinate and `q=a_l+gamma*r_l` agreeing with the folded word.

Any hypothetical joint degree-`<8` explanation agrees with `(a_l,r_l)` on the
sixteen-point core, hence is equal to it by the polynomial root bound.  The
explicit fresh-coordinate mismatch then gives the required non-jointness.
Thus all computational work is confined to closed finite-field equalities;
the structural no-joint argument remains algebraic.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false
set_option linter.unusedFintypeInType false
set_option linter.style.multiGoal false

open Finset Polynomial
open _root_.ProximityGap Code
open CodingTheory.ProximityGap.Hab25Core.Hab25JohnsonEndgame
open scoped NNReal Polynomial

namespace ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterSmoothCounterexampleF97

attribute [local instance] Classical.propDecidable

abbrev F97 := ZMod 97

local instance localInstance_HalfPredecessorRateQuarterSmoothCounterexampleF97_1 : Fact (Nat.Prime 97) := ⟨by decide⟩

/-- A generator of the order-`32` subgroup of `F_97^*`. -/
def omega : F97 := 28

/-- The powers `omega^0,...,omega^31`, written explicitly so closed certificate
checks reduce without repeatedly normalizing modular exponentiation. -/
def domainValues : Fin 32 → F97 := ![
  1, 28, 8, 30, 64, 46, 27, 77,
  22, 34, 79, 78, 50, 42, 12, 45,
  96, 69, 89, 67, 33, 51, 70, 20,
  75, 63, 18, 19, 47, 55, 85, 52]

/-- The smooth evaluation domain `mu_32`, enumerated by powers of `omega`. -/
def dom : Fin 32 ↪ F97 :=
  ⟨domainValues, by decide⟩

theorem domainValues_eq_pow (e : Fin 32) :
    domainValues e = omega ^ (e : ℕ) := by
  fin_cases e <;> decide

theorem omega_pow_thirtyTwo : omega ^ 32 = (1 : F97) := by decide

/-- The first received row of the exact certificate. -/
def u0 : Fin 32 → F97 := ![
  0, 0, 77, 0, 0, 0, 0, 0,
  0, 59, 53, 54, 54, 26, 84, 45,
  0, 0, 20, 0, 0, 0, 0, 0,
  0, 38, 44, 43, 43, 71, 13, 52]

/-- The second received row of the exact certificate. -/
def u1 : Fin 32 → F97 := ![
  0, 0, 46, 0, 0, 0, 0, 0,
  0, 16, 24, 38, 36, 93, 7, 2,
  0, 0, 46, 0, 0, 0, 0, 0,
  0, 16, 24, 38, 36, 93, 7, 2]

def u : WordStack F97 (Fin 2) (Fin 32) := ![u0, u1]

@[simp] theorem u_zero : u 0 = u0 := rfl
@[simp] theorem u_one : u 1 = u1 := rfl

/-! ## Three polynomial lines and their sixteen-coordinate cores -/

/-- The three direction polynomials `f_1,f_2,f_3` from the probe. -/
noncomputable def r : Fin 3 → F97[X] := ![
  0,
  C 63 + C 77 * X ^ 2 + C 34 * X ^ 4 + C 20 * X ^ 6,
  C 12 + C 10 * X ^ 2 + C 76 * X ^ 4 + C 1 * X ^ 6]

/-- The line intercept is `X*f_i`. -/
noncomputable def a (line : Fin 3) : F97[X] := X * r line

/-- The three sixteen-coordinate cores. -/
def core : Fin 3 → Finset (Fin 32) := ![
  {0, 1, 3, 4, 5, 6, 7, 8, 16, 17, 19, 20, 21, 22, 23, 24},
  {0, 1, 2, 8, 9, 10, 11, 12, 16, 17, 18, 24, 25, 26, 27, 28},
  {2, 3, 5, 7, 9, 10, 13, 14, 18, 19, 21, 23, 25, 26, 29, 30}]

theorem core_card (line : Fin 3) : (core line).card = 16 := by
  fin_cases line <;> decide

theorem fourTermEven_natDegree_le_six (c0 c2 c4 c6 : F97) :
    (C c0 + C c2 * X ^ 2 + C c4 * X ^ 4 + C c6 * X ^ 6).natDegree ≤ 6 := by
  refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
  · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
    · refine (natDegree_add_le _ _).trans (max_le ?_ ?_)
      · exact le_trans (Polynomial.natDegree_C c0).le (by omega)
      · exact (Polynomial.natDegree_C_mul_X_pow_le c2 2).trans (by omega)
    · exact (Polynomial.natDegree_C_mul_X_pow_le c4 4).trans (by omega)
  · exact (Polynomial.natDegree_C_mul_X_pow_le c6 6).trans (by omega)

theorem r_natDegree_le_six (line : Fin 3) : (r line).natDegree ≤ 6 := by
  fin_cases line
  · simp [r]
  · exact fourTermEven_natDegree_le_six 63 77 34 20
  · exact fourTermEven_natDegree_le_six 12 10 76 1

theorem r_natDegree_lt_eight (line : Fin 3) : (r line).natDegree < 8 :=
  (r_natDegree_le_six line).trans_lt (by omega)

theorem a_natDegree_lt_eight (line : Fin 3) : (a line).natDegree < 8 := by
  have hmul : (X * r line).natDegree ≤ X.natDegree + (r line).natDegree :=
    Polynomial.natDegree_mul_le
  have hr := r_natDegree_le_six line
  rw [a]
  simp only [natDegree_X] at hmul
  omega

theorem degree_lt_of_natDegree_lt_eight {p : F97[X]}
    (hp : p.natDegree < 8) : p.degree < (8 : ℕ) := by
  by_cases hzero : p = 0
  · rw [hzero]
    exact WithBot.bot_lt_coe 8
  · exact (Polynomial.natDegree_lt_iff_degree_lt hzero).mp hp

theorem r_degree_lt_eight (line : Fin 3) : (r line).degree < (8 : ℕ) :=
  degree_lt_of_natDegree_lt_eight (r_natDegree_lt_eight line)

theorem a_degree_lt_eight (line : Fin 3) : (a line).degree < (8 : ℕ) :=
  degree_lt_of_natDegree_lt_eight (a_natDegree_lt_eight line)

set_option maxHeartbeats 2000000 in
-- This closed check expands three lines across all 32 explicit coordinates.
set_option linter.flexible false in
-- The simplifier intentionally normalizes each closed certificate branch.
/-- On each core, the displayed polynomial pair exactly equals the received
pair.  This is the first closed finite-field part of the certificate. -/
theorem core_pair_agreement (line : Fin 3) (e : Fin 32)
    (he : e ∈ core line) :
    (a line).eval (dom e) = u0 e ∧ (r line).eval (dom e) = u1 e := by
  fin_cases line <;> fin_cases e <;> simp [core] at he
  all_goals simp [a, r, dom, u0, u1]
  all_goals decide

/-! ## The 36 indexed scalar certificates -/

/-- The 36 distinct bad scalars, in increasing integer representative order. -/
def gamma : Fin 36 → F97 := ![
  1, 8, 12, 17, 18, 19, 20, 22, 26,
  27, 28, 30, 33, 34, 40, 42, 46, 47,
  50, 51, 55, 57, 63, 64, 67, 69, 70,
  71, 75, 77, 78, 79, 80, 85, 89, 96]

/-- Which of the three polynomial lines certifies each scalar. -/
def certificateLine : Fin 36 → Fin 3 := ![
  2, 0, 0, 2, 0, 0, 1, 2, 0,
  1, 2, 1, 1, 0, 1, 0, 1, 0,
  0, 1, 0, 1, 0, 1, 1, 2, 1,
  0, 2, 1, 0, 0, 2, 0, 0, 2]

/-- The fresh coordinate appended to the corresponding sixteen-point core. -/
def fresh : Fin 36 → Fin 32 := ![
  16, 18, 30, 31, 10, 11, 7, 24, 15,
  22, 17, 19, 4, 25, 15, 29, 21, 12,
  28, 5, 13, 31, 9, 20, 3, 1, 6,
  31, 8, 23, 27, 26, 15, 14, 2, 0]

/-- The decoded polynomial at an indexed scalar. -/
noncomputable def q (j : Fin 36) : F97[X] :=
  a (certificateLine j) + C (gamma j) * r (certificateLine j)

/-- Its seventeen-coordinate witness support. -/
def support (j : Fin 36) : Finset (Fin 32) :=
  insert (fresh j) (core (certificateLine j))

theorem fresh_not_mem_core (j : Fin 36) :
    fresh j ∉ core (certificateLine j) := by
  fin_cases j <;> decide

theorem support_card (j : Fin 36) : (support j).card = 17 := by
  simp [support, fresh_not_mem_core, core_card]

theorem q_natDegree_lt_eight (j : Fin 36) : (q j).natDegree < 8 := by
  have hCr : (C (gamma j) * r (certificateLine j)).natDegree ≤
      (r (certificateLine j)).natDegree :=
    natDegree_C_mul_le (gamma j) (r (certificateLine j))
  exact lt_of_le_of_lt (natDegree_add_le _ _)
    (max_lt (a_natDegree_lt_eight (certificateLine j))
      (lt_of_le_of_lt hCr (r_natDegree_lt_eight (certificateLine j))))

theorem q_degree_lt_eight (j : Fin 36) : (q j).degree < (8 : ℕ) :=
  degree_lt_of_natDegree_lt_eight (q_natDegree_lt_eight j)

set_option linter.flexible false in
-- The simplifier intentionally normalizes each closed certificate branch.
/-- The fresh coordinate satisfies the folded agreement equation. -/
theorem fresh_agreement (j : Fin 36) :
    (q j).eval (dom (fresh j)) =
      u0 (fresh j) + gamma j * u1 (fresh j) := by
  fin_cases j <;> simp [q, a, r, certificateLine, fresh, gamma,
    dom, u0, u1]
  all_goals decide

set_option linter.flexible false in
-- The simplifier intentionally normalizes each closed certificate branch.
/-- The underlying line pair fails to match the received pair at the fresh
coordinate.  This is the second closed finite-field part of the certificate. -/
theorem fresh_pair_mismatch (j : Fin 36) :
    ((a (certificateLine j)).eval (dom (fresh j)),
      (r (certificateLine j)).eval (dom (fresh j))) ≠
    (u0 (fresh j), u1 (fresh j)) := by
  fin_cases j <;> simp [a, r, certificateLine, fresh, dom, u0, u1]
  all_goals decide

/-- The selected polynomial agrees with the folded word on the entire
seventeen-coordinate support. -/
theorem support_agreement (j : Fin 36) (e : Fin 32)
    (he : e ∈ support j) :
    (q j).eval (dom e) = u0 e + gamma j * u1 e := by
  simp only [support, Finset.mem_insert] at he
  rcases he with rfl | heCore
  · exact fresh_agreement j
  · have hcore := core_pair_agreement (certificateLine j) e heCore
    simp only [q, eval_add, eval_mul, eval_C]
    rw [hcore.1, hcore.2]

/-! ## Algebraic non-jointness from a large core -/

/-- A sixteen-point core uniquely fixes both degree-`<8` rows.  Consequently
a mismatch at one appended coordinate forbids a joint explanation. -/
theorem not_pairJointAgreesOn_insert_core
    (D : Finset (Fin 32)) (e : Fin 32) (a0 r0 : F97[X])
    (ha : a0.degree < (8 : ℕ)) (hr : r0.degree < (8 : ℕ))
    (hcard : 8 ≤ D.card)
    (hcore : ∀ i ∈ D,
      a0.eval (dom i) = u0 i ∧ r0.eval (dom i) = u1 i)
    (hmismatch : (a0.eval (dom e), r0.eval (dom e)) ≠ (u0 e, u1 e)) :
    ¬ pairJointAgreesOn
      ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
        Set (Fin 32 → F97))
      (insert e D) u0 u1 := by
  rintro ⟨v0, hv0, v1, hv1, hagree⟩
  change v0 ∈ ReedSolomon.code dom 8 at hv0
  change v1 ∈ ReedSolomon.code dom 8 at hv1
  rw [ReedSolomon.mem_code_iff_exists_polynomial] at hv0 hv1
  obtain ⟨p0, hp0, hv0⟩ := hv0
  obtain ⟨p1, hp1, hv1⟩ := hv1
  have hp0eq : p0 = a0 := by
    apply sub_eq_zero.mp
    apply eq_zero_of_degree_lt_of_vanishes_on
      (lt_of_le_of_lt (Polynomial.degree_sub_le _ _) (max_lt hp0 ha))
      D hcard
    intro i hi
    have hreceived := (hagree i (Finset.mem_insert_of_mem hi)).1
    have hpoly : p0.eval (dom i) = u0 i := by
      rw [hv0] at hreceived
      simpa only [ReedSolomon.evalOnPoints, LinearMap.coe_mk,
        AddHom.coe_mk, Function.comp_apply] using hreceived
    rw [eval_sub, hpoly, (hcore i hi).1, sub_self]
  have hp1eq : p1 = r0 := by
    apply sub_eq_zero.mp
    apply eq_zero_of_degree_lt_of_vanishes_on
      (lt_of_le_of_lt (Polynomial.degree_sub_le _ _) (max_lt hp1 hr))
      D hcard
    intro i hi
    have hreceived := (hagree i (Finset.mem_insert_of_mem hi)).2
    have hpoly : p1.eval (dom i) = u1 i := by
      rw [hv1] at hreceived
      simpa only [ReedSolomon.evalOnPoints, LinearMap.coe_mk,
        AddHom.coe_mk, Function.comp_apply] using hreceived
    rw [eval_sub, hpoly, (hcore i hi).2, sub_self]
  apply hmismatch
  have hfresh := hagree e (Finset.mem_insert_self e D)
  have hfirst : a0.eval (dom e) = u0 e := by
    have h := hfresh.1
    rw [hv0, hp0eq] at h
    simpa only [ReedSolomon.evalOnPoints, LinearMap.coe_mk,
      AddHom.coe_mk, Function.comp_apply] using h
  have hsecond : r0.eval (dom e) = u1 e := by
    have h := hfresh.2
    rw [hv1, hp1eq] at h
    simpa only [ReedSolomon.evalOnPoints, LinearMap.coe_mk,
      AddHom.coe_mk, Function.comp_apply] using h
  exact Prod.ext hfirst hsecond

theorem support_not_joint (j : Fin 36) :
    ¬ pairJointAgreesOn
      ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
        Set (Fin 32 → F97))
      (support j) u0 u1 := by
  apply not_pairJointAgreesOn_insert_core
    (core (certificateLine j)) (fresh j)
    (a (certificateLine j)) (r (certificateLine j))
    (a_degree_lt_eight (certificateLine j))
    (r_degree_lt_eight (certificateLine j))
    (by rw [core_card]; omega)
    (core_pair_agreement (certificateLine j))
    (fresh_pair_mismatch j)

/-! ## Literal MCA events and the 36-scalar lower bound -/

theorem radius_product_eq_seventeen :
    ((1 : ℝ≥0) - (15 / 32 : ℝ≥0)) *
      (Fintype.card (Fin 32) : ℝ≥0) = 17 := by
  have h1532 : (15 / 32 : ℝ≥0) ≤ 1 := by
    rw [div_le_one (by norm_num : (0 : ℝ≥0) < 32)]
    norm_num
  apply NNReal.coe_injective
  rw [NNReal.coe_mul, NNReal.coe_sub h1532]
  push_cast [Fintype.card_fin]
  norm_num

/-- The explicit decode certificate for indexed scalar `j`. -/
noncomputable def decode (j : Fin 36) :
    McaDecode dom 8 (15 / 32) u (gamma j) where
  S := support j
  P := q j
  hdeg := q_degree_lt_eight j
  hcard := by
    rw [support_card, radius_product_eq_seventeen]
    norm_num
  hagree := by
    intro e he
    simpa only [u_zero, u_one, smul_eq_mul] using support_agreement j e he
  hnjp := by
    simpa only [u_zero, u_one] using support_not_joint j

theorem mcaEvent_index (j : Fin 36) :
    mcaEvent
      ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
        Set (Fin 32 → F97))
      (15 / 32) (u 0) (u 1) (gamma j) :=
  (decode j).mcaEvent

/-- The scalar enumeration is injective. -/
def gammaEmbedding : Fin 36 ↪ F97 := ⟨gamma, by decide⟩

/-- The displayed finite set of 36 bad scalars. -/
def G : Finset F97 := Finset.univ.map gammaEmbedding

theorem G_card : G.card = 36 := by
  simp [G]

/-- Every displayed scalar belongs to the literal MCA bad-event filter. -/
theorem G_subset_badScalar_filter :
    G ⊆ Finset.univ.filter fun gamma : F97 =>
      mcaEvent
        ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
          Set (Fin 32 → F97))
        (15 / 32) (u 0) (u 1) gamma := by
  intro gammaValue hgamma
  rw [G, Finset.mem_map] at hgamma
  obtain ⟨j, hj, rfl⟩ := hgamma
  simp only [Finset.mem_filter, Finset.mem_univ, true_and]
  exact mcaEvent_index j

/-- **Exact smooth counterexample.**  The bad-scalar filter has at least 36
members, and therefore strictly more than the domain size 32. -/
theorem thirtySix_le_badScalar_filter_card :
    36 ≤ (Finset.univ.filter fun gamma : F97 =>
      mcaEvent
        ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
          Set (Fin 32 → F97))
        (15 / 32) (u 0) (u 1) gamma).card := by
  rw [← G_card]
  exact Finset.card_le_card G_subset_badScalar_filter

theorem thirtyTwo_lt_badScalar_filter_card :
    32 < (Finset.univ.filter fun gamma : F97 =>
      mcaEvent
        ((ReedSolomon.code dom 8 : Submodule F97 (Fin 32 → F97)) :
          Set (Fin 32 → F97))
        (15 / 32) (u 0) (u 1) gamma).card := by
  exact lt_of_lt_of_le (by norm_num : 32 < 36)
    thirtySix_le_badScalar_filter_card

end ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterSmoothCounterexampleF97

/-! ## Axiom audit -/

open ArkLib.ProximityGap.Frontier.HalfPredecessorRateQuarterSmoothCounterexampleF97
#print axioms omega_pow_thirtyTwo
#print axioms core_pair_agreement
#print axioms fresh_agreement
#print axioms fresh_pair_mismatch
#print axioms not_pairJointAgreesOn_insert_core
#print axioms mcaEvent_index
#print axioms G_subset_badScalar_filter
#print axioms thirtySix_le_badScalar_filter_card
#print axioms thirtyTwo_lt_badScalar_filter_card
