/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.ConstantIndexGaussSumBound
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._R17QuadrupleWeilRung
import ArkLib.ToMathlib.NumberTheory.GaussSumNorm

/-!
# R19 (lane CHIDECOMP): `ChiDecompositionOff` is a THEOREM — the R15/R17 named input discharged

Round 19 of issue #466.  The R17 rung interface named three inputs; this file proves the first
one, `ChiDecompositionOff`, outright (no named residual):

For a multiplicative character `χ : F → ℂ` of order `m = orderOf χ`, cutting out the index-`m`
subgroup `H = G_χ = {a : χ a = 1}`, a primitive additive character `ψ`, and any `G ⊆ D`,
for every offset `s₀ ∉ D`:

  `m · I_H(s₀) = −|G| + ∑_{j=1}^{m−1} g(χ^j) · T_{χ^j}(s₀)`

with `g(χ') = gaussSum χ' ψ` and `T_{χ'}(s₀) = ∑_{x∈G} conj(χ'(s₀−x))` (= `twistedThinSum`).

Probe: `probe_r19_chidecomp.py` — worst |LHS−RHS| ≤ 8.2e-13 over ALL admissible `s₀` at
`(p,n,m) ∈ {(41,8,2),(41,8,4),(41,8,5),(73,8,3),(73,8,4)}` in the EXACT Lean convention.

Derivation (all steps below are Lean theorems):
1. indicator: `m·I_H(s₀) = ∑_{j<m} ∑_b χ^j(b)·conj(η_b)·ψ(b·s₀)` (`mulChar_pow_sum_all`);
2. swap: the inner sum is `∑_{x∈G} gaussSum(χ^j, mulShift ψ (s₀−x))`
   (`conj(ψ(bx)) = ψ(−bx)`, so `ψ(b·s₀)·conj(ψ(bx)) = (mulShift ψ (s₀−x)) b`);
3. `j = 0`: `gaussSum(1, ψ') = −1` for `ψ' ≠ 1`; since `s₀ ∉ D ⊇ G` every shift `s₀−x ≠ 0`
   and `ψ` is primitive, the `j = 0` row sums to `−|G|`;
4. `1 ≤ j < m`: `gaussSum(χ^j, mulShift ψ u) = conj(χ^j(u))·gaussSum(χ^j, ψ)` for `u ≠ 0`
   (Mathlib `gaussSum_mulShift` + unit-circle values `mulChar_mul_conj`), so the `j`-th row
   is `g(χ^j)·T_{χ^j}(s₀)`;
5. re-index the rows `j ∈ (range m).erase 0` as the character set
   `X = image (χ ^ ·) ((range m).erase 0)` (injective by `pow_injOn_Iio_orderOf`).

Deliverables:
* `chiDecompositionOff_holds` — `ChiDecompositionOff ψ G (Gchi χ) D (chiFamily χ)
  (fun χ' => gaussSum χ' ψ) (orderOf χ)` from `hψ : ψ.IsPrimitive` and `hGD : G ⊆ D`.
* `gaussSumSizeBound_holds` — `GaussSumSizeBound (chiFamily χ) (fun χ' => gaussSum χ' ψ)`
  (in fact each Gauss sum has norm EXACTLY `√q`), discharging the SECOND named input for the
  explicit family.
* `chiFamily_card` — `|X| = m − 1` (the exact cardinality the rung constants consume).

After this brick the r = 2 rung `r2Rung_of_gchi` / `wickAwayAtWithConstant_two_of_gchi`
(round 18) needs ONLY `FourthMomentTwistBound` (the quartic Weil input, a Mathlib gap) plus
the regime inequalities.  CORE OPEN, ON-BGK — this is formalization debt paid, not the wall.

Issue #466, round 19, lane CHIDECOMP.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open Finset
open ArkLib.ProximityGap.SubgroupGaussSumSecondMoment
open ArkLib.ProximityGap.ConstantIndexGaussSum
open ArkLib.ProximityGap.Frontier.R15IncidenceMomentInterchange
open ArkLib.ProximityGap.Frontier.R17QuadrupleWeilRung

namespace ArkLib.ProximityGap.Frontier.R19ChiDecomposition

local notation "conj'" => starRingEnd ℂ

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F]

/-- `MulChar F ℂ` needs a (classical) `DecidableEq` for the explicit `Finset.image` family. -/
noncomputable local instance localInstance_R19ChiDecomposition_1 : DecidableEq (MulChar F ℂ) := Classical.decEq _

/-! ### (0) The explicit character family -/

/-- The explicit family `X = {χ^j : 1 ≤ j < orderOf χ}` of the `m−1` nontrivial characters
with `χ'^m = χ₀` generated by `χ`. -/
noncomputable def chiFamily (χ : MulChar F ℂ) : Finset (MulChar F ℂ) :=
  ((Finset.range (orderOf χ)).erase 0).image (χ ^ ·)

/-- Every member of the family is nontrivial. -/
theorem chiFamily_ne_one (χ : MulChar F ℂ) {χ' : MulChar F ℂ} (hχ' : χ' ∈ chiFamily χ) :
    χ' ≠ 1 := by
  obtain ⟨j, hj, rfl⟩ := Finset.mem_image.mp hχ'
  obtain ⟨hj0, hjm⟩ := Finset.mem_erase.mp hj
  exact pow_ne_one_of_lt_orderOf hj0 (Finset.mem_range.mp hjm)

/-- The family has exactly `m − 1` members (`j ↦ χ^j` is injective below the order). -/
theorem chiFamily_card (χ : MulChar F ℂ) : (chiFamily χ).card = orderOf χ - 1 := by
  rw [chiFamily, Finset.card_image_of_injOn, Finset.card_erase_of_mem
    (Finset.mem_range.mpr (MulChar.orderOf_pos χ)), Finset.card_range]
  intro i hi j hj hij
  exact pow_injOn_Iio_orderOf
    (Set.mem_Iio.mpr (Finset.mem_range.mp (Finset.mem_of_mem_erase hi)))
    (Set.mem_Iio.mpr (Finset.mem_range.mp (Finset.mem_of_mem_erase hj))) hij

/-! ### (1) Pointwise ingredients -/

/-- Conjugation moves an additive-character value to the negated argument. -/
theorem conj_addChar_apply (ψ : AddChar F ℂ) (a : F) : conj' (ψ a) = ψ (-a) := by
  have hchar : (0 : ℕ) < ringChar F := by
    haveI := ringChar.charP F
    exact Nat.pos_of_ne_zero (CharP.char_ne_zero_of_finite F (ringChar F))
  rw [AddChar.starComp_apply hchar, AddChar.inv_apply]

/-- The shifted Gauss sum in the conjugated form used by `twistedThinSum`:
`gaussSum χ' (mulShift ψ u) = conj(χ'(u)) · gaussSum χ' ψ` for `u ≠ 0`. -/
theorem gaussSum_mulShift_eq_conj_mul (χ' : MulChar F ℂ) (ψ : AddChar F ℂ)
    {u : F} (hu : u ≠ 0) :
    gaussSum χ' (AddChar.mulShift ψ u) = conj' (χ' u) * gaussSum χ' ψ := by
  have hshift := gaussSum_mulShift χ' ψ hu.isUnit.unit
  rw [IsUnit.unit_spec] at hshift
  calc gaussSum χ' (AddChar.mulShift ψ u)
      = (conj' (χ' u) * χ' u) * gaussSum χ' (AddChar.mulShift ψ u) := by
        rw [mul_comm (conj' (χ' u)) (χ' u),
          ArkLib.ProximityGap.Frontier.R17TchiMomentIdentities.mulChar_mul_conj χ' hu, one_mul]
    _ = conj' (χ' u) * (χ' u * gaussSum χ' (AddChar.mulShift ψ u)) := by ring
    _ = conj' (χ' u) * gaussSum χ' ψ := by rw [hshift]

/-! ### (2) The row identities -/

/-- **Row expansion.** For any character `χ'` (any `j`-th power), the full-`b` twisted incidence
row is a `G`-sum of shifted Gauss sums:
`∑_b χ'(b)·conj(η_b)·ψ(b·s₀) = ∑_{x∈G} gaussSum χ' (mulShift ψ (s₀−x))`. -/
theorem row_expansion (χ' : MulChar F ℂ) (ψ : AddChar F ℂ) (G : Finset F) (s₀ : F) :
    ∑ b : F, χ' b * (conj' (eta ψ G b) * ψ (b * s₀))
      = ∑ x ∈ G, gaussSum χ' (AddChar.mulShift ψ (s₀ - x)) := by
  classical
  calc ∑ b : F, χ' b * (conj' (eta ψ G b) * ψ (b * s₀))
      = ∑ b : F, ∑ x ∈ G, χ' b * (ψ (-(b * x)) * ψ (b * s₀)) := by
        refine Finset.sum_congr rfl (fun b _ => ?_)
        rw [eta, map_sum, Finset.sum_mul, Finset.mul_sum]
        exact Finset.sum_congr rfl (fun x _ => by rw [conj_addChar_apply])
    _ = ∑ x ∈ G, ∑ b : F, χ' b * (ψ (-(b * x)) * ψ (b * s₀)) := Finset.sum_comm
    _ = ∑ x ∈ G, gaussSum χ' (AddChar.mulShift ψ (s₀ - x)) := by
        refine Finset.sum_congr rfl (fun x _ => ?_)
        rw [gaussSum]
        refine Finset.sum_congr rfl (fun b _ => ?_)
        rw [AddChar.mulShift_apply, ← AddChar.map_add_eq_mul]
        have harg : -(b * x) + b * s₀ = (s₀ - x) * b := by ring
        rw [harg]

/-- **Trivial row.** Off `G`, the `j = 0` row collapses to `−|G|`. -/
theorem row_trivial {ψ : AddChar F ℂ} (hψ : ψ.IsPrimitive) (G : Finset F)
    {s₀ : F} (hs₀ : s₀ ∉ G) :
    ∑ b : F, (1 : MulChar F ℂ) b * (conj' (eta ψ G b) * ψ (b * s₀)) = -(G.card : ℂ) := by
  rw [row_expansion]
  have hterm : ∀ x ∈ G, gaussSum (1 : MulChar F ℂ) (AddChar.mulShift ψ (s₀ - x)) = -1 := by
    intro x hx
    have hne : s₀ - x ≠ 0 := sub_ne_zero_of_ne (fun h => hs₀ (h ▸ hx))
    exact gaussSum_one_eq_neg_one (hψ hne)
  rw [Finset.sum_congr rfl hterm, Finset.sum_const, nsmul_eq_mul, mul_neg_one]

/-- **Nontrivial row.** Off `G`, the `j`-th row is `g(χ')·T_{χ'}(s₀)`. -/
theorem row_nontrivial (χ' : MulChar F ℂ) {ψ : AddChar F ℂ} (G : Finset F)
    {s₀ : F} (hs₀ : s₀ ∉ G) :
    ∑ b : F, χ' b * (conj' (eta ψ G b) * ψ (b * s₀))
      = gaussSum χ' ψ * twistedThinSum χ' G s₀ := by
  rw [row_expansion, twistedThinSum, Finset.mul_sum]
  refine Finset.sum_congr rfl (fun x hx => ?_)
  have hne : s₀ - x ≠ 0 := sub_ne_zero_of_ne (fun h => hs₀ (h ▸ hx))
  rw [gaussSum_mulShift_eq_conj_mul χ' ψ hne, mul_comm]

/-! ### (3) The indicator decomposition of the incidence sum -/

/-- **Indicator decomposition.** `m·I_{G_χ}(s₀) = ∑_{j<m} (j-th row)`. -/
theorem incidence_indicator_decomp (χ : MulChar F ℂ) (ψ : AddChar F ℂ) (G : Finset F)
    (s₀ : F) :
    (orderOf χ : ℂ) * incidenceSum ψ G (Gchi χ) s₀
      = ∑ j ∈ Finset.range (orderOf χ),
          ∑ b : F, (χ ^ j) b * (conj' (eta ψ G b) * ψ (b * s₀)) := by
  classical
  rw [Finset.sum_comm]
  symm
  calc ∑ b : F, ∑ j ∈ Finset.range (orderOf χ), (χ ^ j) b * (conj' (eta ψ G b) * ψ (b * s₀))
      = ∑ b : F, (∑ j ∈ Finset.range (orderOf χ), (χ ^ j) b)
          * (conj' (eta ψ G b) * ψ (b * s₀)) := by
        refine Finset.sum_congr rfl (fun b _ => ?_); rw [Finset.sum_mul]
    _ = ∑ b : F, (if χ b = 1 then (orderOf χ : ℂ) else 0)
          * (conj' (eta ψ G b) * ψ (b * s₀)) := by
        refine Finset.sum_congr rfl (fun b _ => by rw [mulChar_pow_sum_all])
    _ = ∑ b : F, if χ b = 1 then (orderOf χ : ℂ) * (conj' (eta ψ G b) * ψ (b * s₀)) else 0 := by
        refine Finset.sum_congr rfl (fun b _ => ?_); simp only [ite_mul, zero_mul]
    _ = ∑ b ∈ Gchi χ, (orderOf χ : ℂ) * (conj' (eta ψ G b) * ψ (b * s₀)) := by
        rw [Gchi, Finset.sum_filter]
    _ = (orderOf χ : ℂ) * ∑ b ∈ Gchi χ, conj' (eta ψ G b) * ψ (b * s₀) := by
        rw [Finset.mul_sum]
    _ = (orderOf χ : ℂ) * incidenceSum ψ G (Gchi χ) s₀ := by rw [incidenceSum]

/-! ### (4) The main theorem: the R17 named input holds -/

/-- **`ChiDecompositionOff` is a theorem** for the explicit family `X = chiFamily χ`,
`g = gaussSum · ψ`, `H = G_χ`, `m = orderOf χ`: for a primitive `ψ` and any `G ⊆ D`,
`m·I_H(s₀) = −|G| + ∑_{χ'∈X} g(χ')·T_{χ'}(s₀)` off `D`.  This discharges the first of the
three round-17/18 named inputs. -/
theorem chiDecompositionOff_holds (χ : MulChar F ℂ) {ψ : AddChar F ℂ} (hψ : ψ.IsPrimitive)
    {G D : Finset F} (hGD : G ⊆ D) :
    ChiDecompositionOff ψ G (Gchi χ) D (chiFamily χ) (fun χ' => gaussSum χ' ψ) (orderOf χ) := by
  intro s₀ hs₀
  have hs₀G : s₀ ∉ G := fun h => hs₀ (hGD h)
  have hm : 0 ∈ Finset.range (orderOf χ) := Finset.mem_range.mpr (MulChar.orderOf_pos χ)
  rw [incidence_indicator_decomp χ ψ G s₀,
    ← Finset.insert_erase hm, Finset.sum_insert (Finset.notMem_erase 0 _)]
  congr 1
  · rw [pow_zero]; exact row_trivial hψ G hs₀G
  · have hinj : ∀ i ∈ (Finset.range (orderOf χ)).erase 0,
        ∀ j ∈ (Finset.range (orderOf χ)).erase 0, χ ^ i = χ ^ j → i = j := by
      intro i hi j hj hij
      exact pow_injOn_Iio_orderOf
        (Set.mem_Iio.mpr (Finset.mem_range.mp (Finset.mem_of_mem_erase hi)))
        (Set.mem_Iio.mpr (Finset.mem_range.mp (Finset.mem_of_mem_erase hj))) hij
    rw [chiFamily, Finset.sum_image hinj]
    exact Finset.sum_congr rfl (fun j _ => row_nontrivial (χ ^ j) G hs₀G)

/-! ### (5) The Gauss-sum size input for the SAME explicit family -/

/-- The Gauss sums of the explicit family have norm exactly `√q`. -/
theorem norm_gaussSum_chiFamily (χ : MulChar F ℂ) {ψ : AddChar F ℂ} (hψ : ψ.IsPrimitive)
    {χ' : MulChar F ℂ} (hχ' : χ' ∈ chiFamily χ) :
    ‖gaussSum χ' ψ‖ = Real.sqrt (Fintype.card F) :=
  _root_.norm_gaussSum_eq_sqrt_card (chiFamily_ne_one χ hχ') hψ

/-- **`GaussSumSizeBound` is a theorem** for the explicit family — the second round-17 named
input discharged. -/
theorem gaussSumSizeBound_holds (χ : MulChar F ℂ) {ψ : AddChar F ℂ} (hψ : ψ.IsPrimitive) :
    GaussSumSizeBound (chiFamily χ) (fun χ' => gaussSum χ' ψ) :=
  fun _ hχ' => le_of_eq (norm_gaussSum_chiFamily χ hψ hχ')

end ArkLib.ProximityGap.Frontier.R19ChiDecomposition

#print axioms ArkLib.ProximityGap.Frontier.R19ChiDecomposition.chiFamily_card
#print axioms ArkLib.ProximityGap.Frontier.R19ChiDecomposition.chiDecompositionOff_holds
#print axioms ArkLib.ProximityGap.Frontier.R19ChiDecomposition.gaussSumSizeBound_holds
