/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._R23TripleConvEnergyInput

/-!
# LANE B2 (#466, r=3 rung, route ii): Hasse–Davenport exact angle relations along
  subgroup cosets of ℤ/m — NEW exact structure on the Jacobi coefficient sequence

## The discovery (math + probe; this session, 2026-07-10)

Apply the classical Hasse–Davenport PRODUCT relation
`∏_{a=0}^{k-1} g(χ'ρ^a) = χ'(k)^{-k}·g(χ'^k)·∏_{a=1}^{k-1} g(ρ^a)` (ρ of order `k`)
to BOTH Gauss-sum factors of `J_j = g(λ^j)·g(χ)/g(λ^j χ)` along the coset
`{j, j+u, j+2u}` of the order-3 subgroup `⟨u⟩ ≤ ℤ/m`, `u = m/3`.  The auxiliary
products `∏_{a=1}^{2} g(ρ^a)` CANCEL between numerator and denominator, leaving:

  **(I3)**  `J_j · J_{j+u} · J_{j+2u} = κ · J₃(3j)`  for EVERY `j : ℤ/m`, where
            `κ = χ(3)³·J(χ,χ)·J(χ²,χ)` (constant in `j`, `‖κ‖ = q`) and
            `J₃ = jacobiCoeff (χ³) lam` — a DEPTH-1 ladder object for `χ³`.

Conditions: `3 ∣ m`, `p ≠ 3`, `χ²` and `χ³` nontrivial.  Probe
`scripts/probes/probe_466_r3_hasse_davenport_coset.py` (deterministic, 75
(q,m,χ)-instances, tolerance 1e-8 relative at scale `q^{3/2}`) verified:

* (I3) holds at EVERY index `j` — including the per-index degenerate cases
  `λ^{3j}χ³` trivial, `λ^{3j}` trivial, `λ^{j+au}χ` trivial (both sides degenerate
  consistently; no index exclusions needed);
* the `χ²`-trivial branch fails by the EXACT factor `q` (lhs `= q·κ·J₃(3j)`,
  verified as identity D3a) — the classical `g(χ)² = χ(−1)q` degeneration;
* the `k = 2` analogue (I2) `J_j·J_{j+m/2} = χ(2)²·J(χ,χ)·J₂(2j)` holds likewise;
* the aggregate (AGG3) `∑_j J_j J_{j+u} J_{j+2u} = κ·m·W_{χ³,G'}(1)` holds exactly,
  `G'` the index-`m/3` coarsening of `G` — a genuine VERTICAL DESCENT: the
  depth-3 coset-diagonal mass IS a depth-1 thin face value of `χ³` over the
  coarser subgroup;
* **refutation half**: the same collapse for the perturbed off-coset triple
  `(j, j+u+1, j+2u−1)` FAILS at 0/m indices in every probed non-vacuous cell
  (m ≥ 6) — the angle rigidity is EXACTLY the coset structure, no further.

## What this brick lands (all axiom-clean)

* `HDCosetTripleCollapse` — the named exact input (classical HD; the Gauss-sum
  product relation is not yet in Mathlib, so the identity is an honest named
  hypothesis with the instantiation pinned above and probe-verified);
* `sum_cosetTripleProduct_eq` — the unconditional aggregation step;
* `sum_jacobiCoeff_subgroup_eq_shiftedSum` — the unconditional Fubini/indicator
  evaluation: `∑_j J₃(3j) = m·(shiftedSum χ₃ G' 1)` given the coarse indicator;
* `sum_cosetTripleProduct_eq_shiftedSum` — the composed exact vertical descent
  (depth-3 coset diagonal = `κ·m·`(depth-1 face of `χ³` at `s = 1` over `G'`));
* `norm_cosetTripleProduct_le` / `cosetTripleProduct_energy_le` — the r=3
  consumers: on the coset-diagonal stratum the triple-product phase mass is
  depth-1-controlled, `∑_j ‖J_j J_{j+u} J_{j+2u}‖² ≤ K²·m·B ( = m·q³ at the
  classical values)` — meeting the Wick budget `m³q³` with `m²` headroom where
  the R23 triangle-inequality baseline loses exactly `m²`.

Honest scope: (I3) constrains the coset-DIAGONAL stratum of `tripleConv`; the
probe countermodel shows the generic off-coset strata do NOT collapse — the open
core `TripleConvEnergyBound` remains open on those strata.  CORE OPEN, ON-BGK.

Axiom-clean (`propext, Classical.choice, Quot.sound`).  Issue #466, LANE B2.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open Finset

namespace ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple

open ArkLib.ProximityGap.Frontier.R19JacobiFourierExpansion

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F]
variable {m : ℕ} [NeZero m] {lam : ZMod m → F → ℂ}

/-- The coset-diagonal triple product of a coefficient sequence along the coset
`{j, j+u, j+2u}` of the subgroup generated by `u`. -/
def cosetTripleProduct (J : ZMod m → ℂ) (u j : ZMod m) : ℂ :=
  J j * J (j + u) * J (j + u + u)

/-- **The named Hasse–Davenport coset collapse** (probe-verified exact identity;
classical instantiation: `J = jacobiCoeff χ lam`, `J₃ = jacobiCoeff (χ³) lam`,
`u = m/3`, `κ = χ(3)³·J(χ,χ)·J(χ²,χ)` with `‖κ‖ = q`, under `3 ∣ m`, `p ≠ 3`,
`χ², χ³` nontrivial — see the file docstring and the probe).  The Gauss-sum
product relation behind it is classical mathematics not yet in Mathlib; this Prop
is the honest named form of exactly that input, nothing more. -/
def HDCosetTripleCollapse (J J₃ : ZMod m → ℂ) (u : ZMod m) (κ : ℂ) : Prop :=
  ∀ j : ZMod m, cosetTripleProduct J u j = κ * J₃ (3 * j)

/-- **Unconditional aggregation.**  Under the collapse, the total coset-diagonal
triple-product mass is `κ` times a pure depth-1 sum. -/
theorem sum_cosetTripleProduct_eq {J J₃ : ZMod m → ℂ} {u : ZMod m} {κ : ℂ}
    (h : HDCosetTripleCollapse J J₃ u κ) :
    ∑ j : ZMod m, cosetTripleProduct J u j = κ * ∑ j : ZMod m, J₃ (3 * j) := by
  rw [Finset.mul_sum]
  exact Finset.sum_congr rfl (fun j _ => h j)

/-- **Unconditional Fubini/indicator evaluation of the depth-1 subgroup sum.**
If the sub-family `{λ_{3j}}` has the coarse indicator property (finite abelian
duality supplies it for the index-`m/3` coarsening `G'` of `G`), then
`∑_j J₃(3j) = m · shiftedSum χ₃ G' 1`. -/
theorem sum_jacobiCoeff_subgroup_eq_shiftedSum (χ₃ : F → ℂ) (G' : Finset F)
    (hcoarse : ∀ t : F, ∑ j : ZMod m, lam (3 * j) t
      = (m : ℂ) * (if t ∈ G' then 1 else 0)) :
    ∑ j : ZMod m, jacobiCoeff χ₃ lam (3 * j) = (m : ℂ) * shiftedSum χ₃ G' 1 := by
  classical
  unfold jacobiCoeff shiftedSum
  rw [Finset.sum_comm]
  have hpt : ∀ t : F,
      ∑ j : ZMod m, lam (3 * j) t * χ₃ (1 - t)
        = (m : ℂ) * (if t ∈ G' then χ₃ (1 - t) else 0) := by
    intro t
    rw [← Finset.sum_mul, hcoarse t]
    split_ifs with ht <;> ring
  rw [Finset.sum_congr rfl (fun t _ => hpt t), ← Finset.mul_sum]
  congr 1
  rw [Finset.sum_ite_mem]
  congr 1
  simp

/-- **The composed exact vertical descent** (depth 3 → depth 1): the aggregated
coset-diagonal triple products equal `κ·m` times the thin-face value of `χ₃` at
`s = 1` over the coarser subgroup `G'`.  This is (AGG3), probe-verified. -/
theorem sum_cosetTripleProduct_eq_shiftedSum {J : ZMod m → ℂ} (χ₃ : F → ℂ)
    (G' : Finset F) {u : ZMod m} {κ : ℂ}
    (h : HDCosetTripleCollapse J (jacobiCoeff χ₃ lam) u κ)
    (hcoarse : ∀ t : F, ∑ j : ZMod m, lam (3 * j) t
      = (m : ℂ) * (if t ∈ G' then 1 else 0)) :
    ∑ j : ZMod m, cosetTripleProduct J u j
      = κ * ((m : ℂ) * shiftedSum χ₃ G' 1) := by
  rw [sum_cosetTripleProduct_eq h,
    sum_jacobiCoeff_subgroup_eq_shiftedSum χ₃ G' hcoarse]

/-- **Pointwise phase rigidity on the coset diagonal.**  Under the collapse, the
depth-3 triple product is depth-1-controlled: `‖J_j J_{j+u} J_{j+2u}‖ ≤ K·B` with
NO triangle inequality over `m`.  At the classical values `K = q`, `B = √q` this
is `q^{3/2}` — the exact Wick-scale pointwise bound on this stratum. -/
theorem norm_cosetTripleProduct_le {J J₃ : ZMod m → ℂ} {u : ZMod m} {κ : ℂ}
    {K B : ℝ} (h : HDCosetTripleCollapse J J₃ u κ) (hκ : ‖κ‖ ≤ K)
    (hB : ∀ c : ZMod m, ‖J₃ c‖ ≤ B) (j : ZMod m) :
    ‖cosetTripleProduct J u j‖ ≤ K * B := by
  have hB0 : (0 : ℝ) ≤ B := le_trans (norm_nonneg _) (hB (3 * j))
  rw [h j, norm_mul]
  exact mul_le_mul hκ (hB (3 * j)) (norm_nonneg _) (le_trans (norm_nonneg _) hκ)

/-- **Coset-diagonal energy meets the Wick budget with `m²` headroom.**  Under
the collapse with `‖κ‖ ≤ K` and `‖J₃‖² ≤ B` pointwise,
`∑_j ‖J_j J_{j+u} J_{j+2u}‖² ≤ K²·m·B`.  At the classical values (`K = q`,
`B = q`) this is `m·q³` — against the r=3 Wick budget `C·m³·q³` the HD stratum
carries `1/m²` of the budget, exactly where the R23 triangle-inequality baseline
loses the factor `m²`. -/
theorem cosetTripleProduct_energy_le {J J₃ : ZMod m → ℂ} {u : ZMod m} {κ : ℂ}
    {K B : ℝ} (h : HDCosetTripleCollapse J J₃ u κ) (hκ : ‖κ‖ ≤ K)
    (hB : ∀ c : ZMod m, ‖J₃ c‖ ^ 2 ≤ B) :
    ∑ j : ZMod m, ‖cosetTripleProduct J u j‖ ^ 2 ≤ K ^ 2 * (m : ℝ) * B := by
  have hK0 : (0 : ℝ) ≤ K := le_trans (norm_nonneg _) hκ
  have hpt : ∀ j : ZMod m, ‖cosetTripleProduct J u j‖ ^ 2 ≤ K ^ 2 * B := by
    intro j
    rw [h j, norm_mul, mul_pow]
    have h1 : ‖κ‖ ^ 2 ≤ K ^ 2 := pow_le_pow_left₀ (norm_nonneg _) hκ 2
    exact mul_le_mul h1 (hB (3 * j)) (sq_nonneg _) (by positivity)
  calc ∑ j : ZMod m, ‖cosetTripleProduct J u j‖ ^ 2
      ≤ ∑ _j : ZMod m, K ^ 2 * B := Finset.sum_le_sum (fun j _ => hpt j)
    _ = ((Finset.univ : Finset (ZMod m)).card : ℝ) * (K ^ 2 * B) := by
        rw [Finset.sum_const, nsmul_eq_mul]
    _ = K ^ 2 * (m : ℝ) * B := by
        simp [ZMod.card]
        ring

end ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple

/-! ## Axiom audit (must be ⊆ {propext, Classical.choice, Quot.sound}; NO sorryAx) -/
open ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple in
#print axioms sum_cosetTripleProduct_eq
open ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple in
#print axioms sum_jacobiCoeff_subgroup_eq_shiftedSum
open ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple in
#print axioms sum_cosetTripleProduct_eq_shiftedSum
open ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple in
#print axioms norm_cosetTripleProduct_le
open ArkLib.ProximityGap.Frontier.R297HasseDavenportCosetTriple in
#print axioms cosetTripleProduct_energy_le
