/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._R323ResultantRecurrenceLatticeIndex
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._R315KernelRelationResultantWeld

/-!
# ROUND 324 (#466, Fable session 2026-07-09): R315 × R323 WELD — every realized kernel
  relation's recurrence lattice has index exactly `|N(d)|`, and `p ∣ N(d)`

R315 turned every realized R314 shadow-kernel relation `d` into a relation polynomial
`P_d` with a nonzero, height-bounded integer annihilator divisible by `p`.  R323 discharged
the determinant identification: `#(ℤ[x]/(x^m+1) ⧸ (P)) = |Res(x^m+1, P)|`.  This brick
welds them at the relation level:

* **`relation_lattice_index`** — for any nonzero coefficient vector `d : Fin (2^k) → ℤ`,
  the recurrence lattice `P_d·ℤ[x]/(x^{2^k}+1)` has index exactly
  `|Res(x^{2^k}+1, P_d)|.natAbs` (never divisible-degenerate: `deg P_d < 2^k`).
* **`realized_relation_lattice_index_and_dvd`** — for a *realized* relation
  (`d ∈ shadowKernelRelations g n (2^k) r`, `g^{2^k} = -1` in char `p`): the index equals
  `|N(d)|.natAbs` AND `p ∣ N(d)`, where `N(d) = patternResultant (2^k) (relationPoly d)`.

This is exactly the algebraic content the R321/R322 census reads off numerically
(`|N(d)|/p ∈ {2,4,8}` on all 92 in-window `n=32` cells): the evaluation kernel sits over a
single short recurrence lattice with explicitly computable dyadic index ratio — now with
zero named hypotheses on the identification side.

Issue #466, round r324.  Target axiom set: `[propext, Classical.choice, Quot.sound]`.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open Polynomial AdjoinRoot

namespace ArkLib.ProximityGap.Frontier.R324RelationLatticeIndexWeld

open ArkLib.ProximityGap.Frontier.FS2PatternAnnihilatorResultant
open ArkLib.ProximityGap.Frontier.R323ResultantRecurrenceLatticeIndex
open ArkLib.ProximityGap.Frontier.R315KernelRelationResultantWeld
open ArkLib.ProximityGap.Frontier.R314KernelRelationMassDecomposition
open ArkLib.ProximityGap.Frontier.R306Depth3CharZeroFloor

/-- A nonzero relation vector's polynomial is never divisible by `x^{2^k}+1`
(degree obstruction). -/
theorem not_fpoly_dvd_relationPoly {k : ℕ} {d : Fin (2 ^ k) → ℤ} (hd : d ≠ 0) :
    ¬ fpoly (2 ^ k) ∣ relationPoly d := by
  intro hdvd
  have hne : relationPoly d ≠ 0 := relationPoly_ne_zero hd
  have hle := Polynomial.natDegree_le_of_dvd hdvd hne
  have hlt := relationPoly_natDegree_lt (m := 2 ^ k) (by positivity) d
  rw [fz_natDegree] at hle
  omega

/-- **Relation-lattice index.**  For any nonzero `d : Fin (2^k) → ℤ`, the recurrence
lattice generated by `P_d` in `ℤ[x]/(x^{2^k}+1)` has index `|Res(x^{2^k}+1, P_d)|`. -/
theorem relation_lattice_index {k : ℕ} {d : Fin (2 ^ k) → ℤ} (hd : d ≠ 0) :
    Nat.card (AdjoinRoot (fpoly (2 ^ k)) ⧸
        Ideal.span ({AdjoinRoot.mk (fpoly (2 ^ k)) (relationPoly d)} :
          Set (AdjoinRoot (fpoly (2 ^ k)))))
      = (patternResultant (2 ^ k) (relationPoly d)).natAbs :=
  nat_card_quot_span_mk_eq_patternResultant k (relationPoly d)
    (not_fpoly_dvd_relationPoly hd)

/-- **Realized-relation weld.**  Every realized R314 shadow-kernel relation in
characteristic `p` (at a `2^{k+1}`-th half-root `g`) has recurrence-lattice index exactly
`|N(d)|` with `p ∣ N(d)`, for the concrete annihilator
`N(d) = Res(x^{2^k}+1, P_d)`. -/
theorem realized_relation_lattice_index_and_dvd
    {F : Type} [Field F] [Fintype F] [DecidableEq F]
    (p : ℕ) [CharP F p] (g : F) (n k r : ℕ)
    (hg : g ^ (2 ^ k) = -1)
    {d : Fin (2 ^ k) → ℤ}
    (hd : d ∈ shadowKernelRelations g n (2 ^ k) r) :
    Nat.card (AdjoinRoot (fpoly (2 ^ k)) ⧸
        Ideal.span ({AdjoinRoot.mk (fpoly (2 ^ k)) (relationPoly d)} :
          Set (AdjoinRoot (fpoly (2 ^ k)))))
      = (patternResultant (2 ^ k) (relationPoly d)).natAbs
    ∧ (p : ℤ) ∣ patternResultant (2 ^ k) (relationPoly d) := by
  have hdstruct := shadowKernelRelation_ne_zero_and_evalVec_eq_zero
    g n (2 ^ k) r hd
  refine ⟨relation_lattice_index hdstruct.1, ?_⟩
  refine charP_dvd_patternResultant_of_common_root (by positivity) F p g hg ?_
  rw [aeval_relationPoly]
  exact hdstruct.2

#print axioms relation_lattice_index
#print axioms realized_relation_lattice_index_and_dvd

end ArkLib.ProximityGap.Frontier.R324RelationLatticeIndexWeld
