/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib

/-!
# R342: the difference-quotient walk has a forced inversion collapse

The quotient walk generated by the multiplicative cosets of `H - 1` cannot
behave like a walk with `|H|-1` independent generators.  The elements `r` and
`r⁻¹` always define the same quotient class modulo `H`, since

`r⁻¹ - 1 = (-r⁻¹) * (r - 1)`.

When `-1,r ∈ H`, the multiplier `-r⁻¹` is again in `H`.  Thus, apart from the
self-inverse element `-1`, the generators occur in forced pairs.  R342's probe
shows that this collapse persists as very slow critical-depth mixing in the
actual prize cells.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.R342DifferenceQuotientWalkNoGo

/-- The exact inversion-pair identity behind the quotient-generator collapse. -/
theorem inv_sub_one_eq_neg_inv_mul_sub_one {F : Type*} [Field F]
    {r : F} (hr : r ≠ 0) :
    r⁻¹ - 1 = (-r⁻¹) * (r - 1) := by
  field_simp
  ring

/-- Subgroup membership of the multiplier witnessing equality of the two
quotient classes. -/
theorem neg_inv_mem_subgroup {F : Type*} [Field F]
    (H : Subgroup Fˣ) {r : Fˣ} (hr : r ∈ H) (hneg : (-1 : Fˣ) ∈ H) :
    -r⁻¹ ∈ H := by
  rw [show -r⁻¹ = (-1 : Fˣ) * r⁻¹ by simp]
  exact H.mul_mem hneg (H.inv_mem hr)

end ArkLib.ProximityGap.Frontier.R342DifferenceQuotientWalkNoGo

#print axioms ArkLib.ProximityGap.Frontier.R342DifferenceQuotientWalkNoGo.inv_sub_one_eq_neg_inv_mul_sub_one
#print axioms ArkLib.ProximityGap.Frontier.R342DifferenceQuotientWalkNoGo.neg_inv_mem_subgroup
