/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib

/-!
# R381: dyadic evaluation groups exclude the R380 cubic resonance

The R380 six-hit syndrome line is generated by a ratio `u` satisfying both
`u^(2^mu)=1` and `u^2+u+1=0`.  These equations are incompatible in characteristic
other than three: the second makes `u^3=1`, while the first makes the order of `u`
divide a power of two.  Coprimality forces `u=1`, contradicting `3 != 0`.
-/

set_option autoImplicit false

namespace ArkLib.ProximityGap.Frontier.R381DyadicCubicResonanceExcluded

/-- A two-power torsion group over a field of characteristic other than three has no
nontrivial cubic resonance. -/
theorem no_dyadic_cubic_resonance {F : Type} [Field F] (mu : Nat) (u : F)
    (hchar : (3 : F) ≠ 0) (hdyadic : u ^ (2 ^ mu) = 1)
    (hcubic : u ^ 2 + u + 1 = 0) : False := by
  have hu3 : u ^ 3 = 1 := by
    apply sub_eq_zero.mp
    linear_combination (u - 1) * hcubic
  have hord3 : orderOf u ∣ 3 := orderOf_dvd_of_pow_eq_one hu3
  have hord2 : orderOf u ∣ 2 ^ mu := orderOf_dvd_of_pow_eq_one hdyadic
  have hcop : Nat.Coprime 3 (2 ^ mu) :=
    (by decide : Nat.Coprime 3 2).pow_right mu
  have hord1 : orderOf u = 1 := Nat.dvd_one.mp (hcop ▸ Nat.dvd_gcd hord3 hord2)
  have hu1 : u = 1 := orderOf_eq_one_iff.mp hord1
  apply hchar
  rw [hu1] at hcubic
  linear_combination hcubic

end ArkLib.ProximityGap.Frontier.R381DyadicCubicResonanceExcluded

#print axioms ArkLib.ProximityGap.Frontier.R381DyadicCubicResonanceExcluded.no_dyadic_cubic_resonance
