/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.CS25RSMinWeight

/-!
# R383: the rich-hyperplane triple dichotomy

Lift an MCA quotient pencil to the supercode generated by RS and the two received
rows.  A selector normal consists of a codeword `c` and two projective coefficients
`a,b`; its agreement coordinates are the zeros of `c + a*u0 + b*u1`.

Given three selector normals, a scalar relation that kills both coefficient columns
`a,b` leaves a Reed--Solomon codeword relation.  If that codeword is nonzero, every
coordinate common to the three agreement sets is one of its roots, so there are fewer
than `k` common coordinates.  If it is zero, the three normals are linearly dependent:
this is exactly the affine-selector cluster branch.
-/

set_option autoImplicit false

open Finset

namespace ArkLib.ProximityGap.Frontier.R383RichHyperplaneTripleDichotomy

variable {ι F : Type} [Fintype ι] [DecidableEq ι]
variable [Field F] [Fintype F] [DecidableEq F]

/-- Coordinates common to a finite family of affine-selector agreement equations. -/
def commonSelectorZeros {J : Type} [Fintype J]
    (c : J → ι → F) (a b : J → F) (u0 u1 : ι → F) : Finset ι :=
  Finset.univ.filter fun i =>
    ∀ j : J, c j i + a j * u0 i + b j * u1 i = 0

/-- **Non-affine branch of the rich-hyperplane triple dichotomy.**  Any relation
among selector normals which cancels the two quotient coordinates but leaves a
nonzero RS codeword forces their common agreement below the RS dimension. -/
theorem card_commonSelectorZeros_lt_of_nonzero_relation
    {J : Type} [Fintype J] [DecidableEq J]
    (domain : ι ↪ F) (k : Nat)
    (c : J → ι → F) (a b lam : J → F) (u0 u1 : ι → F)
    (hc : ∀ j, c j ∈ ReedSolomon.code domain k)
    (ha : ∑ j, lam j * a j = 0)
    (hb : ∑ j, lam j * b j = 0)
    (hne : (∑ j, lam j • c j) ≠ 0) :
    (commonSelectorZeros c a b u0 u1).card < k := by
  classical
  let csum : ι → F := ∑ j, lam j • c j
  have hcsum_mem : csum ∈ ReedSolomon.code domain k := by
    dsimp only [csum]
    exact Submodule.sum_mem _ fun j _ => Submodule.smul_mem _ _ (hc j)
  have hsubset : commonSelectorZeros c a b u0 u1 ⊆
      Finset.univ.filter (fun i => csum i = 0) := by
    intro i hi
    have hzero : ∀ j : J, c j i + a j * u0 i + b j * u1 i = 0 :=
      (Finset.mem_filter.mp hi).2
    rw [Finset.mem_filter]
    refine ⟨Finset.mem_univ _, ?_⟩
    dsimp only [csum]
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    have hsum := Finset.sum_congr rfl fun j (_hj : j ∈ Finset.univ) =>
      congrArg (fun z : F => lam j * z) (hzero j)
    simp only [mul_add, mul_zero] at hsum
    rw [Finset.sum_add_distrib, Finset.sum_add_distrib] at hsum
    have hua : ∑ j, lam j * (a j * u0 i) = 0 := by
      calc
        ∑ j, lam j * (a j * u0 i) = ∑ j, (lam j * a j) * u0 i := by
          apply Finset.sum_congr rfl
          intro j _
          rw [mul_assoc]
        _ = (∑ j, lam j * a j) * u0 i := by rw [Finset.sum_mul]
        _ = 0 := by rw [ha, zero_mul]
    have hub : ∑ j, lam j * (b j * u1 i) = 0 := by
      calc
        ∑ j, lam j * (b j * u1 i) = ∑ j, (lam j * b j) * u1 i := by
          apply Finset.sum_congr rfl
          intro j _
          rw [mul_assoc]
        _ = (∑ j, lam j * b j) * u1 i := by rw [Finset.sum_mul]
        _ = 0 := by rw [hb, zero_mul]
    simpa [hua, hub] using hsum
  exact lt_of_le_of_lt (Finset.card_le_card hsubset)
    (ArkLib.CS25.rs_card_zeros_lt domain k csum hcsum_mem hne)

end ArkLib.ProximityGap.Frontier.R383RichHyperplaneTripleDichotomy

#print axioms
  ArkLib.ProximityGap.Frontier.R383RichHyperplaneTripleDichotomy.card_commonSelectorZeros_lt_of_nonzero_relation
