/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._SupportDividedDifferenceOperator

/-!
# Coefficient/Khatri--Rao factorization of divided-difference rows

The global rank problem acts on degree-`<K` polynomial coefficients.  Each operator row factors
as a label-incidence functional tensored with the Vandermonde evaluation vector
`(1,x,...,x^(K-1))`.  This file makes that factorization explicit without choosing a matrix basis.
-/

set_option autoImplicit false

open Polynomial

namespace ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization

open SupportDividedDifferenceOperator

variable {F X J : Type} [Field F] [DecidableEq J]

/-- Sparse three-label parity vector underlying one divided-difference row.  Repeated row indices
are allowed; `Pi.single` addition then combines their coefficients correctly. -/
def labelParityVector (label : J → F) {support : X → Finset J}
    (row : SupportRow support) : J → F :=
  Pi.single row.anchor₀ (label row.anchor₁ - label row.point) +
    Pi.single row.anchor₁ (label row.point - label row.anchor₀) +
    Pi.single row.point (label row.anchor₀ - label row.anchor₁)

/-- Every local parity row has zero total coefficient. -/
theorem sum_labelParityVector_eq_zero
    [Fintype J] (label : J → F) {support : X → Finset J}
    (row : SupportRow support) :
    ∑ j, labelParityVector label row j = 0 := by
  unfold labelParityVector
  simp only [Pi.add_apply]
  rw [Finset.sum_add_distrib, Finset.sum_add_distrib]
  simp

/-- Every local parity row also has zero label-weighted coefficient.  These are precisely the two
checks of the local dimension-two label Reed--Solomon code. -/
theorem label_dotProduct_labelParityVector_eq_zero
    [Fintype J] (label : J → F) {support : X → Finset J}
    (row : SupportRow support) :
    (fun j => label j) ⬝ᵥ labelParityVector label row = 0 := by
  simp [labelParityVector, dotProduct_add]
  ring

/-- Coordinate-local parity space generated by all divided-difference triples at that coordinate. -/
noncomputable def localParitySpace
    (label : J → F) (support : X → Finset J) (x : X) : Submodule F (J → F) :=
  Submodule.span F {ell | ∃ row : SupportRow support,
    row.coordinate = x ∧ ell = labelParityVector label row}

/-- Every concrete row vector belongs to the parity space at its coordinate. -/
theorem labelParityVector_mem_localParitySpace
    (label : J → F) {support : X → Finset J} (row : SupportRow support) :
    labelParityVector label row ∈ localParitySpace label support row.coordinate := by
  apply Submodule.subset_span
  exact ⟨row, rfl, rfl⟩

/-- Pairing a local parity vector with polynomial evaluations. -/
def parityEvalMeasurement [Fintype J]
    (domain : X → F) (q : J → F[X]) (x : X) (ell : J → F) : F :=
  ell ⬝ᵥ (fun j => (q j).eval (domain x))

/-- A generating parity vector evaluates to the corresponding divided-difference row. -/
theorem parityEvalMeasurement_labelParityVector
    [Fintype J] (domain : X → F) (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) :
    parityEvalMeasurement domain q row.coordinate (labelParityVector label row) =
      dividedDifferenceAt domain label q row := by
  simp [parityEvalMeasurement, labelParityVector, dividedDifferenceAt, add_dotProduct]

/-- **Concrete kernel-to-local-space bridge.**  If a polynomial family lies in the global
support-divided-difference kernel, then at every coordinate its evaluation column annihilates the
entire generated local parity space, not merely the chosen triple rows. -/
theorem parityEvalMeasurement_eq_zero_of_mem_ker
    [Fintype J] (domain : X → F) (support : X → Finset J) (label : J → F)
    (q : J → F[X])
    (hq : q ∈ (supportDividedDifference domain support label).ker) :
    ∀ x ell, ell ∈ localParitySpace label support x →
      parityEvalMeasurement domain q x ell = 0 := by
  intro x
  let pairing : (J → F) →ₗ[F] F :=
    (dotProductBilin F F) (fun j => (q j).eval (domain x))
  have hgenerators :
      {ell | ∃ row : SupportRow support,
        row.coordinate = x ∧ ell = labelParityVector label row} ⊆
        LinearMap.ker pairing := by
    intro ell hell
    obtain ⟨row, hrowx, rfl⟩ := hell
    change pairing (labelParityVector label row) = 0
    have hrowZero := congrFun (LinearMap.mem_ker.mp hq) row
    change dividedDifferenceAt domain label q row = 0 at hrowZero
    rw [← parityEvalMeasurement_labelParityVector domain label q row] at hrowZero
    simpa [pairing, parityEvalMeasurement, hrowx, dotProduct, mul_comm] using hrowZero
  have hspanKer : localParitySpace label support x ≤ LinearMap.ker pairing :=
    Submodule.span_le.mpr hgenerators
  intro ell hell
  have hm := LinearMap.mem_ker.mp (hspanKer hell)
  simpa [pairing, parityEvalMeasurement, dotProduct, mul_comm] using hm

/-- Conversely, annihilating every coordinate-local parity space implies every generating
divided-difference row vanishes. -/
theorem mem_ker_of_parityEvalMeasurement_eq_zero
    [Fintype J] (domain : X → F) (support : X → Finset J) (label : J → F)
    (q : J → F[X])
    (hlocal : ∀ x ell, ell ∈ localParitySpace label support x →
      parityEvalMeasurement domain q x ell = 0) :
    q ∈ (supportDividedDifference domain support label).ker := by
  rw [LinearMap.mem_ker]
  funext row
  change dividedDifferenceAt domain label q row = 0
  rw [← parityEvalMeasurement_labelParityVector domain label q row]
  exact hlocal row.coordinate (labelParityVector label row)
    (labelParityVector_mem_localParitySpace label row)

/-- **Exact Tanner-code semantics.**  The support-divided-difference kernel is equivalent to
annihilating the full local label-parity space at every coordinate. -/
theorem mem_ker_iff_forall_localParity_measurement_eq_zero
    [Fintype J] (domain : X → F) (support : X → Finset J) (label : J → F)
    (q : J → F[X]) :
    q ∈ (supportDividedDifference domain support label).ker ↔
      ∀ x ell, ell ∈ localParitySpace label support x →
        parityEvalMeasurement domain q x ell = 0 := by
  constructor
  · exact parityEvalMeasurement_eq_zero_of_mem_ker domain support label q
  · exact mem_ker_of_parityEvalMeasurement_eq_zero domain support label q

/-- Coefficient of degree `d` in the three-label divided-difference functional. -/
def dividedDifferenceCoeff (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) (d : Nat) : F :=
  (label row.anchor₁ - label row.point) * (q row.anchor₀).coeff d +
    (label row.point - label row.anchor₀) * (q row.anchor₁).coeff d +
    (label row.anchor₀ - label row.anchor₁) * (q row.point).coeff d

/-- The degree-`d` divided-difference coefficient is exactly the sparse label-parity vector paired
with the degree-`d` coefficient column. -/
theorem dividedDifferenceCoeff_eq_labelParity_dotProduct
    [Fintype J] (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) (d : Nat) :
    dividedDifferenceCoeff label q row d =
      labelParityVector label row ⬝ᵥ (fun j => (q j).coeff d) := by
  simp [labelParityVector, dividedDifferenceCoeff, add_dotProduct]

/-- **Khatri--Rao row factorization.**  On degree-`<K` inputs, a support-divided-difference row
is the dot product of its label-incidence coefficient row with the length-`K` Vandermonde row at
the domain coordinate. -/
theorem dividedDifferenceAt_eq_sum_coeff_mul_pow
    (domain : X → F) (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) (K : Nat)
    (hdeg₀ : (q row.anchor₀).natDegree < K)
    (hdeg₁ : (q row.anchor₁).natDegree < K)
    (hdegPoint : (q row.point).natDegree < K) :
    dividedDifferenceAt domain label q row =
      ∑ d ∈ Finset.range K,
        dividedDifferenceCoeff label q row d * domain row.coordinate ^ d := by
  unfold dividedDifferenceAt dividedDifferenceCoeff
  rw [Polynomial.eval_eq_sum_range' hdeg₀, Polynomial.eval_eq_sum_range' hdeg₁,
    Polynomial.eval_eq_sum_range' hdegPoint]
  simp only [Finset.mul_sum, ← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro d _hd
  ring

/-- Degree-`<K` submodule form of the factorization. -/
theorem dividedDifferenceAt_eq_sum_coeff_mul_pow_of_degreeLT
    (domain : X → F) (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) {K : Nat} [NeZero K]
    (hdegree : ∀ j, q j ∈ Polynomial.degreeLT F K) :
    dividedDifferenceAt domain label q row =
      ∑ d ∈ Finset.range K,
        dividedDifferenceCoeff label q row d * domain row.coordinate ^ d := by
  apply dividedDifferenceAt_eq_sum_coeff_mul_pow domain label q row K
  · exact ReedSolomon.natDegree_lt_of_mem_degreeLT (hdegree row.anchor₀)
  · exact ReedSolomon.natDegree_lt_of_mem_degreeLT (hdegree row.anchor₁)
  · exact ReedSolomon.natDegree_lt_of_mem_degreeLT (hdegree row.point)

/-- Fully concrete tensor-row form: each degree slice pairs the sparse local label-parity vector
with the corresponding polynomial coefficient column, then weights it by the Vandermonde entry. -/
theorem dividedDifferenceAt_eq_sum_parity_dotProduct_mul_pow
    [Fintype J] (domain : X → F) (label : J → F) (q : J → F[X])
    {support : X → Finset J} (row : SupportRow support) {K : Nat} [NeZero K]
    (hdegree : ∀ j, q j ∈ Polynomial.degreeLT F K) :
    dividedDifferenceAt domain label q row =
      ∑ d ∈ Finset.range K,
        (labelParityVector label row ⬝ᵥ (fun j => (q j).coeff d)) *
          domain row.coordinate ^ d := by
  rw [dividedDifferenceAt_eq_sum_coeff_mul_pow_of_degreeLT
    domain label q row hdegree]
  apply Finset.sum_congr rfl
  intro d _hd
  rw [dividedDifferenceCoeff_eq_labelParity_dotProduct]

end ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization

#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.dividedDifferenceAt_eq_sum_coeff_mul_pow
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.dividedDifferenceAt_eq_sum_coeff_mul_pow_of_degreeLT
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.dividedDifferenceCoeff_eq_labelParity_dotProduct
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.dividedDifferenceAt_eq_sum_parity_dotProduct_mul_pow
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.sum_labelParityVector_eq_zero
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.label_dotProduct_labelParityVector_eq_zero
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.parityEvalMeasurement_labelParityVector
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.parityEvalMeasurement_eq_zero_of_mem_ker
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.mem_ker_of_parityEvalMeasurement_eq_zero
#print axioms ArkLib.ProximityGap.Frontier.SupportDividedDifferenceCoefficientFactorization.mem_ker_iff_forall_localParity_measurement_eq_zero
