/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors (#466)
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._SYZ62GradedExchange

/-!
# SYZ63 — the leading-vector exchange step, discharged unconditionally

SYZ62 reduced the two-ramp residual to a single named `Prop` — `GradedExchange` — the
leading-vector exchange step of Cox–Sederberg–Chen μ-basis theory, and proved
`windowed generation ⟸ GradedExchange` (`span_of_gradedExchange`).  SYZ61 pinned the syzygy
kernel of a coprime triple as a free `K[X]`-module of rank **exactly 2**.

**This file discharges `GradedExchange` itself, unconditionally and axiom-clean.**  Given any
weight vector `d : Fin 3 → ℕ` and any rank-`2` submodule `N ⊆ K[X]³`, a degree-minimal pair of
generators satisfies the graded exchange step, so — via SYZ62's reduction — `N` is generated by
that pair.

## The argument

Fix weights `d`.  Working in the product-degree grading `pdeg d` (SYZ62):

* **Minimal selection.**  `WithBot ℕ` is well-founded under `<`, so there is a nonzero `e₁ ∈ N` of
  minimal product-degree `δ₁`, and — since `rank N = 2 > 1`, so `K[X]·e₁ ≠ N` — a `e₂ ∈ N \ K[X]·e₁`
  of minimal product-degree `δ₂` among that complement.  Both product-degrees are genuine naturals
  `n₁ ≤ n₂` (nonzero vectors have `pdeg ≠ ⊥`).

* **Leading vectors.**  `lc₁ := lv d n₁ e₁`, `lc₂ := lv d n₂ e₂ ∈ K³` are nonzero (a slot attains
  the product-degree) and `K`-independent: were `lc₂ ∈ K·lc₁`, subtracting the matching monomial
  multiple of `e₁` would drop `pdeg e₂` below `δ₂` while staying outside `K[X]·e₁` — impossible by
  `δ₂`-minimality.

* **The exchange.**  For `w ∈ N`, `w ≠ 0`, put `D := pdeg w`.  If `w ∈ K[X]·e₁` reduce to `0`
  directly.  Otherwise `D ≥ δ₂`, and the leading vector `lv d D w` lies in `span_K{lc₁, lc₂}`:
  otherwise `{lc₁, lc₂, lv d D w}` would be `K`-independent, forcing `e₁, e₂, w` to be
  `K[X]`-independent (the top-degree cancellation: a `K[X]`-relation combines leading vectors with
  nonzero top coefficients, contradicting `K`-independence), i.e. `rank N ≥ 3 > 2`.  Cancelling the
  two leading terms with the monomial multiples `C c₁ · X^{D−n₁}·e₁`, `C c₂ · X^{D−n₂}·e₂` kills
  `lv d D` and hence drops `pdeg` below `D`.

## Scrupulous honesty — scope

This lands `GradedExchange` for **every** rank-`2` submodule of `K[X]³` (`exists_gradedExchange`),
hence for the syzygy kernel of a coprime triple (`syzygyKernel_gradedExchange`), and — chaining
SYZ62 — that the kernel **is generated by a degree-minimal pair** (`syzygyKernel_muBasis_span`).

It does **not** by itself close `SYZ60.MuBasisWindowIso` / `SYZ44.RankNullity`: those additionally
need the *windowed* finrank iso (injective + surjective on the degree windows), a further degree
bookkeeping layer on top of the span generation landed here.  So the graded exchange step — SYZ62's
last classical residual — is now **proved**, but the windowed-count iso and the degree-sum law
remain conditional on that separate bookkeeping.  This does **not** claim δ* closure.

Axiom-clean; `#print axioms` at the bottom.  No `sorry`, no `native_decide`.
-/

set_option autoImplicit false
set_option linter.style.longLine false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 1600000

open Module Polynomial
open ArkLib.ProximityGap.SYZ62
open scoped Cardinal

namespace ArkLib.ProximityGap.SYZ63

variable {K : Type*} [Field K]

/-! ## 0. Polynomial-coefficient helper: the top coefficient of a product -/

/-- **Top-coefficient of a product.**  For `q, p ≠ 0` and any `m ≥ deg p`, the coefficient of
`q · p` at degree `deg q + m` is `leadingCoeff q · coeff p m`.  At `m = deg p` this is the classical
`coeff_mul_degree_add_degree`; above it both sides vanish. -/
private theorem coeff_mul_top (q p : K[X]) {m : ℕ} (hq : q ≠ 0) (hp : p ≠ 0)
    (hm : p.natDegree ≤ m) :
    (q * p).coeff (q.natDegree + m) = q.leadingCoeff * p.coeff m := by
  rcases eq_or_lt_of_le hm with h | h
  · -- m = natDegree p : classical top-of-product
    have hlead : p.leadingCoeff = p.coeff m := by rw [← h]; rfl
    calc (q * p).coeff (q.natDegree + m)
        = (q * p).coeff (q.natDegree + p.natDegree) := by rw [h]
      _ = q.leadingCoeff * p.leadingCoeff := coeff_mul_degree_add_degree q p
      _ = q.leadingCoeff * p.coeff m := by rw [hlead]
  · -- m > natDegree p : both sides zero
    have hpc : p.coeff m = 0 := coeff_eq_zero_of_natDegree_lt h
    have hqp : (q * p).natDegree = q.natDegree + p.natDegree := natDegree_mul hq hp
    have hlt : (q * p).natDegree < q.natDegree + m := by rw [hqp]; omega
    rw [coeff_eq_zero_of_natDegree_lt hlt, hpc, mul_zero]

/-! ## 1. Grading facts specific to the exchange -/

variable {d : Fin 3 → ℕ}

/-- A nonzero vector has non-`⊥` product-degree. -/
theorem pdeg_ne_bot_of_ne_zero {w : Fin 3 → K[X]} (hw : w ≠ 0) : pdeg d w ≠ ⊥ := by
  intro hbot
  apply hw
  funext i
  have hle : pterm d w i ≤ (⊥ : WithBot ℕ) := hbot ▸ pterm_le_pdeg d w i
  have : pterm d w i = ⊥ := le_bot_iff.mp hle
  by_contra hwi
  simp only [pterm] at this
  rw [degree_eq_natDegree hwi, ← Nat.cast_add] at this
  simp at this

/-- If `w` attains product-degree `D`, some slot realises it, so the leading vector is nonzero. -/
theorem lv_ne_zero_of_pdeg_eq {w : Fin 3 → K[X]} {D : ℕ} (hw : pdeg d w = (D : WithBot ℕ)) :
    lv d D w ≠ 0 := by
  -- some slot attains the max
  have hmax : pterm d w 0 = pdeg d w ∨ pterm d w 1 = pdeg d w ∨ pterm d w 2 = pdeg d w := by
    simp only [pdeg]
    rcases max_choice (max (pterm d w 0) (pterm d w 1)) (pterm d w 2) with h | h
    · rcases max_choice (pterm d w 0) (pterm d w 1) with h' | h'
      · left; rw [h, h']
      · right; left; rw [h, h']
    · right; right; rw [h]
  intro hzero
  -- from lv = 0 : every attaining slot has coeff 0, contradicting attainment
  have key : ∀ i, pterm d w i = (D : WithBot ℕ) → False := by
    intro i hi
    have hwi : w i ≠ 0 := by
      intro h0
      simp [pterm, h0] at hi
    have hdeg : (w i).degree = ((w i).natDegree : WithBot ℕ) := degree_eq_natDegree hwi
    have hnd : (w i).natDegree + d i = D := by
      simp only [pterm, hdeg, ← Nat.cast_add] at hi
      exact Nat.cast_inj.mp hi
    have hcoeff : (w i).coeff (D - d i) = 0 := congrFun hzero i
    have : (w i).coeff (w i).natDegree = 0 := by
      have : D - d i = (w i).natDegree := by omega
      rwa [this] at hcoeff
    rw [← leadingCoeff] at this
    exact hwi (leadingCoeff_eq_zero.mp this)
  rcases hmax with h | h | h
  · exact key 0 (by rw [h, hw])
  · exact key 1 (by rw [h, hw])
  · exact key 2 (by rw [h, hw])

/-- **Detecting a degree drop.**  If `pdeg d w ≤ D` and the leading vector at `D` vanishes, then the
product-degree is strictly below `D`. -/
theorem pdeg_lt_of_lv_eq_zero {w : Fin 3 → K[X]} {D : ℕ}
    (hle : pdeg d w ≤ (D : WithBot ℕ)) (hlv : lv d D w = 0) : pdeg d w < (D : WithBot ℕ) := by
  rcases lt_or_eq_of_le hle with h | h
  · exact h
  · exact absurd hlv (lv_ne_zero_of_pdeg_eq h)

/-- Product-degree of a negated vector is unchanged. -/
theorem pdeg_neg (w : Fin 3 → K[X]) : pdeg d ((-1 : K[X]) • w) = pdeg d w := by
  rw [pdeg_smul]
  have : (-1 : K[X]).degree = 0 := by simp
  rw [this, zero_add]

/-- Subadditivity for subtraction. -/
theorem pdeg_sub_le (w w' : Fin 3 → K[X]) :
    pdeg d (w - w') ≤ max (pdeg d w) (pdeg d w') := by
  have : w - w' = w + (-1 : K[X]) • w' := by rw [neg_one_smul]; ring
  rw [this]
  refine le_trans (pdeg_add_le d _ _) ?_
  rw [pdeg_neg]

/-- **Leading vector under `K[X]`-scaling, at the top target degree.**  For `q ≠ 0` and `w` of
product-degree `D`, the leading vector of `q • w` at the shifted degree `deg q + D` is the leading
coefficient of `q` times the leading vector of `w`. -/
theorem lv_smul_top {w : Fin 3 → K[X]} {D : ℕ} (q : K[X]) (hq : q ≠ 0)
    (hw : pdeg d w = (D : WithBot ℕ)) :
    lv d (q.natDegree + D) (q • w) = q.leadingCoeff • lv d D w := by
  funext i
  simp only [lv, Pi.smul_apply, smul_eq_mul]
  -- slot bound: deg (w i) + d i ≤ D
  have hbound : pterm d w i ≤ (D : WithBot ℕ) := hw ▸ pterm_le_pdeg d w i
  rcases eq_or_ne (w i) 0 with hwi | hwi
  · simp [hwi]
  · have hdeg : (w i).degree = ((w i).natDegree : WithBot ℕ) := degree_eq_natDegree hwi
    have hnd : (w i).natDegree + d i ≤ D := by
      simp only [pterm, hdeg, ← Nat.cast_add] at hbound
      exact Nat.cast_le.mp hbound
    have hdi : d i ≤ D := by omega
    have hidx : q.natDegree + D - d i = q.natDegree + (D - d i) := by
      rw [Nat.add_sub_assoc hdi]
    have hmle : (w i).natDegree ≤ D - d i := by omega
    rw [hidx, coeff_mul_top q (w i) hq hwi hmle]

/-! ## 2. The abstract rank-2 exchange -/

section Abstract

variable {N : Submodule K[X] (Fin 3 → K[X])}

/-- **Independence descent.**  Three nonzero members of a rank-`2` submodule whose leading vectors
(at their own product-degrees) are `K`-independent cannot exist: they would be `K[X]`-independent,
forcing `rank N ≥ 3`. -/
theorem no_three_independent_lv (hrank : Module.rank K[X] N = 2)
    (u : Fin 3 → (Fin 3 → K[X])) (hu : ∀ i, u i ∈ N) (hune : ∀ i, u i ≠ 0)
    (Dn : Fin 3 → ℕ) (hD : ∀ i, pdeg d (u i) = (Dn i : WithBot ℕ))
    (hindep : LinearIndependent K (fun i => lv d (Dn i) (u i))) : False := by
  -- Build a K[X]-linearly independent family inside N, contradicting rank 2.
  set v : Fin 3 → N := fun i => ⟨u i, hu i⟩ with hv
  have hNindep : LinearIndependent K[X] v := by
    rw [Fintype.linearIndependent_iff]
    intro g hg
    -- push the N-relation to the ambient module
    have hamb : g 0 • u 0 + g 1 • u 1 + g 2 • u 2 = 0 := by
      have := congrArg (N.subtype) hg
      simpa [map_add, map_smul, hv, Fin.sum_univ_three] using this
    -- suppose some coefficient is nonzero; derive a K-relation among the (independent) lv's
    by_contra hnall
    push_neg at hnall
    obtain ⟨i₀, hi₀⟩ := hnall
    -- the per-term product-degrees
    set P : Fin 3 → WithBot ℕ := fun i => pdeg d (g i • u i) with hP
    -- P i = deg (g i) + Dn i
    have hPeq : ∀ i, P i = (g i).degree + (Dn i : WithBot ℕ) := by
      intro i; rw [hP]; simp only; rw [pdeg_smul, hD i]
    set M' : WithBot ℕ := max (max (P 0) (P 1)) (P 2) with hM'
    -- M' ≠ ⊥ : the i₀ term is nonzero
    have hu0ne : g i₀ • u i₀ ≠ 0 := by
      simp only [smul_ne_zero_iff]
      exact ⟨hi₀, hune i₀⟩
    have hPi0 : P i₀ ≠ ⊥ := pdeg_ne_bot_of_ne_zero hu0ne
    have hM'ne : M' ≠ ⊥ := by
      rw [hM']
      fin_cases i₀ <;> simp_all <;>
        first
          | (intro h; exact hPi0 (le_bot_iff.mp (h ▸ le_max_left _ _)))
          | (intro h; exact hPi0 (le_bot_iff.mp (h ▸ le_trans (le_max_right _ _) (le_max_left _ _))))
          | (intro h; exact hPi0 (le_bot_iff.mp (h ▸ le_max_right _ _)))
    obtain ⟨M, hM⟩ := WithBot.ne_bot_iff_exists.mp hM'ne
    rw [← Nat.cast_withBot] at hM
    -- each term's contribution to lv d M
    have hle : ∀ i, P i ≤ (M : WithBot ℕ) := by
      intro i
      rw [hM, hM']
      fin_cases i
      · exact le_trans (le_max_left _ _) (le_max_left _ _)
      · exact le_trans (le_max_right _ _) (le_max_left _ _)
      · exact le_max_right _ _
    -- γ i : the leading coefficient when the term attains M, else 0
    set γ : Fin 3 → K := fun i => if P i = (M : WithBot ℕ) then (g i).leadingCoeff else 0 with hγ
    -- lv d M of each term equals γ i • (lv d (Dn i) (u i))
    have hterm : ∀ i, lv d M (g i • u i) = γ i • lv d (Dn i) (u i) := by
      intro i
      by_cases hcase : P i = (M : WithBot ℕ)
      · -- attaining: use lv_smul_top
        have hgi : g i ≠ 0 := by
          intro h0
          rw [hP] at hcase
          simp [h0, pdeg_zero] at hcase
        have hMval : (g i).natDegree + Dn i = M := by
          have := hPeq i
          rw [hcase] at this
          rw [degree_eq_natDegree hgi, ← Nat.cast_add] at this
          exact (Nat.cast_inj.mp this.symm)
        rw [hγ]; simp only [hcase, if_true]
        rw [← hMval, lv_smul_top (q := g i) hgi (hD i)]
      · -- not attaining: term's lv vanishes
        have hlt : P i < (M : WithBot ℕ) := lt_of_le_of_ne (hle i) hcase
        rw [hγ]; simp only [hcase, if_false, zero_smul]
        exact lv_eq_zero_of_pdeg_lt d M (g i • u i) hlt
    -- sum the contributions: 0 = Σ γ i • lv
    have hsum0 : γ 0 • lv d (Dn 0) (u 0) + γ 1 • lv d (Dn 1) (u 1)
        + γ 2 • lv d (Dn 2) (u 2) = 0 := by
      have h0 : lv d M (g 0 • u 0 + g 1 • u 1 + g 2 • u 2) = 0 := by
        rw [hamb]; funext i; simp [lv]
      rw [lv_add, lv_add] at h0
      rw [hterm 0, hterm 1, hterm 2] at h0
      exact h0
    -- independence forces all γ = 0
    have hγ0 : ∀ i, γ i = 0 := by
      have := Fintype.linearIndependent_iff.mp hindep γ
      apply this
      rw [Fin.sum_univ_three]; exact hsum0
    -- but the attaining index i₁ has γ i₁ = leadingCoeff ≠ 0
    have hattain : ∃ i, P i = (M : WithBot ℕ) := by
      have hchoice : M' = P 0 ∨ M' = P 1 ∨ M' = P 2 := by
        rw [hM']
        rcases max_choice (max (P 0) (P 1)) (P 2) with h | h
        · rcases max_choice (P 0) (P 1) with h' | h'
          · left; rw [h, h']
          · right; left; rw [h, h']
        · right; right; rw [h]
      rcases hchoice with h | h | h
      · exact ⟨0, by rw [hM]; exact h.symm⟩
      · exact ⟨1, by rw [hM]; exact h.symm⟩
      · exact ⟨2, by rw [hM]; exact h.symm⟩
    obtain ⟨i₁, hi₁⟩ := hattain
    have hgi₁ : g i₁ ≠ 0 := by
      intro h0
      rw [hP] at hi₁
      simp [h0, pdeg_zero] at hi₁
    have : γ i₁ = (g i₁).leadingCoeff := by rw [hγ]; simp [hi₁]
    have hlead : (g i₁).leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hgi₁
    exact hlead (by rw [← this]; exact hγ0 i₁)
  -- rank contradiction
  have hcard : ((3 : ℕ) : Cardinal) ≤ Module.rank K[X] (N : Submodule K[X] _) :=
    le_rank_iff.mpr ⟨v, hNindep⟩
  rw [hrank] at hcard
  norm_num at hcard

end Abstract

/-! ## 3. The exchange step, discharged -/

/-- **The graded exchange step, unconditional.**  Every rank-`2` submodule `N ⊆ K[X]³` has a pair
of members `e₁, e₂` satisfying `GradedExchange`, for any weight vector `d`. -/
theorem exists_gradedExchange (d : Fin 3 → ℕ) (N : Submodule K[X] (Fin 3 → K[X]))
    (hrank : Module.rank K[X] N = 2) :
    ∃ e₁ ∈ N, ∃ e₂ ∈ N, GradedExchange (d := d) N e₁ e₂ := by
  -- N ≠ ⊥ (rank 2 ≠ 0)
  have hNbot : N ≠ ⊥ := by
    intro h; rw [h] at hrank; simp [rank_bot] at hrank
  obtain ⟨x₀, hx₀N, hx₀ne⟩ := (Submodule.ne_bot_iff N).mp hNbot
  -- well-foundedness of < on WithBot ℕ
  have hwf : WellFounded ((· < ·) : WithBot ℕ → WithBot ℕ → Prop) := wellFounded_lt
  -- (1) minimal nonzero e₁
  set S₁ : Set (WithBot ℕ) := (fun w => pdeg d w) '' {w | w ∈ N ∧ w ≠ 0} with hS₁
  have hS₁ne : S₁.Nonempty := ⟨pdeg d x₀, x₀, ⟨hx₀N, hx₀ne⟩, rfl⟩
  obtain ⟨v₁, hv₁S, hv₁min⟩ := hwf.has_min S₁ hS₁ne
  obtain ⟨e₁, ⟨he₁N, he₁ne⟩, he₁pd⟩ := hv₁S
  have hmin₁ : ∀ w ∈ N, w ≠ 0 → v₁ ≤ pdeg d w := by
    intro w hwN hwne
    by_contra hlt
    push_neg at hlt
    exact hv₁min (pdeg d w) ⟨w, ⟨hwN, hwne⟩, rfl⟩ hlt
  -- span{e₁} ≠ N, giving a witness outside
  have hexists₂ : ∃ w ∈ N, w ∉ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X])) := by
    by_contra hall
    push_neg at hall
    have hle : N ≤ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X])) := hall
    have h1 : Module.rank K[X] (N : Submodule K[X] _)
        ≤ Module.rank K[X] (Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X]))) :=
      Submodule.rank_mono (R := K[X]) hle
    have h2 : Module.rank K[X] (Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X]))) ≤ 1 := by
      have hh := rank_span_le (R := K[X]) ({e₁} : Set (Fin 3 → K[X]))
      rwa [Cardinal.mk_singleton] at hh
    rw [hrank] at h1
    exact absurd (le_trans h1 h2) (by norm_num)
  -- (2) minimal e₂ outside span{e₁}
  set S₂ : Set (WithBot ℕ) :=
    (fun w => pdeg d w) '' {w | w ∈ N ∧ w ∉ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X]))} with hS₂
  have hS₂ne : S₂.Nonempty := by
    obtain ⟨w, hwN, hwout⟩ := hexists₂
    exact ⟨pdeg d w, w, ⟨hwN, hwout⟩, rfl⟩
  obtain ⟨v₂, hv₂S, hv₂min⟩ := hwf.has_min S₂ hS₂ne
  obtain ⟨e₂, ⟨he₂N, he₂out⟩, he₂pd⟩ := hv₂S
  have he₂ne : e₂ ≠ 0 := by
    intro h0; apply he₂out; rw [h0]; exact Submodule.zero_mem _
  have hmin₂ : ∀ w ∈ N, w ∉ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X])) → v₂ ≤ pdeg d w := by
    intro w hwN hwout
    by_contra hlt
    push_neg at hlt
    exact hv₂min (pdeg d w) ⟨w, ⟨hwN, hwout⟩, rfl⟩ hlt
  -- extract naturals n₁ ≤ n₂
  have hv₁ne : v₁ ≠ ⊥ := by rw [← he₁pd]; exact pdeg_ne_bot_of_ne_zero he₁ne
  have hv₂ne : v₂ ≠ ⊥ := by rw [← he₂pd]; exact pdeg_ne_bot_of_ne_zero he₂ne
  obtain ⟨n₁, hn₁⟩ := WithBot.ne_bot_iff_exists.mp hv₁ne
  obtain ⟨n₂, hn₂⟩ := WithBot.ne_bot_iff_exists.mp hv₂ne
  have hv₁eq : v₁ = (n₁ : WithBot ℕ) := hn₁.symm
  have hv₂eq : v₂ = (n₂ : WithBot ℕ) := hn₂.symm
  have hpd₁ : pdeg d e₁ = (n₁ : WithBot ℕ) := he₁pd.trans hv₁eq
  have hpd₂ : pdeg d e₂ = (n₂ : WithBot ℕ) := he₂pd.trans hv₂eq
  have hn₁₂ : n₁ ≤ n₂ := by
    have hle : v₁ ≤ pdeg d e₂ := hmin₁ e₂ he₂N he₂ne
    rw [hv₁eq, hpd₂] at hle
    exact Nat.cast_le.mp hle
  -- leading vectors
  set lc₁ : Fin 3 → K := lv d n₁ e₁ with hlc₁
  set lc₂ : Fin 3 → K := lv d n₂ e₂ with hlc₂
  have hlc₁ne : lc₁ ≠ 0 := lv_ne_zero_of_pdeg_eq hpd₁
  have hlc₂ne : lc₂ ≠ 0 := lv_ne_zero_of_pdeg_eq hpd₂
  -- lc₂ ∉ K·lc₁  (else δ₂ minimality is violated)
  have hnotprop : ∀ c : K, c • lc₁ ≠ lc₂ := by
    intro c hc
    -- q = C c * X^(n₂ - n₁)
    set q : K[X] := C c * X ^ (n₂ - n₁) with hq
    -- e₂' = e₂ - q • e₁  is in N, outside span{e₁}, with pdeg < n₂
    have hcne : c ≠ 0 := by
      rintro rfl; simp only [zero_smul] at hc; exact hlc₂ne hc.symm
    have hqne : q ≠ 0 := by
      rw [hq]; exact mul_ne_zero (by simpa using hcne) (pow_ne_zero _ X_ne_zero)
    have hqnd : q.natDegree = n₂ - n₁ := by
      rw [hq, natDegree_C_mul (by simpa using hcne), natDegree_X_pow]
    have hqlead : q.leadingCoeff = c := by
      rw [hq]; rw [leadingCoeff_mul, leadingCoeff_X_pow, mul_one, leadingCoeff_C]
    -- pdeg (q • e₁) = n₂
    have hpdq : pdeg d (q • e₁) = (n₂ : WithBot ℕ) := by
      rw [pdeg_smul, hpd₁, degree_eq_natDegree hqne, hqnd, ← Nat.cast_add]
      congr 1; omega
    -- lv d n₂ (q • e₁) = c • lc₁
    have hlvq : lv d n₂ (q • e₁) = c • lc₁ := by
      have := lv_smul_top (q := q) hqne hpd₁
      rw [hqnd] at this
      have hidx : n₂ - n₁ + n₁ = n₂ := by omega
      rw [hidx] at this
      rw [this, hqlead, hlc₁]
    set e₂' : Fin 3 → K[X] := e₂ - q • e₁ with he₂'
    have he₂'N : e₂' ∈ N := N.sub_mem he₂N (N.smul_mem _ he₁N)
    have he₂'out : e₂' ∉ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X])) := by
      intro hmem
      apply he₂out
      have : e₂ = e₂' + q • e₁ := by rw [he₂']; ring
      rw [this]
      exact Submodule.add_mem _ hmem (Submodule.smul_mem _ _ (Submodule.subset_span (by simp)))
    -- lv d n₂ e₂' = lc₂ - c • lc₁ = 0
    have hlv0 : lv d n₂ e₂' = 0 := by
      rw [he₂', show e₂ - q • e₁ = e₂ + (-1 : K) • (q • e₁) by rw [neg_one_smul]; ring]
      rw [lv_add, lv_smulK, hlvq, ← hlc₂]
      rw [← hc]
      simp
    have hpdle : pdeg d e₂' ≤ (n₂ : WithBot ℕ) := by
      rw [he₂']
      calc pdeg d (e₂ - q • e₁) = pdeg d (e₂ + (-1 : K[X]) • (q • e₁)) := by
              congr 1; rw [neg_one_smul]; ring
        _ ≤ max (pdeg d e₂) (pdeg d ((-1 : K[X]) • (q • e₁))) := pdeg_add_le d _ _
        _ ≤ (n₂ : WithBot ℕ) := by
              apply max_le
              · rw [hpd₂]
              · rw [pdeg_smul, hpdq]; simp
    have hdrop : pdeg d e₂' < (n₂ : WithBot ℕ) := pdeg_lt_of_lv_eq_zero hpdle hlv0
    -- contradicts δ₂ minimality
    have hge := hmin₂ e₂' he₂'N he₂'out
    rw [hv₂eq] at hge
    exact absurd (lt_of_le_of_lt hge hdrop) (lt_irrefl _)
  -- lc₁, lc₂ are K-independent
  have hpair : LinearIndependent K ![lc₁, lc₂] := by
    rw [LinearIndependent.pair_iff]
    intro s t hst
    rcases eq_or_ne t 0 with ht | ht
    · subst ht
      simp only [zero_smul, add_zero] at hst
      have : s = 0 := by
        rcases eq_or_ne s 0 with h | h
        · exact h
        · exact absurd ((smul_eq_zero.mp hst).resolve_left h) hlc₁ne
      exact ⟨this, rfl⟩
    · exfalso
      apply hnotprop (-(t⁻¹ * s))
      have hts : t • lc₂ = -(s • lc₁) := eq_neg_of_add_eq_zero_right hst
      have h1 : (-(t⁻¹ * s)) • lc₁ = t⁻¹ • (-(s • lc₁)) := by
        rw [neg_smul, mul_smul, ← smul_neg]
      rw [h1, ← hts, smul_smul, inv_mul_cancel₀ ht, one_smul]
  -- Assemble GradedExchange
  refine ⟨e₁, he₁N, e₂, he₂N, ?_⟩
  intro w hwN hwne
  by_cases hwspan : w ∈ Submodule.span K[X] ({e₁} : Set (Fin 3 → K[X]))
  · -- w = a • e₁ : reduce fully to 0
    rw [Submodule.mem_span_singleton] at hwspan
    obtain ⟨a, ha⟩ := hwspan
    refine ⟨a, 0, ?_⟩
    rw [zero_smul, add_zero, ha, sub_self, pdeg_zero]
    exact bot_lt_iff_ne_bot.mpr (pdeg_ne_bot_of_ne_zero hwne)
  · -- w ∉ span{e₁} : D := pdeg w ≥ n₂
    obtain ⟨Dn, hDn⟩ := WithBot.ne_bot_iff_exists.mp (pdeg_ne_bot_of_ne_zero hwne)
    rw [← Nat.cast_withBot] at hDn
    have hpdw : pdeg d w = (Dn : WithBot ℕ) := hDn.symm
    have hD₂ : n₂ ≤ Dn := by
      have hge := hmin₂ w hwN hwspan
      rw [hv₂eq, hpdw] at hge
      exact Nat.cast_le.mp hge
    have hD₁ : n₁ ≤ Dn := le_trans hn₁₂ hD₂
    -- span claim: lv d Dn w ∈ span_K {lc₁, lc₂}
    have hspan : ∃ c₁ c₂ : K, c₁ • lc₁ + c₂ • lc₂ = lv d Dn w := by
      by_contra hno
      push_neg at hno
      -- ![lc₁, lc₂, lv d Dn w] is K-independent
      have htriple : LinearIndependent K (fun i => lv d (![n₁, n₂, Dn] i) (![e₁, e₂, w] i)) := by
        rw [Fintype.linearIndependent_iff]
        intro g hg
        rw [Fin.sum_univ_three] at hg
        simp only [Matrix.cons_val_zero, Matrix.cons_val_one, Matrix.head_cons,
          Matrix.cons_val_two, Matrix.tail_cons] at hg
        -- g 0 • lc₁ + g 1 • lc₂ + g 2 • lv d Dn w = 0
        have hg' : g 0 • lc₁ + g 1 • lc₂ + g 2 • lv d Dn w = 0 := by
          rw [hlc₁, hlc₂]; exact hg
        rcases eq_or_ne (g 2) 0 with h2 | h2
        · rw [h2, zero_smul, add_zero] at hg'
          have := (LinearIndependent.pair_iff.mp hpair) (g 0) (g 1) hg'
          intro i; fin_cases i
          · exact this.1
          · exact this.2
          · exact h2
        · exfalso
          apply hno (-(g 2)⁻¹ * g 0) (-(g 2)⁻¹ * g 1)
          have hiso : g 2 • lv d Dn w = -(g 0 • lc₁ + g 1 • lc₂) :=
            eq_neg_of_add_eq_zero_right hg'
          have : lv d Dn w = (g 2)⁻¹ • (-(g 0 • lc₁ + g 1 • lc₂)) := by
            rw [← hiso, smul_smul, inv_mul_cancel₀ h2, one_smul]
          rw [this]; module
      -- contradiction with rank 2
      exact no_three_independent_lv hrank ![e₁, e₂, w]
        (by intro i; fin_cases i <;> simpa using ‹_›)
        (by intro i; fin_cases i <;> simp_all)
        ![n₁, n₂, Dn]
        (by intro i; fin_cases i <;> simp_all)
        htriple
    -- cancel the two leading terms
    obtain ⟨c₁, c₂, hc⟩ := hspan
    set q₁ : K[X] := C c₁ * X ^ (Dn - n₁) with hq₁
    set q₂ : K[X] := C c₂ * X ^ (Dn - n₂) with hq₂
    refine ⟨q₁, q₂, ?_⟩
    set r : Fin 3 → K[X] := w - (q₁ • e₁ + q₂ • e₂) with hr
    -- lv d Dn (qⱼ • eⱼ) = cⱼ • lcⱼ  (or 0)
    have hlvq : ∀ (c : K) (nⱼ : ℕ) (eⱼ : Fin 3 → K[X]),
        n₁ ≤ Dn → pdeg d eⱼ = (nⱼ : WithBot ℕ) → nⱼ ≤ Dn →
        lv d Dn ((C c * X ^ (Dn - nⱼ)) • eⱼ) = c • lv d nⱼ eⱼ := by
      intro c nⱼ eⱼ _ hpdⱼ hnⱼ
      rcases eq_or_ne c 0 with hc0 | hc0
      · subst hc0; simp only [map_zero, zero_mul, zero_smul]; funext i; simp [lv]
      · set qc : K[X] := C c * X ^ (Dn - nⱼ) with hqc
        have hqcne : qc ≠ 0 := mul_ne_zero (by simpa using hc0) (pow_ne_zero _ X_ne_zero)
        have hqcnd : qc.natDegree = Dn - nⱼ := by
          rw [hqc, natDegree_C_mul (by simpa using hc0), natDegree_X_pow]
        have hqclead : qc.leadingCoeff = c := by
          rw [hqc, leadingCoeff_mul, leadingCoeff_X_pow, mul_one, leadingCoeff_C]
        have := lv_smul_top (q := qc) hqcne hpdⱼ
        rw [hqcnd] at this
        have hidx : Dn - nⱼ + nⱼ = Dn := by omega
        rw [hidx] at this
        rw [this, hqclead]
    have hlvq₁ : lv d Dn (q₁ • e₁) = c₁ • lc₁ := by
      rw [hq₁, hlvq c₁ n₁ e₁ hD₁ hpd₁ hD₁, hlc₁]
    have hlvq₂ : lv d Dn (q₂ • e₂) = c₂ • lc₂ := by
      rw [hq₂, hlvq c₂ n₂ e₂ hD₁ hpd₂ hD₂, hlc₂]
    -- lv d Dn r = 0
    have hlvr : lv d Dn r = 0 := by
      rw [hr, show w - (q₁ • e₁ + q₂ • e₂)
            = w + (-1 : K) • (q₁ • e₁) + (-1 : K) • (q₂ • e₂) by
              rw [neg_one_smul, neg_one_smul]; ring]
      rw [lv_add, lv_add, lv_smulK, lv_smulK, hlvq₁, hlvq₂, ← hc]
      module
    -- pdeg (qⱼ • eⱼ) ≤ Dn
    have hpdqle : ∀ (c : K) (nⱼ : ℕ) (eⱼ : Fin 3 → K[X]),
        pdeg d eⱼ = (nⱼ : WithBot ℕ) → nⱼ ≤ Dn →
        pdeg d ((C c * X ^ (Dn - nⱼ)) • eⱼ) ≤ (Dn : WithBot ℕ) := by
      intro c nⱼ eⱼ hpdⱼ hnⱼ
      rw [pdeg_smul, hpdⱼ]
      rcases eq_or_ne c 0 with hc0 | hc0
      · subst hc0; simp
      · have hqcne : (C c * X ^ (Dn - nⱼ)) ≠ 0 :=
          mul_ne_zero (by simpa using hc0) (pow_ne_zero _ X_ne_zero)
        have hnd : (C c * X ^ (Dn - nⱼ)).natDegree = Dn - nⱼ := by
          rw [natDegree_C_mul (by simpa using hc0), natDegree_X_pow]
        rw [degree_eq_natDegree hqcne, hnd, ← Nat.cast_add, Nat.cast_le]
        omega
    -- pdeg r ≤ Dn
    have hpdle : pdeg d r ≤ (Dn : WithBot ℕ) := by
      rw [hr]
      refine le_trans (pdeg_sub_le (d := d) _ _) (max_le ?_ ?_)
      · exact le_of_eq hpdw
      · refine le_trans (pdeg_add_le d _ _) (max_le ?_ ?_)
        · rw [hq₁]; exact hpdqle c₁ n₁ e₁ hpd₁ hD₁
        · rw [hq₂]; exact hpdqle c₂ n₂ e₂ hpd₂ hD₂
    rw [hpdw]
    exact pdeg_lt_of_lv_eq_zero hpdle hlvr

/-! ## 4. Specialization to the syzygy kernel -/

/-- **The graded exchange step for the syzygy kernel of a coprime triple.**  Discharges SYZ62's
`GradedExchange` residual unconditionally, from the rank-`2` structure of SYZ61. -/
theorem syzygyKernel_gradedExchange (d : Fin 3 → ℕ) {f g h : K[X]}
    (hfg : IsCoprime f g) (hfh : IsCoprime f h) :
    ∃ e₁ ∈ LinearMap.ker (SYZ61.syzygyMap f g h),
      ∃ e₂ ∈ LinearMap.ker (SYZ61.syzygyMap f g h),
        GradedExchange (d := d) (LinearMap.ker (SYZ61.syzygyMap f g h)) e₁ e₂ :=
  exists_gradedExchange d _ (SYZ61.rank_syzygyKernel hfg hfh)

/-- **The syzygy kernel is generated by a degree-minimal pair — unconditional.**  Chaining SYZ62's
`syzygyKernel_eq_span_of_gradedExchange` with the discharged exchange step: the kernel of a coprime
triple is the `K[X]`-span of a degree-minimal (μ-)basis, with no remaining `GradedExchange`
hypothesis. -/
theorem syzygyKernel_muBasis_span (d : Fin 3 → ℕ) {f g h : K[X]}
    (hfg : IsCoprime f g) (hfh : IsCoprime f h) :
    ∃ e₁ e₂ : Fin 3 → K[X],
      LinearMap.ker (SYZ61.syzygyMap f g h)
        = Submodule.span K[X] ({e₁, e₂} : Set (Fin 3 → K[X])) := by
  obtain ⟨e₁, he₁, e₂, he₂, hex⟩ := syzygyKernel_gradedExchange d hfg hfh
  exact ⟨e₁, e₂, SYZ62.syzygyKernel_eq_span_of_gradedExchange he₁ he₂ hex⟩

end ArkLib.ProximityGap.SYZ63

/-! ## Axiom audit -/

#print axioms ArkLib.ProximityGap.SYZ63.lv_smul_top
#print axioms ArkLib.ProximityGap.SYZ63.no_three_independent_lv
#print axioms ArkLib.ProximityGap.SYZ63.exists_gradedExchange
#print axioms ArkLib.ProximityGap.SYZ63.syzygyKernel_gradedExchange
#print axioms ArkLib.ProximityGap.SYZ63.syzygyKernel_muBasis_span
