/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._PrizeShapePrimeP30
import ArkLib.Data.CodingTheory.ProximityGap.Frontier._RankOneTensorProjectiveInjection

/-!
# W7 seal: the 186 scalar evaluation facts of the rate-half three-core base certificate

`docs/kb/deltastar-466-rate-half-three-core-radix-counterexample-2026-07-10.md` reduces the
base separation of the three-core radix counterexample to 186 scalar facts: for each of the
93 external-defect directions, the exact row-reduced representative is nonzero at coordinate 6
and its coordinate-15/coordinate-6 ratio equals the published fingerprint.

This file discharges all 186 facts by kernel computation and composes them with the
(restated) chart lemmas of `Frontier/_RateHalfBaseFingerprintTable.lean` into
hypothesis-free projective-separation theorems for the concrete direction family.

Definitional shape (mirrors `scripts/probes/probe_rate_half_three_core_radix_counterexample.py`,
regenerated and re-verified by `scripts/probes/probe_w7_emit_fingerprint_lemmas.py`):

* `dom i` — the 64 points of `mu_64` inside the certified field, as natural residues;
* `defectN c out coord` — the external interpolation defect of core `c` at evaluation
  point `out`, coordinate `coord` (Lagrange formula on the 32-point interpolation basis);
* `rowTab` — the reduced row echelon form (pivots 0,1,2) of the three 33-point parity
  checks, i.e. the canonical basis of the annihilator used for row reduction;
* `directionNat i` — the canonical reduced representative of the `i`-th defect:
  `defect - defect[0]*row0 - defect[1]*row1 - defect[2]*row2`;
* `direction i` — the same family in `ZMod P`.

All arithmetic is `Nat`-mod arithmetic with a proved cast bridge to `ZMod P`, following the
`binaryPow` precedent of `_PrizeShapePrimeP30.lean`.  This file is deliberately
self-contained (it does not import the in-flight table file); its `fingerprintNat` is
literal-identical to `_RateHalfBaseFingerprintTable.fingerprintNat`, so the final splice can
identify the two by `rfl`.

Generated by `scripts/probes/probe_w7_emit_fingerprint_lemmas.py --emit-lean`.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 4000000

namespace ArkLib.ProximityGap.Frontier.W7RateHalfFingerprintSeal

open ArkLib.ProximityGap.PrizeShapePrimeP30

/-! ## Data tables (verified against the executable probe) -/

/-- The 64 points of `mu_64` (powers of `g^(2^24)`), as natural residues.
Verified below (`dom_spec`) to be the powers of the certified generator. -/
def domList : List Nat := [
    1,
    321066668146402433440778728016715546214271526818,
    60616617640587399731238504649262561904952465870,
    123727080781006193763170998591753013078275202333,
    357111556877444407914257742635116754287240874648,
    163037564022491890662650184594034462089571475672,
    180302925007710129500740201843249687412807954972,
    206803494027859418451314723399405770624818811392,
    18943363311336672863882327061011457227257409586,
    94433394601357961600764487285907972477705738088,
    230652020692776982540211547301654915686642604297,
    22463590154682192035157368102590270869344099052,
    5432565771502941682267434416927491076554553408,
    230569489483889856817835856555427008954037899891,
    173801114578312560973488816740838087830934792494,
    139430348106837550333670365636953079222317959892,
    125829621549097067457234094028236226857884909488,
    207938506821888563856516729408600781869316076888,
    282656783672639442256183087460876628125524873454,
    24785212891906941409212651148545924505048172099,
    330615295793966429274619141634401517550009310623,
    284966171637437540689403051988823694424323178303,
    139766967446474405906618613814689071480855463340,
    312340703059359479572634071101532688503561221932,
    21013949898147473983537680665153842593321561442,
    350850172524867305949053369713275306327463241492,
    67277701860843575759477541221165560025453218326,
    348454398940572651475270161942887388546490744145,
    312537465479665851940571453204847113794250060034,
    337459159582592257937740223199452220342178896782,
    166292514101872441565810142390472415201609924274,
    91816159347804290385485657470462022439142889128,
    365375409332725729550921208179070755120141565952,
    44308741186323296110142480162355208905870039135,
    304758791692138329819682703529808193215189100083,
    241648328551719535787750209587317742041866363620,
    8263852455281321636663465543954000832900691305,
    202337845310233838888271023585036293030570090281,
    185072484325015600050181006335821067707333610981,
    158571915304866311099606484779664984495322754561,
    346432046021389056687038881118059297892884156367,
    270942014731367767950156720893162782642435827865,
    134723388639948747010709660877415839433498961656,
    342911819178043537515763840076480484250797466901,
    359942843561222787868653773762143264043587012545,
    134805919848835872733085351623643746166103666062,
    191574294754413168577432391438232667289206773459,
    225945061225888179217250842542117675897823606061,
    239545787783628662093687114150834528262256656465,
    157436902510837165694404478770469973250825489065,
    82718625660086287294738120718194126994616692499,
    340590196440818788141708557030524830615093393854,
    34760113538759300276302066544669237570132255330,
    80409237695288188861518156190247060695818387650,
    225608441886251323644302594364381683639286102613,
    53034706273366249978287137077538066616580344021,
    344361459434578255567383527513916912526820004511,
    14525236807858423601867838465795448792678324461,
    298097707471882153791443666957905195094688347627,
    16921010392153078075651046236183366573650821808,
    52837943853059877610349754974223641325891505919,
    27916249750133471613180984979618534777962669171,
    199082895230853287985111065788598339918531641679,
    273559249984921439165435550708608732680998676825]

/-- Interpolation basis of core 0: the 32 smallest core coordinates. -/
def basis0 : List Nat :=
  [0, 2, 4, 6, 8, 9, 11, 14, 15, 16, 22, 23, 24, 25, 26, 28, 29, 31, 32, 33, 34, 36, 37, 38, 42, 44, 48, 49, 50, 55, 56, 57]

/-- Interpolation basis of core 1: the 32 smallest core coordinates. -/
def basis1 : List Nat :=
  [1, 3, 5, 6, 8, 10, 13, 15, 17, 18, 19, 21, 22, 23, 26, 27, 28, 30, 32, 35, 36, 42, 46, 48, 53, 55, 56, 57, 58, 59, 60, 62]

/-- Interpolation basis of core 2: the 32 smallest core coordinates. -/
def basis2 : List Nat :=
  [2, 6, 9, 11, 14, 15, 16, 18, 19, 20, 22, 25, 26, 27, 28, 29, 30, 32, 35, 36, 37, 38, 45, 46, 48, 49, 51, 53, 56, 57, 58, 60]

def basis : Fin 3 -> List Nat := ![basis0, basis1, basis2]

/-- The 31 out-of-core coordinates of core 0, ascending. -/
def outside0 : Fin 31 -> Nat :=
  ![1, 3, 5, 7, 10, 12, 13, 17, 18, 19, 20, 21, 27, 30, 35, 39, 40, 41, 43, 45, 46, 47, 51, 52, 53, 54, 59, 60, 61, 62, 63]

/-- The 31 out-of-core coordinates of core 1, ascending. -/
def outside1 : Fin 31 -> Nat :=
  ![0, 2, 4, 7, 9, 11, 12, 14, 16, 20, 24, 25, 29, 31, 33, 34, 37, 38, 39, 40, 41, 43, 44, 45, 47, 49, 50, 51, 52, 54, 61]

/-- The 31 out-of-core coordinates of core 2, ascending. -/
def outside2 : Fin 31 -> Nat :=
  ![0, 1, 3, 4, 5, 7, 8, 10, 12, 13, 17, 21, 23, 24, 31, 33, 34, 39, 40, 41, 42, 43, 44, 47, 50, 52, 54, 55, 59, 62, 63]

def outside : Fin 3 -> Fin 31 -> Nat := ![outside0, outside1, outside2]

/-- Row 0 of the reduced row echelon form of the three parity checks
(pivots at columns 0,1,2). -/
def row0 : Fin 64 -> Nat := ![
    1,
    0,
    0,
    0,
    58321627912346206918606479398294951345523034605,
    0,
    240972375945632963342224903776639644690796586856,
    0,
    243949883998755798396994763884076450824201376843,
    113794499926558988274435909501961333798270779608,
    0,
    324198878790508486318562406516403852813699886310,
    0,
    0,
    163052030195340477430021517522616234698471928900,
    268601307306210571600803297347436836967476343200,
    183079019450379786537161988993596164100841621821,
    0,
    240463095494319716041840289465343279832884334799,
    275139116786348232446777354274324654677782706492,
    265958314726541150149310058331318571763497362180,
    0,
    289013168566546914197607925568456072965237097756,
    90612684652808256762208848855968631817283847123,
    6342647726575018787874764782916588718083252712,
    76489623194527533235547312014076791914757591094,
    216771238196855066158057873287908967122167976277,
    143424193477091565373539144475886048010446998985,
    161524942701710142595480608411484214403418952329,
    16279557856551525516947086995913588707102577016,
    52917766149631546364837184169578702379048726514,
    1529266149868212107379067398235586776287270601,
    61745831853719623685442199352726641719724049161,
    158014590519845501114436728604943989256578824666,
    191724923515417388623263837769055723320189828664,
    159940518624705105730872340885884894320642488948,
    69068189067272009394702879872129214707753046159,
    224600005810898321419664864731934554662703712217,
    147536976122145278434337923587724615541405886345,
    0,
    0,
    0,
    225069921046687447565498674131213861020912299875,
    0,
    47681052421008125591743671195299934384996098724,
    63420174537833187084674647793816712212404111348,
    95949716047614501036115590290993073258386761688,
    0,
    141145961822858032096670721196249285076863023177,
    150222536302213719815598836093781590330614949983,
    227382310412279671600813789418117446703337801150,
    76362499708484793262211712934821833244577961629,
    0,
    62117423789741659719984523742505659374327966756,
    0,
    103564625652511783273033341983285781216093218805,
    118152882938613097887503690467915291111718755461,
    4520301202065964842753128924170916687250762374,
    314570952455464529964885312079272052743624251446,
    0,
    212888410120129329991050852150149906884321385416,
    288642324812445901225103695044843446056840751140,
    0,
    0]

/-- Row 1 of the reduced row echelon form of the three parity checks
(pivots at columns 0,1,2). -/
def row1 : Fin 64 -> Nat := ![
    0,
    1,
    0,
    304188521992130468930198416467426668735344653453,
    0,
    261566528356564461362794375315591160902870407367,
    83135197273689243477588137888062899021486972753,
    0,
    8919785961339591321460319999721670698057055844,
    0,
    346710239451633087035300417501105979811071702380,
    0,
    0,
    239450416748601540322158319270553086638898705730,
    0,
    228003850430197349733176828707999312919007092681,
    0,
    203510624742928700256078552763439566962990271759,
    33828044647646302477859473640644901969253341023,
    191857101487254843468422548160146248880321540311,
    0,
    88223243312656861745222291420846403390997975574,
    160996925683514293611105374349777604380773982896,
    45071491019230541311373912204457121993647310893,
    0,
    0,
    342568906881295926039020913683463721612177518928,
    264492110708898020458960489303478215324542086853,
    186503760979962831911895128899080053353338689152,
    0,
    124629064883613338933453332121085920452739719785,
    0,
    56926116939695966969396924561728353033716147810,
    0,
    0,
    49499967482871869187340556874787378314137190449,
    137739372226110856687436498196557657390612844822,
    0,
    0,
    0,
    0,
    0,
    10200555412266824380308202842081130664480089068,
    0,
    0,
    0,
    144864793164948540022457935860877836472393136654,
    0,
    307693257651108420435707462565621375341075449679,
    0,
    0,
    0,
    0,
    4344348669071452743640510329594428666994664889,
    0,
    137394798595924917800831077235630427341622368347,
    228758758182845432790958519077147738616115737114,
    102481183957313187978369461266525439915866149367,
    131120161558291483502344653383501364696829717447,
    30884861158052061358655919897520911014828479468,
    99692575479323093827397170789592802258233081820,
    0,
    227444442548245261566410040988200499859644119796,
    332554723070933442065573148940742691047913719229]

/-- Row 2 of the reduced row echelon form of the three parity checks
(pivots at columns 0,1,2). -/
def row2 : Fin 64 -> Nat := ![
    0,
    0,
    1,
    0,
    0,
    0,
    63491388653432640767466837058092486385509547035,
    0,
    0,
    363040609698121606723825268970460297305722938103,
    0,
    120381452253255851116125949253562302779062399662,
    0,
    0,
    246498449458618357754591268889908910102259701113,
    337296824443171766836803838974401544918005647694,
    304533319214977115315275271830295941534250036995,
    0,
    16296142269181019568242010947571815869160981486,
    98276155094773910256919055464485166788435240910,
    333879151905152364805282957291016387181760007863,
    0,
    279369755275071446840868004165386081173358609276,
    0,
    0,
    306412119179805901353953925813016709066456753528,
    29325755051117312382030606174497823938298400738,
    147640362277453187202751248536606552186500340793,
    138913879122126220032100791896142042412365949111,
    244366949591278081327026760920713394486522801115,
    298994502784450948170118141519643063797327888052,
    0,
    138718800163886349385511482689341304373920766476,
    0,
    0,
    133874066800820654874267531771457605237544548312,
    162818581718579015186768692396757262849522426776,
    139574678065197358389022868012607021705145511535,
    155822510547750862420294907910882239114145170964,
    0,
    0,
    0,
    0,
    0,
    0,
    139325906915408391006531101294574372398725713861,
    208728599292032521956455950168239613940579171534,
    0,
    127864469539363726075959357223399664735172685066,
    188591207483133925190700106842801378214960581145,
    0,
    253435893560152686083338962261574619042302207715,
    0,
    340972652152566919919001221990932730169553920318,
    0,
    0,
    86316913783417667448542211941399963708885374089,
    311133012666991141354510792438362181426816729541,
    328601892247421099105704165238221507277176536729,
    0,
    68397685696890583255472258167814086503506946251,
    98488271750736770260196990990036766419451087414,
    0,
    0]

def rowTab : Fin 3 -> Fin 64 -> Nat := ![row0, row1, row2]

/-- Projective fingerprints, literal-identical to
`_RateHalfBaseFingerprintTable.fingerprintNat` (core-major,
outside-coordinate-minor order). -/
def fingerprintNat : Fin 93 -> Nat := ![
    6524216619379419265027960032285007280893416965,
    124045888548991012736551520256877363283554819126,
    78205154655305592335202998084031357481682584985,
    193163137771712671399382555976978509067032379327,
    80405763652083154931159960361737193112124351887,
    233209580125730856075147370922624716358323973644,
    63500761785130131375806454974459905064328302409,
    255271560274919704367899464910020595596305052979,
    23218018856862058350780878839988572819246617791,
    327968385387143433355941028662515983003555122452,
    160227487706596530280162528523106857477904018409,
    350066523534860444954003745662062651141265912872,
    247375374864416193136572476606388625351761672888,
    19152798527870669990011534388362830168229803478,
    327800481380033275466383605881432803796081172570,
    8758918359624234876649019779507409579865834583,
    32662660518444309544028608452408812686536313085,
    322757489273476040533894234847536105439978835461,
    228977910271476943702717001844190279532546087657,
    103046290960354110358959156733706599594187337050,
    157797791731897865391506902775241396691019619269,
    137047700522270319501854905935916932226959007359,
    131960141982292042329686819381209987500809960271,
    304690352079809913371286578201207705457482375165,
    336753677675989098798027218305782685865790219090,
    355954687579624268554276994344975936368224276880,
    139633254193999289888939480853440839629936389340,
    141751582429381237706743011508296641668266808232,
    279740617563882562523848563003446383662202245636,
    131823367490334859432005074315257073954562062752,
    359667351493780480783782066520321081523604711712,
    242414808873686220968007206655632129203548729448,
    138263457746687149530300047949748173509393533449,
    221850621812594939052438426941778736087519426184,
    277592505980696768087647951861044698282535905620,
    356652007073726325362218282000107144207644595322,
    252452731526049864794473861435024994767742927417,
    142623155316006674093120682369561121464590778775,
    160573670249780903752970269277377435091935729524,
    279978407065829833991792435262396706952298556237,
    247361413343501707437065819658213115674546547523,
    75176667982885008193841496360703386924092719808,
    317605262987410174573200345138873593258567263078,
    105342519473030271217590481482748338161978472139,
    198542067850714490487364434347611029597163042271,
    305805445250679395751630309627464431731696556207,
    55803696533312492916550270037410774191622803524,
    315179611673057301103228756955997021054665204795,
    269493264129862683986264789824619420625075459108,
    206427512949095726427148588523281526611606581360,
    298841136466685667950929925604265079861041718647,
    136868521762370108693503889343212603274729878238,
    302732280435343671380822042287064401797328883823,
    205305449498720247080394673451582411830556845916,
    247222755712635283276891364512359244482140415229,
    37588333991442504096920748180351693462046359904,
    193329321602975454467871340027414897562093870532,
    235246627816890490664368031088191730213677439845,
    137819796880267066363940662252709740246905401938,
    22473703298592912158413662440463315722446412680,
    141710940848925069793832778935509062183192567114,
    134746632064931341993132394912309710312537729554,
    268034455056125492782044832515486280524632269565,
    280384322054880254845585159087635324640070213483,
    257173911236812697240492113010413275005749511866,
    350122604952306266813759635061499055954229496958,
    95251791767022357444218835704023667080625045909,
    192764302054317204352458229514277488856560114488,
    141023403904683691480536701831368356626086440254,
    323067364520036363119263659095390595241599755027,
    327296330549663588109344172166560797306071936879,
    116813929089819384338817592311201993338063192907,
    97780344044954062752999670716685216550333530861,
    157272829917118727340755757866966840830406340771,
    21829971080456242739359033513609721031836609280,
    214594273134773447091817263027887209888396723768,
    285666828152390618209027296047448528597118602072,
    44177871775144706979071583254440014730428385128,
    335650038642704830628915551035483425671861050931,
    30465997243174182964042912625670628846137694857,
    7186056602083308053912767094400036521272374956,
    91650969923244945179001512680835425833367074782,
    232811628346734081320095220491727494039791902744,
    338140676786872208494129708258760481796413610378,
    152721965218371580943700046334350695930050395068,
    107297136567386723545908631513943604944198361884,
    61872307916401866148117216693536513958346328700,
    347158054120765095322643250715230470968746386977,
    207408216532690139037904495933487173367124348812,
    184128275891599264127774350402216581042259028911,
    103511632588387616076760675233867322809628177812,
    81691221358082787513702789644468558453813714546,
    294302854315108558433711175159509436411419687649]


/-! ## Exact modular arithmetic (kernel-cheap shapes) -/

/-- The `i`-th point of `mu_64` as a natural residue (`0` out of range). -/
def dom (i : Nat) : Nat := domList.getD i 0

def mulP (a b : Nat) : Nat := a * b % P

def subP (a b : Nat) : Nat := (a + P - b) % P

def prodP : List Nat -> Nat
  | [] => 1
  | x :: xs => mulP x (prodP xs)

/-- Structurally recursive fuel wrapper for kernel-cheap square-and-multiply
(shape from `_PrizeShapePrimeP30.binaryPowAux`). -/
def powAux (a n : Nat) : Nat -> Nat
  | 0 => 1
  | fuel + 1 =>
      if n = 0 then 1
      else if n % 2 = 0 then powAux (mulP a a) (n / 2) fuel
      else mulP a (powAux (mulP a a) (n / 2) fuel)

def powP (a n : Nat) : Nat := powAux a n (n + 1)

def invP (a : Nat) : Nat := powP a (P - 2)

/-! ## The Lagrange defect and its canonical row reduction -/

/-- Numerator factors of the external interpolation defect. -/
def numerFactors (c : Fin 3) (outside coord : Nat) : List Nat :=
  ((basis c).erase coord).map fun h => subP (dom outside) (dom h)

/-- Denominator factors of the external interpolation defect. -/
def denomFactors (c : Fin 3) (coord : Nat) : List Nat :=
  ((basis c).erase coord).map fun h => subP (dom coord) (dom h)

/-- Coefficient of the external interpolation defect for core `c` at outside
point `outside`, coordinate `coord`. -/
def defectN (c : Fin 3) (outside coord : Nat) : Nat :=
  if coord = outside then 1
  else if coord ∈ basis c then
    subP 0 (mulP (prodP (numerFactors c outside coord))
      (invP (prodP (denomFactors c coord))))
  else 0

def coreOf (i : Fin 93) : Fin 3 := ⟨i.val / 31, by have := i.isLt; omega⟩

def slotOf (i : Fin 93) : Fin 31 := ⟨i.val % 31, Nat.mod_lt _ (by norm_num)⟩

def outsideOf (i : Fin 93) : Nat := outside (coreOf i) (slotOf i)

/-- The canonical reduced representative of the `i`-th external defect:
subtract the pivot components against the reduced parity-check rows. -/
def directionNat (i : Fin 93) (c : Fin 64) : Nat :=
  subP (defectN (coreOf i) (outsideOf i) c.val)
    ((defectN (coreOf i) (outsideOf i) 0 * rowTab 0 c
      + defectN (coreOf i) (outsideOf i) 1 * rowTab 1 c
      + defectN (coreOf i) (outsideOf i) 2 * rowTab 2 c) % P)

/-! ## The 186 scalar evaluation facts (kernel-checked) -/

/-- 93 facts: every reduced direction is nonzero at chart coordinate 6. -/
theorem directionNat_six_ne_zero : forall i : Fin 93, directionNat i 6 ≠ 0 := by
  decide +kernel

/-- 93 facts: the coordinate-15/coordinate-6 chart ratio is the published fingerprint. -/
theorem directionNat_chart_eval :
    forall i : Fin 93, mulP (directionNat i 15) (invP (directionNat i 6)) =
      fingerprintNat i := by
  decide +kernel

/-- The reduction rows are pivot-normalized at columns 0,1,2 (RREF shape). -/
theorem rowTab_pivot :
    forall k l : Fin 3, rowTab k ⟨l.val, by have := l.isLt; omega⟩ =
      if k = l then 1 else 0 := by
  decide

/-! ## Cast bridge to the certified field -/

theorem P_pos : 0 < P := by norm_num

theorem mulP_lt (a b : Nat) : mulP a b < P := Nat.mod_lt _ P_pos

theorem subP_lt (a b : Nat) : subP a b < P := Nat.mod_lt _ P_pos

theorem directionNat_lt (i : Fin 93) (c : Fin 64) : directionNat i c < P :=
  subP_lt _ _

theorem natCast_mulP (a b : Nat) :
    ((mulP a b : Nat) : ZMod P) = (a : ZMod P) * (b : ZMod P) := by
  rw [mulP, ZMod.natCast_mod, Nat.cast_mul]

theorem natCast_subP (a b : Nat) (hb : b ≤ P) :
    ((subP a b : Nat) : ZMod P) = (a : ZMod P) - (b : ZMod P) := by
  rw [subP, ZMod.natCast_mod, Nat.cast_sub (hb.trans (Nat.le_add_left P a)),
    Nat.cast_add, ZMod.natCast_self, add_zero]

theorem natCast_prodP (l : List Nat) :
    ((prodP l : Nat) : ZMod P) = (l.map fun x => (x : ZMod P)).prod := by
  induction l with
  | nil => simp [prodP]
  | cons x xs ih => simp [prodP, natCast_mulP, ih]

theorem natCast_powAux (a n fuel : Nat) (hfuel : n < fuel) :
    ((powAux a n fuel : Nat) : ZMod P) = (a : ZMod P) ^ n := by
  induction fuel generalizing a n with
  | zero => omega
  | succ fuel ih =>
      rw [powAux]
      split_ifs with h0 heven
      · subst n
        simp
      · have hpos : 0 < n := Nat.pos_of_ne_zero h0
        have hhalf : n / 2 < fuel :=
          (Nat.div_lt_self hpos (by norm_num)).trans_le (by omega)
        rw [ih (mulP a a) (n / 2) hhalf, natCast_mulP, ← pow_two, ← pow_mul]
        congr 1
        exact Nat.mul_div_cancel' ((Nat.dvd_iff_mod_eq_zero).mpr heven)
      · have hpos : 0 < n := Nat.pos_of_ne_zero h0
        have hhalf : n / 2 < fuel :=
          (Nat.div_lt_self hpos (by norm_num)).trans_le (by omega)
        rw [natCast_mulP, ih (mulP a a) (n / 2) hhalf, natCast_mulP,
          ← pow_two, ← pow_mul, ← pow_succ']
        congr 1
        omega

theorem natCast_powP (a n : Nat) :
    ((powP a n : Nat) : ZMod P) = (a : ZMod P) ^ n :=
  natCast_powAux a n (n + 1) (by omega)

local instance : Fact (Nat.Prime P) := ⟨prime_P⟩
local instance : NeZero P := ⟨P_pos.ne'⟩

theorem natCast_ne_zero_of_ne_zero_of_lt {a : Nat} (h0 : a ≠ 0) (hlt : a < P) :
    (a : ZMod P) ≠ 0 := by
  intro h
  have hdvd := (ZMod.natCast_eq_zero_iff a P).mp h
  exact absurd (Nat.le_of_dvd (Nat.pos_of_ne_zero h0) hdvd) (not_le.mpr hlt)

theorem natCast_invP_eq_inv (a : Nat) (ha : (a : ZMod P) ≠ 0) :
    ((invP a : Nat) : ZMod P) = (a : ZMod P)⁻¹ := by
  rw [invP, natCast_powP]
  have hone : (a : ZMod P) ^ (P - 1) = 1 := ZMod.pow_card_sub_one_eq_one ha
  have hexp : P - 2 + 1 = P - 1 := by norm_num
  have hmul : (a : ZMod P) * (a : ZMod P) ^ (P - 2) = 1 := by
    rw [← pow_succ', hexp]
    exact hone
  exact eq_inv_of_mul_eq_one_right hmul

/-! ## The direction family in the certified field -/

/-- The 93 reduced external-defect directions, as vectors in the certified field. -/
def direction (i : Fin 93) (c : Fin 64) : ZMod P := (directionNat i c : ZMod P)

/-- The fingerprint table in the certified field (literal-identical to
`_RateHalfBaseFingerprintTable.fingerprint`). -/
def fingerprint : Fin 93 -> ZMod P := fun i => fingerprintNat i

theorem fingerprintNat_lt_prime : forall i, fingerprintNat i < P := by decide

theorem fingerprintNat_injective : Function.Injective fingerprintNat := by decide

theorem fingerprint_injective : Function.Injective fingerprint := by
  intro i j h
  apply fingerprintNat_injective
  have hval := congrArg ZMod.val h
  rwa [fingerprint, fingerprint, ZMod.val_natCast_of_lt (fingerprintNat_lt_prime i),
    ZMod.val_natCast_of_lt (fingerprintNat_lt_prime j)] at hval

/-- **h6, sealed.**  The first 93 scalar facts in the consumer's field-level shape. -/
theorem direction_six_ne_zero : forall i, direction i 6 ≠ 0 := fun i =>
  natCast_ne_zero_of_ne_zero_of_lt (directionNat_six_ne_zero i) (directionNat_lt i 6)

/-- **hchart, sealed.**  The second 93 scalar facts in the consumer's field-level shape. -/
theorem direction_chart :
    forall i, direction i 15 / direction i 6 = fingerprint i := by
  intro i
  have h6 : (directionNat i 6 : ZMod P) ≠ 0 :=
    natCast_ne_zero_of_ne_zero_of_lt (directionNat_six_ne_zero i) (directionNat_lt i 6)
  calc direction i 15 / direction i 6
      = (directionNat i 15 : ZMod P) * (directionNat i 6 : ZMod P)⁻¹ :=
        div_eq_mul_inv _ _
    _ = (directionNat i 15 : ZMod P) * ((invP (directionNat i 6) : Nat) : ZMod P) := by
        rw [natCast_invP_eq_inv _ h6]
    _ = ((mulP (directionNat i 15) (invP (directionNat i 6)) : Nat) : ZMod P) :=
        (natCast_mulP _ _).symm
    _ = fingerprint i := by rw [directionNat_chart_eval i]; rfl

/-! ## Composed base separation (hypothesis-free)

The proof below restates `_RateHalfBaseFingerprintTable.projectively_separated_of_chart`
verbatim (that file is in-flight/uncommitted, so it cannot be imported yet; the splice
replaces this restatement by a direct application once the table file lands). -/

/-- **Composed base certificate.**  The 93 concrete reduced defect directions are
pairwise projectively distinct — no free hypotheses. -/
theorem direction_projectively_separated :
    forall i j, (exists c : ZMod P, direction i = c • direction j) -> i = j := by
  intro i j hproj
  apply fingerprint_injective
  rw [← direction_chart i, ← direction_chart j]
  obtain ⟨c, hc⟩ := hproj
  have h6eq := congrFun hc (6 : Fin 64)
  have h15eq := congrFun hc (15 : Fin 64)
  simp only [Pi.smul_apply, smul_eq_mul] at h6eq h15eq
  rw [h6eq, h15eq]
  have hcne : c ≠ 0 := by
    intro hc0
    rw [hc0, zero_mul] at h6eq
    exact direction_six_ne_zero i h6eq
  field_simp

/-- **Composed lifted certificate.**  At every radix `m ≥ 2` the `93*m` lifted
rank-one directions are pairwise projectively distinct — no free hypotheses.
At the prize radix `m = 2^24` this realizes `93m > 64m = 2^30` distinct
projective labels, the count consumed by
`_RateHalfThreeCoreRadixArithmetic.badCount_gt_length_of_injected_directions`. -/
theorem direction_lifted_projectively_separated (m : Nat) (hm : 2 ≤ m) :
    forall (i j : Fin 93) (x y c : ZMod P),
      RankOneTensorProjectiveInjection.outer
          (direction i) (RankOneTensorProjectiveInjection.vandermonde m x) =
        c • RankOneTensorProjectiveInjection.outer
          (direction j) (RankOneTensorProjectiveInjection.vandermonde m y) ->
        i = j ∧ x = y := by
  apply RankOneTensorProjectiveInjection.outer_vandermonde_projectively_injective
    m hm direction
  · intro i hi
    exact direction_six_ne_zero i (congrFun hi (6 : Fin 64))
  · exact direction_projectively_separated

/-! ## Transparency layer for the downstream splice

The reduced representative is definitionally the Lagrange defect minus its
pivot combination against `rowTab`; these lemmas expose that shape in field
language so the downstream annihilator identification (rows span the actual
parity checks) can consume `direction` without re-evaluating anything. -/

theorem natCast_direction_decomposition (i : Fin 93) (c : Fin 64) :
    direction i c =
      (defectN (coreOf i) (outsideOf i) c.val : ZMod P) -
        ((defectN (coreOf i) (outsideOf i) 0 : ZMod P) * (rowTab 0 c : ZMod P)
          + (defectN (coreOf i) (outsideOf i) 1 : ZMod P) * (rowTab 1 c : ZMod P)
          + (defectN (coreOf i) (outsideOf i) 2 : ZMod P) * (rowTab 2 c : ZMod P)) := by
  rw [direction, directionNat, natCast_subP _ _ (Nat.mod_lt _ P_pos).le,
    ZMod.natCast_mod]
  push_cast
  ring_nf

/-- The Lagrange shape of the defect coefficient at an interpolation-basis
coordinate, in field language. -/
theorem natCast_defectN_basis (c : Fin 3) (outsideCoord coord : Nat)
    (hne : coord ≠ outsideCoord) (hmem : coord ∈ basis c)
    (hden : ((prodP (denomFactors c coord) : Nat) : ZMod P) ≠ 0) :
    ((defectN c outsideCoord coord : Nat) : ZMod P) =
      -((((numerFactors c outsideCoord coord).map fun x => (x : ZMod P)).prod) *
        ((((denomFactors c coord).map fun x => (x : ZMod P)).prod)⁻¹)) := by
  rw [defectN, if_neg hne, if_pos hmem,
    natCast_subP _ _ (mulP_lt _ _).le, natCast_mulP,
    natCast_invP_eq_inv _ hden, natCast_prodP, natCast_prodP,
    Nat.cast_zero, zero_sub]

/-- The evaluation domain really is the smooth `mu_64` subgroup of the prize
field: `dom i` is the `2^24 * i`-th power of the certified order-`2^30`
generator. -/
theorem dom_spec :
    forall i : Fin 64, dom i.val = powP (ZMod.val g) (2 ^ 24 * i.val) := by
  decide +kernel

theorem natCast_dom (i : Fin 64) :
    ((dom i.val : Nat) : ZMod P) = g ^ (2 ^ 24 * i.val) := by
  rw [dom_spec i, natCast_powP, ZMod.natCast_zmod_val]

end ArkLib.ProximityGap.Frontier.W7RateHalfFingerprintSeal

/-! ## Axiom audit -/

open ArkLib.ProximityGap.Frontier.W7RateHalfFingerprintSeal
#print axioms directionNat_six_ne_zero
#print axioms directionNat_chart_eval
#print axioms rowTab_pivot
#print axioms direction_six_ne_zero
#print axioms direction_chart
#print axioms fingerprint_injective
#print axioms direction_projectively_separated
#print axioms direction_lifted_projectively_separated
#print axioms natCast_direction_decomposition
#print axioms natCast_defectN_basis
#print axioms natCast_dom
