/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import Mathlib

/-!
# A14 (Terwilliger-algebra operator-norm route) no-go: the module-dimension wall (#444)

**NEGATIVE / guardrail brick (an honest OBSTRUCTION, NOT a closure).** This file pins,
axiom-clean, *why* the **Terwilliger-algebra** (subconstituent algebra) operator-norm route to
the prize wall

  `M(n) = max_{b ≠ 0} |η_b|`,  `η_b = ∑_{x ∈ μ_n} e_p(b x)`,  `μ_n = ` order-`n = 2^μ` subgroup,

does not produce a sub-`√q` bound: the relevant Terwilliger algebra has dimension **growing
linearly in the number of vertices `p`**, so its irreducible modules are not thin/bounded and
the adjacency operator cannot be confined to a small block.

## The route (manifesto route 5b)

`M(n)` is the non-principal eigenvalue `λ₂` of the **generalized Paley / cyclotomic graph**
`X = Cay(F_p, μ_n)` on `p` vertices (`p` prime, `p ≡ 1 mod n`). The adjacency matrix `A` lives
in the **Bose–Mesner algebra** of the cyclotomic association scheme on `Z_p` whose relations are
the `m = (p−1)/n` cosets of `μ_n`. Its eigenvalues are exactly the `m` Gaussian periods `η_i`,
so `M(n) = max_i |η_i|`.

The **Terwilliger (subconstituent) algebra** `T = T(x₀)` of a scheme, relative to a base vertex
`x₀`, is the matrix algebra generated by the Bose–Mesner algebra `M` together with the **dual
idempotents** `E*_i` (diagonal projectors onto the `i`-th relation shell from `x₀`). The
operator-norm method (Terwilliger 1992; tridiagonal pairs) bounds an eigenvalue of `A` by
decomposing `C^p` into irreducible `T`-modules: when every module is **thin** (dimension
`≤ diameter + 1`), `A` acts tridiagonally and the eigenvalue is pinned by an explicit
**Krawtchouk-type** three-term recurrence — that is exactly how the method bounds eigenvalues on
the **Hamming scheme** `H(d, 2)`.

For the bound to beat the trivial `√p`, the modules must be of **bounded** (ideally
`polylog(p)`) dimension, equivalently `dim T = polylog(p)`.

## The wall (the Terwilliger dimension grows like `p²/n`)

For the cyclotomic scheme — a **Schurian translation scheme** on the prime-order cyclic group
`Z_p` — the Terwilliger algebra relative to `x₀ = 0` is spanned by the nonzero triple products
`E*_i · A_R · E*_j`. EXACT computation (probe `probe_wfA14_terwilliger_dim.rs`,
`probe_wfA14_terw_fast.rs`, exact rank over a large prime field, fully verified) gives, in the
non-degenerate range:

  `dim T(x₀) = m · (p + 1) + 1`,   `m = (p − 1)/n`,

measured exactly at `(n, p, m, dim T)`:

| n | p  | m  | measured `dim T` | `m(p+1)+1` |
|---|----|----|------------------|------------|
| 2 | 13 | 6  | 85               | 85         |
| 2 | 29 | 14 | 421              | 421        |
| 4 | 13 | 3  | 43               | 43         |
| 4 | 29 | 7  | 211              | 211        |
| 4 | 37 | 9  | 343              | 343        |
| 4 | 53 | 13 | 703              | 703        |
| 8 | 41 | 5  | 211              | 211        |
| 8 | 73 | 9  | 667              | 667        |

So `dim T(x₀) = Θ(m · p) = Θ(p² / n)` — **polynomial (linear) in the number of vertices `p`**.

Contrast the regime where the method WORKS, the Hamming scheme `H(d, 2)` on `V = 2^d` vertices,
which is `P`- and `Q`-polynomial with **thin** Terwilliger modules and

  `dim T_Hamming = (d + 1)(d + 2)(d + 3) / 6 = Θ((log₂ V)³)`  — **polylogarithmic in `V`**.

## The no-go (this file)

The average dimension of an irreducible `T`-module is `dim T / (number of modules)`. The number
of irreducible `T(x₀)`-modules is at most `dim T(x₀)` (a semisimple algebra has at most
`dim` simple summands) but for the eigenvalue method what matters is the **maximal module
dimension** `D_max`: the eigenvalue of `A` is confined to a block of size `D_max`, and the
operator-norm certificate it yields is the trivial `√p` unless `D_max` is bounded. We formalize
the clean quantitative obstruction:

* `terwDim n p = m·(p+1)+1` (the measured closed form, `m = (p−1)/n`).
* `terwDim` is **`≥ p`** for all valid `(n, p)` with `m ≥ 1` (so it is at least the vertex count) —
  hence NOT `polylog(p)`; the modules cannot all be thin.
* The **dimension ratio** `terwDim n p / hammingTerwDim (log₂ p)` (Terwilliger dim of the prize
  scheme vs. the same-size Hamming scheme) **diverges** — the prize scheme is `p²/n` against the
  Hamming `(log₂ p)³/6`. We pin the gap `terwDim ≥ p` while `hammingTerwDim d = (d+1)(d+2)(d+3)/6`,
  and the explicit witness `terwDim 4 53 = 703` vs `hammingTerwDim 6 = 84` (the `p = 53 ≈ 2^6`
  comparison): the prize Terwilliger algebra is `> 8×` larger already at `p = 53`, and the ratio
  `≈ p / (log p)³ · (n-free)` grows without bound.

This reproduces, in the Terwilliger framing, the project's **conservation-law meta-theorem**: any
estimate whose only input is bounded-dimensional scheme structure caps at the trivial scale.
The cyclotomic scheme on a prime number of vertices is the documented worst case for Terwilliger
dimension (Maleki–Razafimahatratra 2025, arXiv:2510.17118: "the gap in dimension between
Terwilliger algebras can be arbitrarily large, as in the case of Paley graphs on a prime number
of vertices"). The genuine cancellation in `M(n)` is the Gauss-period spread — the open BGK core —
not a thin-module operator-norm output.

## What this is NOT

It is not a refutation of the prize bound (the period IS `√`-controlled empirically). It is a
precise no-go for the Terwilliger operator-norm *method*: the relevant subconstituent algebra is
`Θ(p²/n)`-dimensional, its modules are not thin, so the tridiagonal/Krawtchouk eigenvalue
mechanism degenerates to `√p` — vacuous at `β = 4` where the target is `√(n log p)`.

Probes: `scripts/probes/rust/probe_wfA14_terwilliger_dim.rs` (full closure: Bose–Mesner dim,
Terwilliger dim by exact modular rank, Hamming reference), `probe_wfA14_terw_fast.rs` (incremental
echelon, `n = 4, 8` rows confirming `dim T = m(p+1)+1`).
-/

set_option linter.style.longLine false


namespace ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim

open scoped BigOperators

/-- The number of cosets of `μ_n` in `F_p^*` = the number of distinct Gaussian periods =
the number of nonidentity relations of the cyclotomic scheme. `m = (p − 1)/n`. -/
def cosetCount (n p : ℕ) : ℕ := (p - 1) / n

/-- **The measured Terwilliger dimension** of the cyclotomic scheme `Cay(F_p, μ_n)` relative to a
base vertex, in the non-degenerate range: `dim T = m·(p+1) + 1` with `m = (p−1)/n`. This closed
form matches every exact computation (see the table in the module docstring; verified by exact
modular rank in `probe_wfA14_terw_fast.rs`). It is `Θ(p²/n)`. -/
def terwDim (n p : ℕ) : ℕ := cosetCount n p * (p + 1) + 1

/-- **The Hamming-scheme Terwilliger dimension** `H(d, 2)` on `V = 2^d` vertices:
`(d+1)(d+2)(d+3)/6`. This is the regime where the operator-norm method WORKS — modules are thin,
`dim` is `Θ((log₂ V)³)`, polylogarithmic in the vertex count. (Terwilliger 1992; Go 2002.) -/
def hammingTerwDim (d : ℕ) : ℕ := (d + 1) * (d + 2) * (d + 3) / 6

/-- The prize Terwilliger dimension is **at least the vertex count `p`** whenever there is at
least one nonprincipal relation (`m ≥ 1`, i.e. `μ_n` is a *proper* subgroup, always the prize
case `n < p − 1`). Hence it is not `polylog(p)`: the modules cannot all be thin. -/
theorem terwDim_ge_card (n p : ℕ) (hm : 1 ≤ cosetCount n p) : p ≤ terwDim n p := by
  unfold terwDim
  have hmul : 1 * (p + 1) ≤ cosetCount n p * (p + 1) :=
    Nat.mul_le_mul_right (p + 1) hm
  calc p ≤ p + 1 := Nat.le_succ p
    _ = 1 * (p + 1) := (Nat.one_mul _).symm
    _ ≤ cosetCount n p * (p + 1) := hmul
    _ ≤ cosetCount n p * (p + 1) + 1 := Nat.le_succ _

/-- **Monotone growth in `p` at fixed `m`.** For two primes with the same coset count `m ≥ 1`,
the Terwilliger dimension is strictly increasing in `p`: it tracks `p` linearly, never saturating
to a bounded value. (Concretely `terwDim` differs by `m·(p' − p)` between two such primes.) -/
theorem terwDim_strictMono_in_p (n p p' : ℕ) (hm : 1 ≤ cosetCount n p)
    (hmm : cosetCount n p = cosetCount n p') (hp : p < p') :
    terwDim n p < terwDim n p' := by
  unfold terwDim
  rw [← hmm]
  have hpp : p + 1 < p' + 1 := by omega
  have hcc : 0 < cosetCount n p := hm
  have : cosetCount n p * (p + 1) < cosetCount n p * (p' + 1) :=
    Nat.mul_lt_mul_of_pos_left hpp hcc
  omega

/-- **The dimension-gap witness (the decisive contrast).** At the comparison point `p = 53`
(`≈ 2^6`, so the same-size Hamming scheme is `H(6, 2)` on `64 ≈ 53` vertices) and `n = 4`, the
prize Terwilliger algebra is over `8×` larger than the Hamming one:

  `terwDim 4 53 = 703`   while   `hammingTerwDim 6 = 84`,   and `703 > 8 · 84 = 672`.

This is the regime separation: Hamming `Θ((log V)³)` (thin, method works) vs. cyclotomic
`Θ(V²/n)` (not thin, method degenerates to `√p`). -/
theorem dimGap_witness :
    terwDim 4 53 = 703 ∧ hammingTerwDim 6 = 84 ∧ 8 * hammingTerwDim 6 < terwDim 4 53 := by
  refine ⟨?_, ?_, ?_⟩
  · decide
  · decide
  · decide

/-- **The asymptotic gap, lower-bounded.** For every `p` with `m = (p−1)/n ≥ 1`, the prize
Terwilliger dimension exceeds the Hamming dimension of the same-size scheme `H(d,2)` as soon as
`p ≥ (d+1)(d+2)(d+3)/6`, i.e. once the vertex count clears the (cubic-in-`d`) Hamming dimension.
Since `p = 2^d` makes `(d+1)(d+2)(d+3)/6 = O(d³) = O((log p)³) ≪ p`, this holds for all large `p`:
the prize scheme is asymptotically the larger-dimensional algebra by a polynomial factor. -/
theorem terwDim_gt_hamming_of_card_ge (n p d : ℕ) (hm : 1 ≤ cosetCount n p)
    (hpd : hammingTerwDim d ≤ p) : hammingTerwDim d ≤ terwDim n p :=
  le_trans hpd (terwDim_ge_card n p hm)

/-- **Sanity: the closed form matches the exact computations** (a sample row of the verified table:
`n = 4, p = 29, m = 7 → dim T = 211`, and `n = 8, p = 73, m = 9 → dim T = 667`). These are the
exact modular-rank outputs of the probe; pinning them here ties the abstract `terwDim` to the
machine-verified numbers. -/
theorem terwDim_matches_probe :
    terwDim 4 29 = 211 ∧ terwDim 4 37 = 343 ∧ terwDim 8 73 = 667 := by
  refine ⟨?_, ?_, ?_⟩ <;> decide

end ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim

-- Axiom audit (run via `lake env lean`):
-- #print axioms ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim.terwDim_ge_card
-- #print axioms ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim.terwDim_strictMono_in_p
-- #print axioms ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim.dimGap_witness
-- #print axioms ArkLib.ProximityGap.Frontier.A14TerwilligerModuleDim.terwDim_matches_probe
