// Exact arithmetic over F_17. The domain is the order-eight subgroup generated by 2.
export const FIELD = 17;
export const DOMAIN = [1, 2, 4, 8, 16, 15, 13, 9];
export const MESSAGE = [1, 2, 3, 1];

export function encode(coefficients: number[]): number[] {
  return DOMAIN.map((x) => coefficients.reduceRight((value, a) => (value * x + a) % FIELD, 0));
}

export const ORIGINAL = encode(MESSAGE);

export function example(errors: number) {
  if (!Number.isInteger(errors) || errors < 0 || errors > 4) throw new RangeError("Choose 0–4 symbol errors");
  const received = ORIGINAL.map((symbol, i) => i < errors ? (symbol + 5) % FIELD : symbol);
  const samples: number[][] = [];
  let count = 0;
  // Enumerate every degree-<4 polynomial exactly; no random sampling or approximation.
  for (let a = 0; a < FIELD; a++) for (let b = 0; b < FIELD; b++)
    for (let c = 0; c < FIELD; c++) for (let d = 0; d < FIELD; d++) {
      const word = encode([a, b, c, d]);
      const distance = word.reduce((total, value, i) => total + Number(value !== received[i]), 0);
      if (distance <= errors) {
        count++;
        if (samples.length < 3) samples.push(word);
      }
    }
  return { received, count, samples };
}
