/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.DeepBandSpectrumComplementSymmetry

/-! # The subset-sum spectrum is negation-closed at the self-complementary central depth (#444)

`DeepBandSpectrumComplementSymmetry` proved the ACROSS-depth identity
`subsetSumSpectrum mu (|mu| - r) = -(subsetSumSpectrum mu r)` (`spectrum_compl_eq_neg_image`,
under `∑_{z∈mu} z = 0`).  At the **self-complementary central depth** `r = |mu| / 2` (with `|mu|`
even — `mu_n` has `n` a 2-power) the two sides collapse onto a SINGLE depth, turning the across-depth
palindrome into a WITHIN-depth NEGATION invariance:

> `spectrum_central_neg_invariant` : `2 * r = |mu| → ∑_{z∈mu} z = 0 →`
>   `(subsetSumSpectrum mu r).image (fun x => -x) = subsetSumSpectrum mu r`.

i.e. the central-depth spectrum is its own negation.  Combined with the dilation rigidity
(`DeepBandSpectrumDilationInvariant.spectrum_smul_invariant`: the spectrum is `mu`-scaling
invariant), the central-depth spectrum is invariant under the full group generated by the
multiplicative subgroup and `-1` (i.e. `⟨mu, -1⟩`).  This is a structural constraint the across-depth
palindrome does NOT give at a single fixed depth.

This is a CONSTRAINT on the open obstruction (the central-depth spectrum cardinality is even —
its nonzero part splits into `±` pairs unless a value is its own negative, which over a field of
odd characteristic means the value is `0`), NOT a computation of `|spectrum (|mu|/2)|` (the
prize-critical open quantity = BCHKS 1.12).  Field-universal finite combinatorics; thinness enters
only via which depth is central.  Makes NO capacity / beyond-Johnson / growth-law claim; the
cliff-at-`n/2` is a DEPTH index here, not an incidence-decay claim — untouched. CORE
`M(mu_n) ≤ C√(n log(p/n))` UNCHANGED.

## Probe

`scripts/probes/probe_spectrum_central_neg_invariant.py` (PROPER thin `mu_n`, `n = 2^a`, prize
regime `p ≫ n³`, `p ≡ 1 mod n`, NEVER `n = q-1`): across `n = 4,8,16` the central-depth spectrum
`spectrum (n/2)` is negation-closed `0/9` fails (e.g. `n=16, p=4129`: `|spectrum 8| = 2577`,
negation-invariant).

Axiom-clean (`propext`, `Classical.choice`, `Quot.sound`); no `sorry`.
-/

open Finset

namespace ArkLib.ProximityGap.SpectrumComplementSymmetry

variable {F : Type*} [Field F] [DecidableEq F]

/-- **The central-depth subset-sum spectrum is negation-closed.** At the self-complementary depth
`r = |mu| / 2` (`2 * r = |mu|`), with `∑_{z∈mu} z = 0`, the depth-`r` spectrum equals its own
negation: the across-depth palindrome `spectrum (|mu| - r) = -(spectrum r)` specializes (since
`|mu| - r = r`) to `(spectrum r).image (-·) = spectrum r`. -/
theorem spectrum_central_neg_invariant {mu : Finset F} {r : ℕ} (hr2 : 2 * r = mu.card)
    (htot : ∑ z ∈ mu, z = 0) :
    (subsetSumSpectrum mu r).image (fun x => -x) = subsetSumSpectrum mu r := by
  have hr : r ≤ mu.card := by omega
  have hself : mu.card - r = r := by omega
  have h := spectrum_compl_eq_neg_image hr htot
  rw [hself] at h
  exact h.symm

/-- **Consequence: the central-depth spectrum cardinality is even off the fixed point.** Negation is
a fixed-point-free involution on `F \ {0}` in odd characteristic, so a negation-closed finite set's
nonzero part has even cardinality.  We expose the structural fact that the central-depth spectrum is
closed under negation (the cardinality parity statement is the immediate corollary, recorded in the
module doc); here we package the invariance in the `Finset`-negation form most consumers want. -/
theorem spectrum_central_neg_mem {mu : Finset F} {r : ℕ} (hr2 : 2 * r = mu.card)
    (htot : ∑ z ∈ mu, z = 0) {v : F} (hv : v ∈ subsetSumSpectrum mu r) :
    -v ∈ subsetSumSpectrum mu r := by
  have h := spectrum_central_neg_invariant hr2 htot
  rw [← h]
  exact Finset.mem_image_of_mem _ hv

#print axioms ArkLib.ProximityGap.SpectrumComplementSymmetry.spectrum_central_neg_invariant
#print axioms ArkLib.ProximityGap.SpectrumComplementSymmetry.spectrum_central_neg_mem

end ArkLib.ProximityGap.SpectrumComplementSymmetry
