/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.GranularityLadderRS
import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots

/-!
# Exact δ* for the explicit smooth NTT Reed–Solomon family (granularity regime)

The granularity ladder `mcaDeltaStar_rs_eq_granularity` pins `δ*` in closed form for *any*
injective evaluation domain.  This file specializes it to the **explicit smooth (NTT) domain**
`dom : i ↦ ω^i` on the multiplicative subgroup `μ_n = ⟨ω⟩` generated by a primitive `n`-th root
of unity — the exact domain shape the Proximity Prize uses (smooth two-power `n = 2^μ`).

The result is a fully explicit, unconditional, axiom-clean **exact** `δ*` value for an infinite
family of explicit smooth Reed–Solomon codes:

  `mcaDeltaStar (RS[F, ⟨ω⟩, k]) ε* = j / n`   for every `ε* ∈ [j/q, (j+1)/q)`

on the granularity bands `3(j−1)+k ≤ n`.  This is the smooth-domain instantiation of the ladder:
it pins `δ*` exactly in the sub-budget regime `q ≲ n·2^{128}` (where `ε*·q` stays within the
staircase's reach).  It does **not** touch the open window-interior prize regime — there `ε*·q`
exceeds the staircase and `δ*` is governed by the BGK/Paley wall — but it is a genuine exact
determination for the explicit smooth NTT family, beyond the toy `F5`/`F17`/`F11` point pins.
-/

open Finset Polynomial
open scoped NNReal ENNReal

namespace ProximityGap.SpikeFloor

variable {F : Type} [Field F] [Fintype F] [DecidableEq F]
variable {n : ℕ} [NeZero n]

/-- The smooth **NTT evaluation domain** `i ↦ ω^i` for a primitive `n`-th root of unity `ω`,
as an injective map `Fin n ↪ F`.  Injectivity is exactly primitivity (`IsPrimitiveRoot.pow_inj`
on the range `i < n`). -/
def nttDom {ω : F} (hω : IsPrimitiveRoot ω n) : Fin n ↪ F :=
  ⟨fun i => ω ^ (i : ℕ), fun i j h => Fin.ext (hω.pow_inj i.isLt j.isLt h)⟩

@[simp] theorem nttDom_apply {ω : F} (hω : IsPrimitiveRoot ω n) (i : Fin n) :
    nttDom hω i = ω ^ (i : ℕ) := rfl

/-- **Exact `δ*` for the explicit smooth NTT Reed–Solomon family (granularity ladder).**

For the Reed–Solomon code on the smooth domain `μ_n = ⟨ω⟩` (`ω` a primitive `n`-th root of unity),
any dimension `k`, any band index `j ≥ 1` with `3(j−1)+k ≤ n`, `j+1+k ≤ n`, `j+1 ≤ |F|`, and every
threshold `ε* ∈ [j/|F|, (j+1)/|F|)`:

  `mcaDeltaStar (RS[F, ⟨ω⟩, k]) ε* = j / n`.

Unconditional and axiom-clean — the smooth-domain instantiation of `mcaDeltaStar_rs_eq_granularity`.
At `n = 2^μ` and a smooth field this is the literal prize domain in the sub-budget regime. -/
theorem mcaDeltaStar_nttRS_eq_granularity {ω : F} (hω : IsPrimitiveRoot ω n) {k j : ℕ}
    (hj1 : 1 ≤ j) (hd3 : 3 * (j - 1) + k ≤ n) (hdj : j + 1 + k ≤ n)
    (hjF : j + 1 ≤ Fintype.card F) {εstar : ℝ≥0∞}
    (hlo : (j : ℝ≥0∞) / (Fintype.card F : ℝ≥0∞) ≤ εstar)
    (hhi : εstar < ((j + 1 : ℕ) : ℝ≥0∞) / (Fintype.card F : ℝ≥0∞)) :
    MCAThresholdLedger.mcaDeltaStar (F := F) (A := F)
      ((rsCode (nttDom hω) k : Submodule F (Fin n → F)) : Set (Fin n → F)) εstar
      = (j : ℝ≥0) / (Fintype.card (Fin n) : ℝ≥0) :=
  mcaDeltaStar_rs_eq_granularity (nttDom hω) hj1 hd3 hdj hjF hlo hhi

end ProximityGap.SpikeFloor

-- Axiom audit (expected: propext, Classical.choice, Quot.sound only)
#print axioms ProximityGap.SpikeFloor.mcaDeltaStar_nttRS_eq_granularity
