/-
Copyright (c) 2026 ArkLib Contributors. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ArkLib Contributors
-/
import ArkLib.Data.CodingTheory.ProximityGap.MCAProjectiveEquivariance

/-!
# Projective MCA events in quotient-support coordinates

For a linear code `C`, a witness set `S` determines the subspace of quotient classes having a
representative which vanishes on `S`.  Line explainability is membership of the combined quotient
class in that subspace, while joint explainability is simultaneous membership of both row classes.

This gives an exact, basis-independent support-subspace description of the projective bad-slot
event.  It is a dictionary for the remaining incidence problem, not an incidence bound.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

open scoped NNReal
open ProximityGap

namespace ProximityGap.ProjectiveQuotientSupport

variable {ι : Type} [Fintype ι] [Nonempty ι] [DecidableEq ι]
variable {F : Type} [Field F] [Fintype F] [DecidableEq F]
variable {A : Type} [Fintype A] [DecidableEq A] [AddCommGroup A] [Module F A]

/-- Words which vanish on the coordinate set `S`. -/
def vanishOn (S : Finset ι) : Submodule F (ι → A) where
  carrier := {e | ∀ i ∈ S, e i = 0}
  zero_mem' := by simp
  add_mem' := by
    intro e f he hf i hi
    simp [he i hi, hf i hi]
  smul_mem' := by
    intro a e he i hi
    simp [he i hi]

@[simp] theorem mem_vanishOn_iff (S : Finset ι) (e : ι → A) :
    e ∈ vanishOn (F := F) S ↔ ∀ i ∈ S, e i = 0 :=
  Iff.rfl

/-- Quotient classes which have a representative vanishing on `S`. -/
def quotientSupportSubmodule (C : Submodule F (ι → A)) (S : Finset ι) :
    Submodule F ((ι → A) ⧸ C) :=
  (vanishOn (F := F) S).map (Submodule.mkQ C)

/-- The basis-free quotient pencil generated by the two row classes. -/
def quotientPencil (C : Submodule F (ι → A)) (u₀ u₁ : ι → A) :
    Submodule F ((ι → A) ⧸ C) :=
  Submodule.span F
    {Submodule.Quotient.mk (p := C) u₀, Submodule.Quotient.mk (p := C) u₁}

/-- A submodule contains the quotient pencil exactly when it contains both row generators. -/
theorem quotientPencil_le_iff
    (C : Submodule F (ι → A)) (u₀ u₁ : ι → A)
    (B : Submodule F ((ι → A) ⧸ C)) :
    quotientPencil C u₀ u₁ ≤ B ↔
      Submodule.Quotient.mk (p := C) u₀ ∈ B ∧
      Submodule.Quotient.mk (p := C) u₁ ∈ B := by
  rw [quotientPencil, Submodule.span_le]
  constructor
  · intro h
    exact ⟨h (by simp), h (by simp)⟩
  · rintro ⟨h₀, h₁⟩ q hq
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hq
    rcases hq with rfl | rfl
    · exact h₀
    · exact h₁

/-- A word class lies in the quotient support subspace exactly when some codeword agrees with the
word on `S`. -/
theorem quotient_mk_mem_quotientSupportSubmodule_iff
    (C : Submodule F (ι → A)) (S : Finset ι) (u : ι → A) :
    Submodule.Quotient.mk (p := C) u ∈ quotientSupportSubmodule C S ↔
      ∃ c ∈ C, ∀ i ∈ S, c i = u i := by
  constructor
  · rintro ⟨e, he, hmk⟩
    have hsub : u - e ∈ C :=
      (Submodule.Quotient.eq C).mp (by simpa using hmk.symm)
    refine ⟨u - e, hsub, ?_⟩
    intro i hi
    have hei : e i = 0 := he i hi
    simp [hei]
  · rintro ⟨c, hc, hagree⟩
    refine ⟨u - c, ?_, ?_⟩
    · intro i hi
      simp [hagree i hi]
    · apply (Submodule.Quotient.eq C).mpr
      have heq : (u - c) - u = -c := by abel
      rw [heq]
      exact C.neg_mem hc

/-- Joint explainability on `S` is simultaneous membership of the two row classes in the quotient
support subspace. -/
theorem pairJointAgreesOn_iff_quotientSupport
    (C : Submodule F (ι → A)) (S : Finset ι) (u₀ u₁ : ι → A) :
    pairJointAgreesOn (C : Set (ι → A)) S u₀ u₁ ↔
      Submodule.Quotient.mk (p := C) u₀ ∈ quotientSupportSubmodule C S ∧
      Submodule.Quotient.mk (p := C) u₁ ∈ quotientSupportSubmodule C S := by
  constructor
  · rintro ⟨c₀, hc₀, c₁, hc₁, hagree⟩
    constructor
    · exact (quotient_mk_mem_quotientSupportSubmodule_iff C S u₀).2
        ⟨c₀, hc₀, fun i hi => (hagree i hi).1⟩
    · exact (quotient_mk_mem_quotientSupportSubmodule_iff C S u₁).2
        ⟨c₁, hc₁, fun i hi => (hagree i hi).2⟩
  · rintro ⟨h₀, h₁⟩
    obtain ⟨c₀, hc₀, hagree₀⟩ :=
      (quotient_mk_mem_quotientSupportSubmodule_iff C S u₀).1 h₀
    obtain ⟨c₁, hc₁, hagree₁⟩ :=
      (quotient_mk_mem_quotientSupportSubmodule_iff C S u₁).1 h₁
    exact ⟨c₀, hc₀, c₁, hc₁, fun i hi => ⟨hagree₀ i hi, hagree₁ i hi⟩⟩

/-- **Exact quotient-support form of the homogeneous MCA event.**  A projective slot is bad
precisely when, on one admissible witness set, its combined quotient class has a vanishing
representative but the two row classes do not both have one. -/
theorem mcaEventProj_iff_quotientSupport
    (C : Submodule F (ι → A)) (δ : ℝ≥0) (u₀ u₁ : ι → A) (α β : F) :
    MCAProjectiveEquivariance.mcaEventProj
        (F := F) (C : Set (ι → A)) δ u₀ u₁ α β ↔
      ∃ S : Finset ι,
        (S.card : ℝ≥0) ≥ (1 - δ) * Fintype.card ι ∧
        Submodule.Quotient.mk (p := C) (α • u₀ + β • u₁) ∈
          quotientSupportSubmodule C S ∧
        ¬ (Submodule.Quotient.mk (p := C) u₀ ∈ quotientSupportSubmodule C S ∧
          Submodule.Quotient.mk (p := C) u₁ ∈ quotientSupportSubmodule C S) := by
  constructor
  · rintro ⟨S, hS, ⟨w, hw, hagree⟩, hno⟩
    refine ⟨S, hS, ?_, ?_⟩
    · apply (quotient_mk_mem_quotientSupportSubmodule_iff C S
        (α • u₀ + β • u₁)).2
      refine ⟨w, hw, ?_⟩
      intro i hi
      simpa using hagree i hi
    · simpa [pairJointAgreesOn_iff_quotientSupport C S u₀ u₁] using hno
  · rintro ⟨S, hS, hline, hno⟩
    obtain ⟨w, hw, hagree⟩ :=
      (quotient_mk_mem_quotientSupportSubmodule_iff C S
        (α • u₀ + β • u₁)).1 hline
    refine ⟨S, hS, ⟨w, hw, ?_⟩, ?_⟩
    · intro i hi
      simpa using hagree i hi
    · simpa [pairJointAgreesOn_iff_quotientSupport C S u₀ u₁] using hno

/-- **Basis-free quotient-pencil form of the homogeneous MCA event.**  A slot is bad precisely
when its combined class lies in one witness support subspace while the entire quotient pencil does
not. -/
theorem mcaEventProj_iff_quotientPencilSupport
    (C : Submodule F (ι → A)) (δ : ℝ≥0) (u₀ u₁ : ι → A) (α β : F) :
    MCAProjectiveEquivariance.mcaEventProj
        (F := F) (C : Set (ι → A)) δ u₀ u₁ α β ↔
      ∃ S : Finset ι,
        (S.card : ℝ≥0) ≥ (1 - δ) * Fintype.card ι ∧
        Submodule.Quotient.mk (p := C) (α • u₀ + β • u₁) ∈
          quotientSupportSubmodule C S ∧
        ¬ quotientPencil C u₀ u₁ ≤ quotientSupportSubmodule C S := by
  rw [mcaEventProj_iff_quotientSupport]
  constructor
  · rintro ⟨S, hS, hline, hnot⟩
    refine ⟨S, hS, hline, ?_⟩
    intro hle
    exact hnot ((quotientPencil_le_iff C u₀ u₁ _).1 hle)
  · rintro ⟨S, hS, hline, hnot⟩
    refine ⟨S, hS, hline, ?_⟩
    intro hmem
    exact hnot ((quotientPencil_le_iff C u₀ u₁ _).2 hmem)

end ProximityGap.ProjectiveQuotientSupport

/-! ## Axiom audit -/
#print axioms ProximityGap.ProjectiveQuotientSupport.mem_vanishOn_iff
#print axioms ProximityGap.ProjectiveQuotientSupport.quotientPencil_le_iff
#print axioms
  ProximityGap.ProjectiveQuotientSupport.quotient_mk_mem_quotientSupportSubmodule_iff
#print axioms ProximityGap.ProjectiveQuotientSupport.pairJointAgreesOn_iff_quotientSupport
#print axioms ProximityGap.ProjectiveQuotientSupport.mcaEventProj_iff_quotientSupport
#print axioms
  ProximityGap.ProjectiveQuotientSupport.mcaEventProj_iff_quotientPencilSupport
